### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by hagrid-sings** [intel/openvino-plugins-ai-audacity#10]
it would appear that, having unzipped the 2 files into the 'audacity' folder, the module 'mod-openvino.dll' has to be moved to the existing 'modules' folder to be recognised by audacity (what about all the other unzipped files?): however, changing the module from 'new' to 'enabled' wants to set 'open' & 'save' directories: why is this?

**Comment by RyanMetcalfeInt8** [comment]
Hi @hagrid-sings,

Did you follow this video?

https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/3f0b92ad-ddf5-438b-ab5a-2190ad1d72f1

The zip files are designed such that the contents can be extracted / dragged into the folder containing Audacity.exe. 

In other words, all of the DLL's except for mod-openvino.dll should be in the same folder as Audacity.exe. mod-openvino.dll should be inside 'modules' folder, and 'openvino-models' folder should be in same directory as Audacity.exe.

> changing the module from 'new' to 'enabled' wants to set 'open' & 'save' directories: why is this?

What do you mean by "wants to set 'open' & 'save' directories"? Could you elaborate?

Thanks!
Ryan

**Comment by hagrid-sings** [comment]
Hi Ryan,

 

Thanks for the clarification of the installation instructions: however, I am left with the problem that, when I ‘OK’ after changing ‘mod-openvino’ module from ‘new’ to ’enabled’, I get the following message:



 

When I ‘OK’ the message. I then get:



 

When I ‘OK’ the message, I get:



 

Please note that’directories’ is now selected and, if I ‘OK’, I go back to the first screen above: if I cancel, module is not enabled.

 

Best regards

 

Dave Viney

 

Tel: 078 02 24 83 26

**Comment by RyanMetcalfeInt8** [comment]
Hi @hagrid-sings, I think you intended to put some images into your response, but I don't see them above. Try adding a comment here directly.. it looks like you may have replied to the GitHub email?

Thanks,
Ryan

**Comment by hagrid-sings** [comment]
Hi Ryan,

it seems that this portal cant/wont handle screenshots which is pretty useless!

messages received when changing module from 'new' to 'enabled' are:

'open directory cannot be set' 'c:\x\y\z does not have write permissions' (where 'c:\x\y\z' is default directory path)
'save directory cannot be set' 'c:\x\y\z does not have write permissions' (where 'c:\x\y\z' is default directory path)

Best regards

Dave Viney

**Comment by RyanMetcalfeInt8** [comment]
hmm, odd -- so which directory is it complaining that it doesn't have write permissions for? 

At this stage, it should only need write permissions to update the audacity.cfg (and possibly other config-related files) in %appdata% directory. It seems odd that it wouldn't have write permissions to that. 

Does it also happen if you try changing other settings?

**Comment by hagrid-sings** [comment]
Thanks again Ryan: this would be so much easier with screenshots!

 

Enabling the module seems to be attempting to access the folder containing the default directories (normally set in the ‘preferences’ directories’ tab: also strange is that this folder is read-only and, even stranger, can’t be unset!

 

I have the latest version of Audacity installed but maybe it is corrupted and needs reinstalling?

 

Best regards

 

Dave Viney

 

Tel: 078 02 24 83 26

**Comment by RyanMetcalfeInt8** [comment]
Hi @hagrid-sings,

Sorry for the delayed response. It is definitely strange, and there are some weird permission issues going on here. Typically, files in Audacity installation folder (usually Program Files\Audacity) are read-only, while user settings and some other things that need to be cached on disk are written to %appdata% (C:\users\<username>\AppData\roaming\audacity). You can double check permissions for %appdata% outside of Audacity by simply trying to create or copy any file there (a simple .txt will do). If you are prompted for 'admin' access for that kind of operation, then there's definitely something weird going on...

If that works, I would say that you might want to re-install Audacity and try again.

>  this would be so much easier with screenshots!

You should be able to copy and paste screenshots directly into the GitHub chat box. Are you possibly replying through an email client?

**Comment by hagrid-sings** [comment]
Hi Ryan, i replied to your previous via email on 26/12 ('Hi Ryan, hope you had a great xmas: I think that I have now sorted this out: it seems that my open & save directories were referencing a non-existent folder and some of the openvino files hadn’t copied across correctly: I now see the 3 openvino effects in audacity though I haven’t tried using then yet…'): i have now tried the 'music separation' effect which is amazing! now trying to understand how it works...

**Comment by RyanMetcalfeInt8** [comment]
Hi @hagrid-sings -- great to hear you were able to get it working! 

>  now trying to understand how it works...

And just FYI, Music Separation uses the 'demucs v4' AI model & pipeline from here: https://github.com/facebookresearch/demucs We basically ported the AI model from pytorch to OpenVINO, and the surrounding pipeline from python to C++ to integrate into Audacity.

**Comment by hagrid-sings** [comment]
many thanks  Ryan for your support & info: much appreciated: i've discovered that the diffusion model employed is based on thermodynamic theory with maths well above my (degree level) understanding!
