### ISSUE TITLE
OpenVino modules dimmed or grayed out

### ISSUE THREAD

**Issue by bluto-vr** [intel/openvino-plugins-ai-audacity#104]
Has anyone else had the problem where audacity has loaded the OpenVino modules but they are dimmed or grayed out and can not be selected.  Very frustating.  Solutions?

**Comment by RyanMetcalfeInt8** [comment]
Hi @bluto-vr,

Hmm, you mean they are grayed out on 'effects' menu? Do you have any audio selected?

Thanks!
Ryan

**Comment by bluto-vr** [comment]
First, thanks for getting back to me. Much appreciated and you solved the
problem.  As soon as I put an audio file in it all worked perfectly.
Thanks again.

**Comment by RyanMetcalfeInt8** [comment]
Perfect, glad it is working!
