### ISSUE TITLE
Crashed after rebooting

### ISSUE THREAD

**Issue by BGbg1234** [intel/openvino-plugins-ai-audacity#105]
![vlcsnap-2024-04-08-14h34m47s911](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/db9a0ec4-35c5-4f08-925c-29e7e7a5ff5b)
![vlcsnap-2024-04-08-14h35m19s111](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/9dd4c467-bc51-4d7e-872a-9afb7af869c8)
![vlcsnap-2024-04-08-14h35m32s012](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/251d9cc6-a7d2-4291-bf6b-d48eee170e17)
![vlcsnap-2024-04-08-14h35m46s374](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/18778db0-2ae4-4bbc-b0c6-50eeba0fa658)
![vlcsnap-2024-04-08-14h36m05s068](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/a1b7b7cf-6ff5-41b7-b125-1b8fedda9978)
![vlcsnap-2024-04-08-14h36m20s309](https://github.com/intel/openvino-plugins-ai-audacity/assets/166370649/8fa880d0-3e4c-4869-a891-192be6f935ef)

**Comment by RyanMetcalfeInt8** [comment]
Hi @BGbg1234,

Strange, can you give some details about your PC setup, such as CPU & GPU model info and Windows OS version?

Thanks,
Ryan

**Comment by koneon** [comment]
I Have the same problem, I am on a dell latitude 5521 laptop. It has an i7 with 16gigs of ram. Running on windows 10.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/166790104/c0733e05-0859-4c59-9a74-6ee7e70d0edd)

**Comment by BGbg1234** [comment]
Lenovo Yoga 720 
Processor: ntel (R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Ram 8.00 GB
System Type 64-bit
Windows 11 Home Version: 23H2

The problem always starts when I change mod-openvino enabled and restart Audacity.

**Comment by RyanMetcalfeInt8** [comment]
Hi @koneon, @BGbg1234, 

Can you try the updated version of these plugins? https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Thanks!
Ryan
