### ISSUE TITLE
Different (essential) files cannot be opened 

### ISSUE THREAD

**Issue by LudoOSGS** [intel/openvino-plugins-ai-audacity#106]
Hello everyone,

After co-filing an issue [here](https://github.com/intel/openvino-plugins-ai-audacity/issues/83), I decided to give it a try on another computer.
However and very unfortunately, if I went a step further, it didn't bring any result, as far as I can make out.
Instead I got messages telling me [GENERAL ERROR] Model file ... ... cannot be opened!
![00000IMG_00000_BURST20240408180523_COVER~2](https://github.com/intel/openvino-plugins-ai-audacity/assets/102878346/de82ff8c-f40f-4399-a6b8-94de8ca8aa1b)

Some information on the computer I am at the moment working with:
![XRecorder_Edited_08042024_183053](https://github.com/intel/openvino-plugins-ai-audacity/assets/102878346/2d984a0b-f6ce-4d06-88c0-04c894dbec3a)

I hope this can help and a solution can be found.

I remain available to give any extra information.

Thanks for the great work!

Cheers and keep it up!

Ludo

**Comment by RyanMetcalfeInt8** [comment]
Hi Ludo!

From the log it looks like perhaps the 'openvino-models' folder wasn't dropped into the right location? If you followed the installation video exactly, you should see a bunch of these model files sitting in ```C:\Program Files\Audacity\openvino-models```. 

One common issue I've seen, is if user's extract the zip file in a different way and it creates an 'extra' openvino-models folder (e.g. ```C:\Program Files\Audacity\openvino-models\openvino-models```)

Can you double check?

Thanks,
Ryan

**Comment by LudoOSGS** [comment]
Hi Ryan,

Thanks for your answer.

I found the video pretty straightforward indeed; I thought I did exactly the same way...
I'm not at home right now, but I'll definitely double check this evening.

Cheers

Ludo

**Comment by LudoOSGS** [comment]
Hi Ryan,

Oops!

Yes indeed, I don't know how it happened but yes: inside the first openvino-models directory, there was a second one!
So I corrected that and of course now it works alright, and really does wonders for that matter!

Thanks a lot and cheers for the great work!

Ludo
