### ISSUE TITLE
Music style remix doesn't work.

### ISSUE THREAD

**Issue by Milo1421** [intel/openvino-plugins-ai-audacity#107]
After using the music style remix effect I just get really weird static.
You can see the settings I used on the following image:
![Capture](https://github.com/intel/openvino-plugins-ai-audacity/assets/166444450/a292f1e9-4d9b-4fbb-bf70-edffc8950685)

**Comment by RyanMetcalfeInt8** [comment]
Hmm, can you give some details about your hardware setup? You may want to try changing all of the devices on the right-side to ```CPU```, and see if it gives the same. Does it produce static regardless of the input prompt (``what to remix to?```) & input audio track?

**Comment by Milo1421** [comment]
Ok, changing the devices on the right to CPU fixed the problem.
