### ISSUE TITLE
failed to run openvino module

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [intel/openvino-plugins-ai-audacity#108]
![Untitled-1](https://github.com/intel/openvino-plugins-ai-audacity/assets/2649072/902d431a-6d3e-42ba-b594-369e060178ba)
no idea why it fails
windows 11 64bits 4GB RAM core 2 Duo

**Comment by RyanMetcalfeInt8** [comment]
Hi @ROBERT-MCDOWELL,

The most likely reason for this is that your core 2 Duo (probably) doesn't support AVX / AVX2 instruction sets. If you give the exact CPU model number, we'll know for sure. Anyway, we will have a fix for this in the next release, coming soon.

Thanks,
Ryan

**Comment by ROBERT-MCDOWELL** [comment]
Hi @RyanMetcalfeInt8 ,
I was almost sure the issue was coming from my old laptop CPU ;)
here are its info:
	Manufacturer		GenuineIntel
	Name			Intel Mobile Core 2 Duo T9600
	Codename		Penryn
	Specification		Intel(R) Core(TM)2 Duo CPU     T9600  @ 2.80GHz
	Package (platform ID)	Socket P (478) (0x7)
	CPUID			6.7.6
	Extended CPUID		6.17
	Core Stepping		C0
	Technology		45 nm
	Core Speed		2793.0 MHz
	Multiplier x Bus Speed	10.5 x 266.0 MHz
	Base frequency (cores)	266.0 MHz
	Base frequency (mem.)	266.0 MHz
	Rated Bus speed		1064.0 MHz
	Stock frequency		2800 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, EM64T, VT-x
	Microcode Revision	0x610
	L1 Data cache		2 x 32 KB (8-way, 64-byte line)
	L1 Instruction cache	2 x 32 KB (8-way, 64-byte line)
	L2 cache		6 MB (24-way, 64-byte line)
	Max CPUID level		0000000Ah
	Max CPUID ext. level	80000008h
	FID/VID Control		yes
	FID range		6.0x - 10.5x
	Max VID			1.175 V

**Comment by RyanMetcalfeInt8** [comment]
Hi @ROBERT-MCDOWELL,

Aha! Yeah, looks like it supports only up to SSE4.1... we'll have to see how it does with the upcoming release.... it's possible that it will require at least SSE4.2 support to run these AI plugins.

Best Regards,
Ryan

**Comment by ROBERT-MCDOWELL** [comment]
Damn :(, I love my old laptop  (HP8730W) :o)

**Comment by GKrcal** [comment]
Hi Ryan,

I've the same issue: "**Unable to load the Unable to load the "mod-openvino" module**"
Do you have any idea?


OS: MS Windows 10
CPU: Intel® Pentium® Processor G2020 (3M Cache- 2.90 GHz)

_Essentials_
Product Collection,Intel® Pentium® Processor G Series
Code Name,Products formerly Ivy Bridge
Vertical Segment,Desktop
Processor Number,G2020
Lithography,22 nm

_CPU Specifications_
Total Cores,2
Total Threads,2
Processor Base Frequency,2.90 GHz
Cache,3 MB Intel® Smart Cache
Bus Speed,5 GT/s
TDP,55 W

_Supplemental Information_
Marketing Status,Discontinued
Launch Date,Q1'13
Servicing Status,End of Servicing Lifetime
End of Servicing Updates Date,Tuesday |  December 31 |  2019
Embedded Options Available,No
Datasheet,View now

_Memory Specifications_
Max Memory Size (dependent on memory type),32 GB
Memory Types,DDR3 1333
Max # of Memory Channels,2
Max Memory Bandwidth,21 GB/s
ECC Memory Supported   ‡,Yes

_GPU Specifications_
GPU Name‡,Intel® HD Graphics for 3rd Generation Intel® Processors
Graphics Base Frequency,650 MHz
Graphics Max Dynamic Frequency,1.05 GHz
Intel® Quick Sync Video,No
Intel® InTru™ 3D Technology,No
Intel® Clear Video HD Technology,
No of Displays Supported ‡,3

_Expansion Options_
PCI Express Revision,2.0
PCI Express Configurations ‡,up to 1x16 |  2x8 |  1x8 & 2x4

_Package Specifications_
Sockets Supported,FCLGA1155
Max CPU Configuration,1
Thermal Solution Specification,2011C
Package Size,37.5mm x 37.5mm

_Advanced Technologies_
Intel® Optane™ Memory Supported ‡,No
Intel® Turbo Boost Technology ‡,No
Intel® Hyper-Threading Technology ‡,No
Intel® 64 ‡,Yes
Instruction Set,64-bit
Instruction Set Extensions,Intel® SSE4.1 |  Intel® SSE4.2
Intel® My WiFi Technology,No
Idle States,Yes
Enhanced Intel SpeedStep® Technology,Yes
Thermal Monitoring Technologies,Yes

_Security & Reliability_
Intel® AES New Instructions,No
Secure Key,No
Intel® Trusted Execution Technology ‡,No
Execute Disable Bit ‡,Yes
Anti-Theft Technology,No
Intel® Virtualization Technology (VT-x) ‡,Yes
Intel® Virtualization Technology for Directed I/O (VT-d) ‡,No
Intel® VT-x with Extended Page Tables (EPT) ‡,Yes

CPU specification from: https://www.intel.com/content/www/us/en/products/sku/71070/intel-pentium-processor-g2020-3m-cache-2-90-ghz/specifications.html

**Comment by RyanMetcalfeInt8** [comment]
> Damn :(, I love my old laptop (HP8730W) :o). many artists have old machines for various reasons, make it work on core 2 duo will be fantastic....

Yeah that's a nice machine :) -- I'll cross my fingers and hopes that the updated release works for you!

**Comment by RyanMetcalfeInt8** [comment]
> Hi Ryan,
> 
> I've the same issue: "**Unable to load the "mod-openvino" module**" Do you have any idea?
> 
> OS: MS Windows 10 CPU: Intel® Pentium® Processor G2020 (3M Cache- 2.90 GHz)
> 
> _Essentials_ Product Collection,Intel® Pentium® Processor G Series Code Name,Products formerly Ivy Bridge Vertical Segment,Desktop Processor Number,G2020 Lithography,22 nm
> 
> _CPU Specifications_ Total Cores,2 Total Threads,2 Processor Base Frequency,2.90 GHz Cache,3 MB Intel® Smart Cache Bus Speed,5 GT/s TDP,55 W
> 
> _Supplemental Information_ Marketing Status,Discontinued Launch Date,Q1'13 Servicing Status,End of Servicing Lifetime End of Servicing Updates Date,Tuesday | December 31 | 2019 Embedded Options Available,No Datasheet,View now
> 
> _Memory Specifications_ Max Memory Size (dependent on memory type),32 GB Memory Types,DDR3 1333 Max # of Memory Channels,2 Max Memory Bandwidth,21 GB/s ECC Memory Supported ‡,Yes
> 
> _GPU Specifications_ GPU Name‡,Intel® HD Graphics for 3rd Generation Intel® Processors Graphics Base Frequency,650 MHz Graphics Max Dynamic Frequency,1.05 GHz Intel® Quick Sync Video,No Intel® InTru™ 3D Technology,No Intel® Clear Video HD Technology, No of Displays Supported ‡,3
> 
> _Expansion Options_ PCI Express Revision,2.0 PCI Express Configurations ‡,up to 1x16 | 2x8 | 1x8 & 2x4
> 
> _Package Specifications_ Sockets Supported,FCLGA1155 Max CPU Configuration,1 Thermal Solution Specification,2011C Package Size,37.5mm x 37.5mm
> 
> _Advanced Technologies_ Intel® Optane™ Memory Supported ‡,No Intel® Turbo Boost Technology ‡,No Intel® Hyper-Threading Technology ‡,No Intel® 64 ‡,Yes Instruction Set,64-bit Instruction Set Extensions,Intel® SSE4.1 | Intel® SSE4.2 Intel® My WiFi Technology,No Idle States,Yes Enhanced Intel SpeedStep® Technology,Yes Thermal Monitoring Technologies,Yes
> 
> _Security & Reliability_ Intel® AES New Instructions,No Secure Key,No Intel® Trusted Execution Technology ‡,No Execute Disable Bit ‡,Yes Anti-Theft Technology,No Intel® Virtualization Technology (VT-x) ‡,Yes Intel® Virtualization Technology for Directed I/O (VT-d) ‡,No Intel® VT-x with Extended Page Tables (EPT) ‡,Yes
> 
> CPU specification from: https://www.intel.com/content/www/us/en/products/sku/71070/intel-pentium-processor-g2020-3m-cache-2-90-ghz/specifications.html

Hi @GKrcal,

Looks like you're kind of in the same boat -- your CPU only supports up to SSE4.2, so the 'R1' release will have this issue. But, since your CPU supports SSE4.2, I'm more confident that the upcoming release will work in your case.

Thanks,
Ryan

**Comment by ROBERT-MCDOWELL** [comment]
@RyanMetcalfeInt8 thx much appreciated! I didn't know audacity is now part of Intel project... first time I used it was in 2007 ;)

**Comment by GKrcal** [comment]
> > Hi Ryan,
> > I've the same issue: "**Unable to load the "mod-openvino" module**" Do you have any idea?
> > OS: MS Windows 10 CPU: Intel® Pentium® Processor G2020 (3M Cache- 2.90 GHz)
> > _Essentials_ Product Collection,Intel® Pentium® Processor G Series Code Name,Products formerly Ivy Bridge Vertical Segment,Desktop Processor Number,G2020 Lithography,22 nm
> > _CPU Specifications_ Total Cores,2 Total Threads,2 Processor Base Frequency,2.90 GHz Cache,3 MB Intel® Smart Cache Bus Speed,5 GT/s TDP,55 W
> > _Supplemental Information_ Marketing Status,Discontinued Launch Date,Q1'13 Servicing Status,End of Servicing Lifetime End of Servicing Updates Date,Tuesday | December 31 | 2019 Embedded Options Available,No Datasheet,View now
> > _Memory Specifications_ Max Memory Size (dependent on memory type),32 GB Memory Types,DDR3 1333 Max # of Memory Channels,2 Max Memory Bandwidth,21 GB/s ECC Memory Supported ‡,Yes
> > _GPU Specifications_ GPU Name‡,Intel® HD Graphics for 3rd Generation Intel® Processors Graphics Base Frequency,650 MHz Graphics Max Dynamic Frequency,1.05 GHz Intel® Quick Sync Video,No Intel® InTru™ 3D Technology,No Intel® Clear Video HD Technology, No of Displays Supported ‡,3
> > _Expansion Options_ PCI Express Revision,2.0 PCI Express Configurations ‡,up to 1x16 | 2x8 | 1x8 & 2x4
> > _Package Specifications_ Sockets Supported,FCLGA1155 Max CPU Configuration,1 Thermal Solution Specification,2011C Package Size,37.5mm x 37.5mm
> > _Advanced Technologies_ Intel® Optane™ Memory Supported ‡,No Intel® Turbo Boost Technology ‡,No Intel® Hyper-Threading Technology ‡,No Intel® 64 ‡,Yes Instruction Set,64-bit Instruction Set Extensions,Intel® SSE4.1 | Intel® SSE4.2 Intel® My WiFi Technology,No Idle States,Yes Enhanced Intel SpeedStep® Technology,Yes Thermal Monitoring Technologies,Yes
> > _Security & Reliability_ Intel® AES New Instructions,No Secure Key,No Intel® Trusted Execution Technology ‡,No Execute Disable Bit ‡,Yes Anti-Theft Technology,No Intel® Virtualization Technology (VT-x) ‡,Yes Intel® Virtualization Technology for Directed I/O (VT-d) ‡,No Intel® VT-x with Extended Page Tables (EPT) ‡,Yes
> > CPU specification from: https://www.intel.com/content/www/us/en/products/sku/71070/intel-pentium-processor-g2020-3m-cache-2-90-ghz/specifications.html
> 
> Hi @GKrcal,
> 
> Looks like you're kind of in the same boat -- your CPU only supports up to SSE4.2, so the 'R1' release will have this issue. But, since your CPU supports SSE4.2, I'm more confident that the upcoming release will work in your case.
> 
> Thanks, Ryan

Thanks for your reply. I'm looking forward for the upcoming release.

**Comment by RyanMetcalfeInt8** [comment]
> @RyanMetcalfeInt8 thx much appreciated!

No problem! 

>  I didn't know audacity is now part of Intel project...

I don't know if I would phrase it like that :) -- it's more the other way around I think. Our team here at Intel loves AI, music, and open source software, and Audacity -- so we decided to develop these plugins.

**Comment by ROBERT-MCDOWELL** [comment]
@RyanMetcalfeInt8  Ha ok, I misinterpreted ;)

**Comment by RyanMetcalfeInt8** [comment]
Hi @MarkR-A,

This is more about the whisper.dll being compiled with AVX / AVX2 specific instructions for distribution with R1 release. Even if one wanted to use *only* GPU as an inference accelerator (in the sense that we expose different 'devices'), there will always be 'glue logic' (the stuff that coordinates everything) running on the CPU.. and hence you'd be left with the same issue.

The workaround for this is to simply compile whisper.dll *without* AVX / AVX2 instructions, and then conditionally install them when we detect that the system doesn't support these instructions. This is what our installer will do for the upcoming 'R2' release.

**Comment by Blueskylegion** [comment]
> ![Untitled-1](https://private-user-images.githubusercontent.com/2649072/321019900-902d431a-6d3e-42ba-b594-369e060178ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDMxNDUsIm5iZiI6MTcxMzU0Mjg0NSwicGF0aCI6Ii8yNjQ5MDcyLzMyMTAxOTkwMC05MDJkNDMxYS02ZDNlLTQyYmEtYjU5NC0zNjllMDYwMTc4YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTYwNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2EyMDM2MzEwZWY1YzBlN2I5YzlkYzM0YjEwYzE0ZjY1Nzg5OWZkNDk5NmYyNWE5OGY2OTQzOGI2MGE2YWQ4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xXYvjpYFAGGmdGKnC29ccjrXPcr286070Rp6SL1mICE) no idea why it fails windows 11 64bits 4GB RAM core 2 Duo

I also had the same problem, looking forward to the new release.

**Comment by Blueskylegion** [comment]
I also had the same problem, looking forward to the new release.

**Comment by RyanMetcalfeInt8** [comment]
Hi @ROBERT-MCDOWELL, @MarkR-A, @Blueskylegion, 

The new release is available here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

I'll close this one for now. If you have issues, feel free to open a new issue. Cheers!
