### ISSUE TITLE
Whisper Transcription Export As text

### ISSUE THREAD

**Issue by hdrmadness** [intel/openvino-plugins-ai-audacity#11]
Hello,

Fantastic addition and implementation. I would have one feature request and that would be to be able to export the transcription as a text file.

Thank you

**Comment by LWinterberg** [comment]
You can do that via File -> Export Other -> Export Labels

**Comment by RyanMetcalfeInt8** [comment]
Thank you @LWinterberg.  

@hdrmadness, I'll close this for now -- but feel free to re-open if it doesn't achieve what you were looking for.
