### ISSUE TITLE
Unable to load the "mod-openvino" module.

### ISSUE THREAD

**Issue by BohdanBohdan** [intel/openvino-plugins-ai-audacity#111]
Hi, any ideas why that might be?
![unnamed](https://github.com/intel/openvino-plugins-ai-audacity/assets/82262356/0211cfe3-28a2-458c-8974-26e9148dc6c1)

**Comment by RyanMetcalfeInt8** [comment]
Hi @BohdanBohdan,

Could you share details of the CPU you're using?

Thanks,
Ryan

**Comment by BohdanBohdan** [comment]
Thanks for the fast reply! My CPU is this one
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/82262356/1bee7586-0614-49b5-862c-61887c351438)

**Comment by RyanMetcalfeInt8** [comment]
Thanks -- so the issue with the 'R1' release is that it requires AVX / AVX2 instruction support. The CPU that you listed only supports up to SSE4.2. Note that our upcoming release (coming soon!) should resolve this issue.

Thanks,
Ryan

**Comment by BohdanBohdan** [comment]
Aha, I see now, oh well. Thank you for your support anyway!
