### ISSUE TITLE
Openvino fails when used with account with non-ascii username

### ISSUE THREAD

**Issue by The3IC** [intel/openvino-plugins-ai-audacity#114]
Testing out the OpenVino plugins and all operations fail. For the transcribe (see log), no obvious problem but for the Noise suppression at least the problem is that the plugin tries to create a file in a non-existent directory due to character set problem, see last line in log:

**Couldn't create directory [C:\Users\HÃ¥kan\AppData\Roaming\audacity], err=Permission denied)**

There is no user HÃ¥kan on the system, instead the user account is "Håkan". This normally happens when a 16 bit unicode is interpreted as 2 x 8 bit (Latin 1?) character set.

I'm wondering if the same issue also blocks the transcription, this would give a hint in that direction: "context creation / initialization failed"

Installation went OK and I can see and start all the OpenVino activities but so far they all fail.

Log output:

11:37:05: Operation 'Importing WAV (Microsoft)' took 3.331000 seconds. Poll was called 461 times and took 0.046272 seconds. Yield was called 48 times and took 0.009145 seconds.
11:38:12: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:38:16: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed
11:38:22: Operation 'OpenVINO Whisper Transcription' took 3.715000 seconds. Poll was called 3756 times and took 0.122008 seconds. Yield was called 54 times and took 0.066083 seconds.
11:38:16: Error: whisper_ctx_init_openvino_encoder failed for device = GPU
11:39:30: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:39:34: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed
11:39:37: Operation 'OpenVINO Whisper Transcription' took 3.655000 seconds. Poll was called 3756 times and took 0.118056 seconds. Yield was called 53 times and took 0.064327 seconds.
11:39:34: Error: whisper_ctx_init_openvino_encoder failed for device = CPU
11:50:58: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:51:06: Operation 'OpenVINO Noise Suppression' took 7.666000 seconds. Poll was called 16 times and took 0.047271 seconds. Yield was called 15 times and took 0.036299 seconds.
11:50:59: Error: In Noise Suppression Compilation, exception: Exception from src\inference\src\core.cpp:237:
Couldn't create directory [C:\Users\HÃ¥kan\AppData\Roaming\audacity], err=Permission denied)

System
Windows 10 latest updates
CPU: Ryzen 5600x (which has the AVX / AVX2)
GPU: AMD XT 6800

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC,

Thanks, yes this is a known issue with the 'R1' release. We have another release dropping soon that should resolve this. Thank you for taking the time to report it though!

Thanks,
Ryan

**Comment by bluemoehre** [comment]
Duplicates https://github.com/intel/openvino-plugins-ai-audacity/issues/91

Looking forward to the new release =)

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC, @bluemoehre, we've posted the new release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Could you try it out and let us know if this non-ascii username issue is resolved? Thanks!

**Comment by The3IC** [comment]
@RyanMetcalfeInt8 a couple of more observations:
- Transcript generation fails for both using CPU as well as using GPU (above was with GPU).
- Music generation fails with GPU but "works" with CPU
- CPU generated music (I used my own prompt) was pretty much useless, tested with a 4:30 piece, after the first 30 seconds (which were boring), the "music" essentially was just random noise.. So at least in my view unfortunately pretty useless
- Audacity logs below

Music generation with GPU:
11:28:51: Error: MusicGen pipeline could not be created.
11:28:51: Operation 'OpenVINO Music Generation' took 11.861000 seconds. Poll was called 24 times and took 0.042957 seconds. Yield was called 23 times and took 0.032562 seconds.
11:28:45: Error: In Music Generation V2, exception: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Program build failed(0_part_2): You may enable OCL source dump to see the error log.

Transcript generation with CPU:

11:26:32: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:26:37: Error: In Whisper Transcription Effect, exception: invalid map<K, T> key
11:26:42: Operation 'OpenVINO Whisper Transcription' took 5.693000 seconds. Poll was called 3760 times and took 0.098182 seconds. Yield was called 58 times and took 0.043275 seconds.

CPU is Ryzen 5 5600X (6 core)
GPU is AMD XT 6600, driver is Adrenalin 23.11.1

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC,

Well, sorry about transcription -- I don't know how I missed that. I just tried on a system that I set up specifically for non-ascii usernames, and sure enough I received the same 'Invalid map' error as you.

Glad to see the other features (mostly) functional, at least on CPU. For GPU, that AMD XT 6600 is probably not well-supported by the OpenVINO framework (the runtime that we build on top of) -- and so unfortunately there's not too much I can do to help out there.

For music generation, there is a bit of a learning curve and is a very iterative process. My recommendation would be to try generating no more than 5 to 10 seconds when you're experimenting with prompts and other settings. It's not going to generate something amazing every time -- so you'll end up throwing away quite a bit. Even if it starts off sounding pretty good, it may transition into something awful... but in this case, the process is just trim away the audio that started to go south, and kick off 'audio continuation' from where the 'good' part left off. 

> In the Install section (after all the downloads), the progress bar was pretty much stuck at 100% all the time

Yes, someone else brought this up too and it's a good point. We'll try to address that going forward.

> as for downloading of models, for a non-expert like me, it would be nice to get some help in choosing which model is optimal/best? Like if I download and use large-V3, do any of the other models make sense to donwload, are there any dependencies etc?

Okay, right -- I suppose a large list of models with checkboxes isn't very intuitive for most, especially if we don't give any pros/cons/info about each model. We'll think about how to address this too. 

Thank you!
Ryan

**Comment by The3IC** [comment]
No probs @RyanMetcalfeInt8, just ping me when you have an update to test.

And it would also be good to understand the UI logic of the Translate? Do you first generate something in the spoken language and the translate the transcript or do you translate directly from the audio? And how do you choose the target language for the translation? Couldn't figure this out from the UI.

**Comment by RyanMetcalfeInt8** [comment]
> And it would also be good to understand the UI logic of the Translate? Do you first generate something in the spoken language and the translate the transcript or do you translate directly from the audio? And how do you choose the target language for the translation? Couldn't figure this out from the UI.

So for transcription, we use the whisper.cpp framework which uses a set of AI LLM models to perform transcription / translation. In both cases, it happens in a single step, directly from the spoken audio (as opposed to transcribe first, and then translate happening on the transcription). 

These whisper models are kind of biased toward english when it comes to translation, as the only option is to translate *to* english... which is why you don't see any options for translation to other languages.

**Comment by The3IC** [comment]
Ah, I see. So if I may, a humble suggestion: if the menu iwould say "Translate to english", this would make this obvious?

**Comment by RyanMetcalfeInt8** [comment]
> Ah, I see. So if I may, a humble suggestion: if the menu would say "Translate to english", this would make this obvious?

Yes, good suggestion. This definitely would make it more clear. Thanks!

**Comment by bluemoehre** [comment]
> Hi @The3IC, @bluemoehre, we've posted the new release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
> 
> Could you try it out and let us know if this non-ascii username issue is resolved? Thanks!

To me it works now using 3.5.1-alpha + v3.5.0-R2. 
No error occurred and no weird folder was created in the user's home directory. 
Many thanks!

**Comment by The3IC** [comment]
> > Hi @The3IC, @bluemoehre, we've posted the new release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
> > Could you try it out and let us know if this non-ascii username issue is resolved? Thanks!

I'm unfortunately still seeing the same error for transcript, the others work, music generation "works".

**Comment by RyanMetcalfeInt8** [comment]
Closing this one, as I think technically it was fixed but was replaced with the newer issue (which hopefully is now also fixed 😄 )
