### ISSUE TITLE
Whenever I make a request, I get meaningless noise instead of music. Please help =(

### ISSUE THREAD

**Issue by Hala-ad-Din** [intel/openvino-plugins-ai-audacity#117]
The plugin is installed and enabled, but instead of generating music it only creates strange noise. The settings are standard, I used different prompts, the result is almost the same.

![1](https://github.com/intel/openvino-plugins-ai-audacity/assets/67903964/92fdea25-88c2-4bcd-ab22-23d7147e597c)
![2](https://github.com/intel/openvino-plugins-ai-audacity/assets/67903964/ff472574-22c2-4005-9506-544ad0ac7553)

Log:
8:14: Audacity 3.4.2
13:28:14: Error: Failed to load shared library 'avformat-60.dll' (error 126: Не найден указанный модуль.)
13:28:14: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
13:28:16: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
13:28:16: Error: Failed to load shared library 'avformat-60.dll' (error 126: Не найден указанный модуль.)
13:28:16: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
13:29:16: Operation 'OpenVINO Music Generation' took 42.201000 seconds. Poll was called 84 times and took 0.066182 seconds. Yield was called 84 times and took 0.039684 seconds.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Hala-ad-Din,

Can you try changing all of the devices on the right side to 'CPU'? Also, just as a heads up, we are swapping this version of Music Generation with an entirely new implementation next week within our updated release. 

Thanks,
Ryan

**Comment by Hala-ad-Din** [comment]
> Hi @Hala-ad-Din,
> 
> Can you try changing all of the devices on the right side to 'CPU'? Also, just as a heads up, we are swapping this version of Music Generation with an entirely new implementation next week within our updated release.
> 
> Thanks, Ryan

Yes, I tried it. The result turned out different, but it’s still not music, unfortunately I can’t attach the mp3
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/67903964/97f8c2bd-4cab-4f63-9ab7-7497c4ce5762)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/67903964/735103ea-3916-4580-aa32-4a3b1c4325c4)

**Comment by Hala-ad-Din** [comment]
> Hi @Hala-ad-Din,
> 
> Can you try changing all of the devices on the right side to 'CPU'? Also, just as a heads up, we are swapping this version of Music Generation with an entirely new implementation next week within our updated release.
> 
> Thanks, Ryan

I tried replacing everything with the GPU and SUDDENLY it worked and produced a pretty decent piano track.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/67903964/1c3bde48-773a-4536-98e2-4ef4436bdec1)

**Comment by Hala-ad-Din** [comment]
Now I'm worried that something is wrong with my processor =(

**Comment by RyanMetcalfeInt8** [comment]
Hi @Hala-ad-Din,

Hmm, glad it seems to be producing *something* reasonable, at least on your GPU. I highly doubt anything is wrong with your processor -- you'd definitely have a lot more things going wrong :)

What CPU / processor are you using?

Thanks,
Ryan

**Comment by Hala-ad-Din** [comment]
Hi, @RyanMetcalfeInt8! 
I use Intel Core i7-13700KF and Geforce RTX 4080. 
I carried out a lot of tests after the build and have been using it for more than six months, so indeed, probably if I had problems with the CPU, they would have made themselves felt earlier =)

**Comment by RyanMetcalfeInt8** [comment]
> I carried out a lot of tests after the build and have been using it for more than six months, so indeed, probably if I had problems with the CPU, they would have made themselves felt earlier =)

I agree. Hmm, strange.. that CPU should be very well supported. Well, like I said earlier, we are releasing a new version of Music Generation which is powered by MusicGen LLM (instead of Riffusion) -- and in my opinion, produces much higher quality audio snippets. I'll add a comment here with the updated release is available, and maybe you can try it out.. hopefully you won't have the same issue with the new version.

Thanks!
Ryan

**Comment by Hala-ad-Din** [comment]
@RyanMetcalfeInt8, thanks!
I'll be happy to test the new version! By the way, another question, does it also make sense to switch the remaining modules to the GPU? I tried them with standard settings, everything seems to work, including whisper transcription and music separation and noise reduction, but I haven’t studied it thoroughly yet. Stuck on scary music generation =)

**Comment by RyanMetcalfeInt8** [comment]
>  By the way, another question, does it also make sense to switch the remaining modules to the GPU? 

Not necessarily... my guess is that whatever might be going wrong is specific to Music Generation. The other effects should work just fine on CPU.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Hala-ad-Din,

New release is here! https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

I'll close this one as completed, but feel free to keep commenting if you have any questions. Cheers!

**Comment by Hala-ad-Din** [comment]
@RyanMetcalfeInt8 , thanks!
Installing! By the way, should the previous version be somehow removed or will it be replaced?

**Comment by Hala-ad-Din** [comment]
@RyanMetcalfeInt8
Well, with the usual settings, music generation works right away! But! There are a couple of observations.
1. If I first generated the music entirely on the CPU, and then added the GPU in the settings of the second generation, an error occurs. I am attaching the error log. [log.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/15073296/log.txt)
2. If during the FIRST generation in a session you turn on the GPU somewhere in the settings, audacity crashes. I am attaching the crash report. [CrashReport.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/15073294/CrashReport.txt)
