### ISSUE TITLE
Access denied- Error 5

### ISSUE THREAD

**Issue by pravin-vaz** [intel/openvino-plugins-ai-audacity#12]
Hi team, thanks for this plugin. 
I have installed the plugin on my Windows 10 machine (64bit, i5,16gb RAM, GPU 1660). When I run it, I get an error-- Access denied (error 5). I have attached a screenshot of it below. 
![Access Denied](https://github.com/intel/openvino-plugins-ai-audacity/assets/4796418/715f1ff8-f1fa-42b1-99f6-0461502b9da7)

Is that because Audacity does not have access to modify files in the Program files directory ?

Warm regards

**Comment by RyanMetcalfeInt8** [comment]
Hi @pravin-vaz,

Can you double check that C:\Program Files\Audacity\openvino-models directory already exists before running Audacity? This folder should be copied there during the installation, so double check the steps (and video).

Thanks,
Ryan
