### ISSUE TITLE
Audacity 3.5 support

### ISSUE THREAD

**Issue by cjmaxik** [intel/openvino-plugins-ai-audacity#120]
Audacity 3.5 stable just dropped, would be nice to have support for it.

https://github.com/intel/openvino-plugins-ai-audacity/issues/16

**Comment by RyanMetcalfeInt8** [comment]
Hi @cjmaxik,

Yes, we're on it 😄 

Stay tuned, we're in the process of generating and testing our release build against the 3.5.0 tag. 

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
We've posted the updated release!

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
