### ISSUE TITLE
Cannot load module "mod-openvino" - Error: The specified procedure was not found

### ISSUE THREAD

**Issue by Komodor93** [intel/openvino-plugins-ai-audacity#122]
Double-checked copying. 

- Windows 11 Pro 64-bit
- Intel Core i7 8750H @ 2.20GHz
- Audacity 3.5.0
- Intel UHD Graphics 630 (Dell)
- 4095MB NVIDIA GeForce GTX 1050 Ti with Max-Q Design

Can you help me, please?

**Comment by RyanMetcalfeInt8** [comment]
Hi @Komodor93,

We're working on getting an updated release out that will be compatible with Audacity 3.5.0. The issue you're hitting is that the 3.4.2-R1 release of our plugins are only compatible with 3.4.2 version of Audacity.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @Komodor93, the updated release is now available here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2 

Enjoy!
