### ISSUE TITLE
V3.5.0-R2    Issues with GPU

### ISSUE THREAD

**Issue by ShamanTcler** [intel/openvino-plugins-ai-audacity#130]
First... the installer worked great ... using CPU I was able to generate word "nuggets" 😁

Switching to GPU....

![GPU](https://github.com/intel/openvino-plugins-ai-audacity/assets/30176093/eca7edda-ec5a-4891-8133-50e5bbc604d6)

So it did find the GPU.

It then fails and this is the log:

![GPU Log](https://github.com/intel/openvino-plugins-ai-audacity/assets/30176093/b29cfd8b-3e2b-4d35-a61c-6b1a129c2361)

**Comment by ShamanTcler** [comment]
I should add:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22635 Build 22635
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	6.95 GB
Total Virtual Memory	36.9 GB
Available Virtual Memory	10.9 GB

**Comment by RyanMetcalfeInt8** [comment]
Hi again @ShamanTcler,

NVidia GPUs are not very well supported by OpenVINO at this point, which is most likely the root of these GPU issues. 

Your i7-10700K should have an integrated GPU (that I am guessing you have disabled) which should work quite well with OpenVINO / these effects. 

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC,

Thanks for the suggestion, I'll try to more clearly spell out what hardware is 'officially' supported on the release page. Basically, our plugins support whatever hardware the OpenVINO framework supports, which is listed here: https://docs.openvino.ai/2024/about-openvino/system-requirements.html

Thanks,
Ryan

**Comment by The3IC** [comment]
Ah, yes, that is clear. Just perhaps add that link with the heading "Supported hardware" also to the audacity plugin. Again for us who come into this mainly/only via audacity, do not really know about the genealogy.

**Comment by RyanMetcalfeInt8** [comment]
Hey @The3IC, thanks again for the suggestion -- I've added this 'Supported Hardware' section to our releases. I'll close this issue then -- Cheers!
