### ISSUE TITLE
Enhancement request:  after translation clean up text position

### ISSUE THREAD

**Issue by ShamanTcler** [intel/openvino-plugins-ai-audacity#131]
You have done great work .... but there are always thing to do better.

This is a sample run:
![Aud](https://github.com/intel/openvino-plugins-ai-audacity/assets/30176093/65dc4278-7e52-4843-be71-9d5aa44e4a9d)

There is a bit of silence before the first word "Welcome" which seems to really throw the alignment off. 

Playing with it I did find I could move things around using the "()" markers.  Are these markers documented somewhere?

**Comment by RyanMetcalfeInt8** [comment]
Hi @ShamanTcler,

Thanks for the feedback!

Just to double check -- is this with 'Max segment length' set to 1? I see you have individual words there. 

I have observed this timestamp misalignment issue as well, when there is a long duration of no speaking at the beginning of the track. I'm not sure if there's too much we'll be able to do about it, but we can poke around whisper.cpp discussions to see if anyone has a good solution for that.

If you were to, say, start your selection at ~1.15 second mark, do you get more accurate transcriptions?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
> Playing with it I did find I could move things around using the "()" markers. Are these markers documented somewhere?

Perhaps -- @petersampsonaudacity, is there Audacity documentation about manipulation of label markers from the GUI someplace? Thanks!
