### ISSUE TITLE
Installed in Program Files/Audacity but does not show up in Audacity

### ISSUE THREAD

**Issue by ProjectK-92** [intel/openvino-plugins-ai-audacity#132]
I have the latest version of Audacity as of 4/23/24, installed plug-ins, but they do not show up in Audacity. Rescanned plug-ins with no luck. Please specify or link exact instructions for proper installation and how to get them to show up in Audacity. Thank you for your time.

**Comment by RyanMetcalfeInt8** [comment]
Hi @ProjectK-92,

After installation, you need to go to Edit -> Preferences, select Modules, change mod-openvino from to Enabled, and press OK. Once you do that, you'll need to close and re-open Audacity. Let me know if that works for you.

Thanks!
Ryan

**Comment by achimschnick** [comment]
I have no Idea about Scripting an such Things at all.  But it would be nice, if someone could tell us, where and how to place all that files and folders and what  has to be done. Just upgraded to 3.5.0
I am not that familiar with Soundsoftware at all, but Audacity is really cool - and for free. indeed. Love you Guys for that.

**Comment by RyanMetcalfeInt8** [comment]
Hi @achimschnick,

You should be able to run our installer, and it will put everything in the right place for you. Let me know if I can help explain anything further.

Thanks!
Ryan

**Comment by ProjectK-92** [comment]
@RyanMetcalfeInt8 That did help! Can't believe I forgot that step. Thanks!

**Comment by achimschnick** [comment]
@RyanMetcalfeInt8 

Hu, must have overlooked it. Thanks a Lot. Will see what happend tomorrow. Too late now here to try all that out 04:49 h german time. Hope it works fine. You get a Review soon.
 

> Hi @achimschnick,
> 
> You should be able to run our installer, and it will put everything in the right place for you. Let me know if I can help explain anything further.
> 
> Thanks! Ryan

**Comment by achimschnick** [comment]
@RyanMetcalfeInt8 
That is so megacool. Was some kind of not working. But than I found to enable Preference -> Modules-> openVINO from (no choice made) to enable. 
Works perfect! I am really happy with it!
Thanks a Lot!!!!

> @RyanMetcalfeInt8
> 
> Hu, must have overlooked it. Thanks a Lot. Will see what happend tomorrow. Too late now here to try all that out 04:49 h german time. Hope it works fine. You get a Review soon.
> 
> > Hi @achimschnick,
> > You should be able to run our installer, and it will put everything in the right place for you. Let me know if I can help explain anything further.
> > Thanks! Ryan

Needed to Change

**Comment by achimschnick** [comment]
Holy, what are you doing. Just updated Audacity to 3.5.1 and openvino does not work anymor.
What can I do?
Rgds
Achim
________________________________
Von: Ryan Metcalfe ***@***.***>
Gesendet: Mittwoch, 24. April 2024 02:18
An: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: achimschnick ***@***.***>; Mention ***@***.***>
Betreff: Re: [intel/openvino-plugins-ai-audacity] Installed in Program Files/Audacity but does not show up in Audacity (Issue #132)


Hi @achimschnick<https://github.com/achimschnick>,

You should be able to run our installer, and it will put everything in the right place for you. Let me know if I can help explain anything further.

Thanks!
Ryan

**Comment by RyanMetcalfeInt8** [comment]
@achimschnick, did you install corresponding 3.5.1-R1 version of these plugins as well? https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2

**Comment by RyanMetcalfeInt8** [comment]
No problem!
