### ISSUE TITLE
Generation and Seperation Fail

### ISSUE THREAD

**Issue by user2w-js** [intel/openvino-plugins-ai-audacity#133]
Running generation and running separation both fail. I have removed Openvino and I have reinstalled Audacity, but no avail.

21:49:44: Audacity 3.5.0
21:49:44: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
21:49:44: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
21:49:50: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
21:49:50: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
21:50:18: Operation 'OpenVINO Music Generation' took 9.603000 seconds. Poll was called 20 times and took 0.090544 seconds. Yield was called 19 times and took 0.071898 seconds.
21:50:12: Error: In Music Generation V2, exception: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for result:new_key_value_23_0/sink_port_0 node (type=reorder)
[GPU] Original name: new_key_value_23_0/sink_port_0
[GPU] Original type: Result
[GPU] Reason: Check '!kernels.empty()' failed at src\plugins\intel_gpu\src\kernel_selector\kernel_selector.cpp:70:
[GPU] Couldn't find a suitable kernel for result:new_key_value_23_0/sink_port_0 params raw string: F32_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v2_p0_0;F16_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v2_p0_0

**Comment by cjmaxik** [comment]
Similar error with Music Separation:
```
12:06:22: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
12:06:24: Error: In Music Separation, exception: Exception from src\inference\src\cpp\core.cpp:126:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for convert:Multiply_56822 node (type=reorder)
[GPU] Original name: Multiply_56822
[GPU] Original type: Convert
[GPU] Reason: Check '!kernels.empty()' failed at src\plugins\intel_gpu\src\kernel_selector\kernel_selector.cpp:70:
[GPU] Couldn't find a suitable kernel for convert:Multiply_56822 params raw string: F16_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0;F32_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0
12:06:27: Operation 'OpenVINO Music Separation' took 2.152000 seconds. Poll was called 6 times and took 0.054386 seconds. Yield was called 4 times and took 0.041739 seconds.
```

**Comment by cjmaxik** [comment]
Seems to be related: https://github.com/intel/openvino-plugins-ai-audacity/issues/130#issuecomment-2073652193

**Comment by RyanMetcalfeInt8** [comment]
Hi @cjmaxik, @user2w-js, what kind GPU are you using?

**Comment by cjmaxik** [comment]
Understood, thank you. I think, a brief note in "Known Issues & Limitations" of the release page will be good in this situation.

**Comment by user2w-js** [comment]
GPU = NVIDIA GeForce RTX 3060 (dGPU) @RyanMetcalfeInt8

**Comment by cjee21** [comment]
Music Separation only works on CPU here as well and this is with an Intel GPU. Same error with previous versions. No issues with Music Gen or Whisper on GPU though.

![Screenshot](https://github.com/intel/openvino-plugins-ai-audacity/assets/77721854/7cc9de92-22f9-4751-bb3b-33a00a9b0e9e)
```
01:33:10: Operation 'Importing FLAC (Free Lossless Audio Codec)' took 0.692000 seconds. Poll was called 87 times and took 0.004432 seconds. Yield was called 6 times and took 0.000664 seconds.
01:33:10: Operation 'Music Information Retrieval' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
01:33:29: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
01:33:32: Error: In Music Separation, exception: Exception from src\inference\src\cpp\core.cpp:126:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Check '_kernels.end() != res' failed at src\plugins\intel_gpu\src\runtime\kernels_cache.cpp:360:
Kernel for {mvn:MVN_1887} is not found in the kernel cache!

01:33:58: Operation 'OpenVINO Music Separation' took 2.790000 seconds. Poll was called 7 times and took 0.056668 seconds. Yield was called 6 times and took 0.050615 seconds.
```

Audacity: 3.5.1 64-bit
OpenVINO Plugin: v3.5.1-R2
GPU: Intel Arc A380 (31.0.101.5445)
CPU: AMD Zen 4

**Comment by RyanMetcalfeInt8** [comment]
Hi @cjee21,

Sorry for delayed response. Strange that you're getting an error using that Arc A380, especially with very recent drivers. Let me see if I can reproduce on an A770.


Thanks,
Ryan

**Comment by vecuccio** [comment]
I have the same problem - except it fails with GPU (immediately) and CPU after the progress bar completes.
RTX2080TI and Intel i7-10700K


21:14:18: Audacity 3.6.1
Log Cleared.
21:14:36: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
21:14:38: Error: In Music Separation, exception: Exception from src/inference/src/cpp/core.cpp:124:
Exception from src/inference/src/dev/plugin.cpp:54:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program_builder.cpp:185:
[GPU] ProgramBuilder build failed!
Exception from src/plugins/intel_gpu/src/graph/include\primitive_type_base.h:58:
[GPU] Can't choose implementation for convert:crosstransformer.layers_t.3.cross_attn.out_proj.weight node (type=reorder)
[GPU] Original name: crosstransformer.layers_t.3.cross_attn.out_proj.weight
[GPU] Original type: Convert
[GPU] Reason: Check '!kernels.empty()' failed at src/plugins/intel_gpu/src/kernel_selector/kernel_selector.cpp:70:
[GPU] Could not find a suitable kernel for convert:crosstransformer.layers_t.3.cross_attn.out_proj.weight params raw string: F16_BFYX_v1_p0_0_v1_p0_0_v512_p0_0_v512_p0_0;F32_BFYX_v1_p0_0_v1_p0_0_v512_p0_0_v512_p0_0





21:14:40: Operation 'OpenVINO Music Separation' took 1.993000 seconds. Poll was called 5 times and took 0.013633 seconds. Yield was called 4 times and took 0.007357 seconds.
21:14:47: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
21:14:59: Error: In Music Separation, exception: unexpected case encountered where curT0 (0.000000) <= curT1(0.000000)
21:15:02: Operation 'OpenVINO Music Separation' took 12.105000 seconds. Poll was called 21 times and took 0.020578 seconds. Yield was called 13 times and took 0.007988 seconds.

**Comment by RyanMetcalfeInt8** [comment]
Hi @vecuccio,

The RTX2080TI is not a supported GPU, unfortunately. You said it also fails for CPU though?

Thanks,
Ryan

**Comment by vecuccio** [comment]
Audacity doesn't support a 2080ti? What DOES it support???

Yeah, it also didn't work on the i7-10700k.

**Comment by RyanMetcalfeInt8** [comment]
> What DOES it support???

https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html

> Yeah, it also didn't work on the i7-10700k.

Happy to take a look if you share more details.
