### ISSUE TITLE
Error message The specified action cannot be found

### ISSUE THREAD

**Issue by anasalmunajjid** [intel/openvino-plugins-ai-audacity#134]
The necessary steps have been taken, but when I open the program, this message appears. What is the solution? Thanks
![photo_2024-04-24_12-05-06](https://github.com/intel/openvino-plugins-ai-audacity/assets/129178000/4ed23632-99d2-4ab9-b520-ede8f708ffc1)

**Comment by Helmut002** [comment]
I have the same problem. I got two machines - one with win11 and there openvino in running fine. And one with win10 and there I get the same message. Competely uninstall audiacity and openvino, deleting the appdata-folders hasn't changed anything.

**Comment by RyanMetcalfeInt8** [comment]
Hi @anasalmunajjid, @Helmut002,

Are you using Audacity **3.5.0** 64-bit, and the latest version of these plugins (https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2)?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi, there has been a patch release since this issue was posted: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1

I'll close this one for now.. please submit a new issue if you are still having trouble. Thanks!
