### ISSUE TITLE
mod-openvino process library not linked again.

### ISSUE THREAD

**Issue by SplendidPiePizza** [intel/openvino-plugins-ai-audacity#136]
ryan. since you released a new one 2 days ago. i still have a same error. the dependencies show's that half of it is error. half of it is ok.
i will send screenshot later.
if you can remember my pc specs
my cpu is amd it support sse both, but i still se 2 errors.
what causes this?

**Comment by RyanMetcalfeInt8** [comment]
Hi @SplendidPiePizza, what errors do you see?

**Comment by SplendidPiePizza** [comment]
> Hi @SplendidPiePizza, what errors do you see?

sorry for long response, but i still get an error. mod-openvino process library not linked, should i sent screenshot?

**Comment by RyanMetcalfeInt8** [comment]
> > Hi @SplendidPiePizza, what errors do you see?
> 
> sorry for long response, but i still get an error. mod-openvino process library not linked, should i sent screenshot?

Yes, please send screenshot.

**Comment by SplendidPiePizza** [comment]
> > > Hi @SplendidPiePizza, what errors do you see?
> > 
> > 
> > sorry for long response, but i still get an error. mod-openvino process library not linked, should i sent screenshot?
> 
> Yes, please send screenshot.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165284283/642d5cbe-ac02-4c9a-8ca7-62c1de99d10d)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165284283/6a68289c-c753-4273-a334-8f67c2a096de)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165284283/f7ae41fc-4a5c-4594-9747-e5f7b5fb1aad)
My Cpu: AMD A4-6210 APU with AMD Radeon R3 Graphics
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165284283/821063fe-2a26-4001-9316-921e3b5c102f)

why is everything always not work. :(

**Comment by SplendidPiePizza** [comment]
also i installed vc redist

**Comment by RyanMetcalfeInt8** [comment]
Hi @SplendidPiePizza,

Which version of Audacity & plugins do you have installed? Make sure that these have matching versions. I would recommend installing Audacity 3.5.1, and the latest version of the plugins (https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2).

It looks like you'll also need to grab an OpenCL.dll.
1. Download this: https://github.com/KhronosGroup/OpenCL-SDK/releases/download/v2023.04.17/OpenCL-SDK-v2023.04.17-Win-x64.zip
2. Copy OpenCL.dll from zip file (inside 'bin' folder) to your Audacity installation folder.

**Comment by RyanMetcalfeInt8** [comment]
> torch_cpu.dll is missing, is it fine?

I missed that. No, it's not okay. This should have been bundle with the installer. Which version of these plugins did you install?

**Comment by SplendidPiePizza** [comment]
> > torch_cpu.dll is missing, is it fine?
> 
> I missed that. No, it's not okay. This should have been bundled with the installer. Which version of these plugins did you install?

i only downloaded, music seperation, and noise suppresion

**Comment by RyanMetcalfeInt8** [comment]
> > > torch_cpu.dll is missing, is it fine?
> > 
> > 
> > I missed that. No, it's not okay. This should have been bundled with the installer. Which version of these plugins did you install?
> 
> i only downloaded, music seperation, and noise suppresion

I don't know what you mean by that. Please let me know what package you downloaded and used to install.

**Comment by SplendidPiePizza** [comment]
> > > > torch_cpu.dll is missing, is it fine?
> > > 
> > > 
> > > I missed that. No, it's not okay. This should have been bundled with the installer. Which version of these plugins did you install?
> > 
> > 
> > i only downloaded, music seperation, and noise suppresion
> 
> I don't know what you mean by that. Please let me know what package you downloaded and used to install.

when i install the bundle, (installer) i only selected music seperation, and noise suppression, but it worked fine. but the vocals is low quality but i don't care.

**Comment by RyanMetcalfeInt8** [comment]
> when i install the bundle, (installer) i only selected music seperation, and noise suppression, but it worked fine. but the vocals is low quality but i don't care.

I'm very confused. It's working fine when you use the installer?

**Comment by SplendidPiePizza** [comment]
> > when i install the bundle, (installer) i only selected music seperation, and noise suppression, but it worked fine. but the vocals is low quality but i don't care.
> 
> I'm very confused. It's working fine when you use the installer?

i am sorry i am not an american this time, (yes it pretty is fine) when installer got in, i only selected music seperation (forgot to uncheck the box noise suppression). then when i click mod-openvino then enabled. IT WORKS!. btw the pros is, pretty neat ai,
cons is when i isolate the vocals. It's low quality, but i don't care.

**Comment by SplendidPiePizza** [comment]
is it fine, torch_cpu.dll is not detected but it's on hard disk. but when i use music separation it's fine, if you think it's fine, you can close this. If not then reply.

**Comment by RyanMetcalfeInt8** [comment]
Okay, I'm glad it's working. I don't know why Dependencies tool is showing torch_cpu.dll as missing. I'll close this one. Thanks!
