### ISSUE TITLE
Audacity has been updated to 3.5.1

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#137]
Audacity has been updated to 3.5.1. Due to this, OpenVINO AI doesn't work. Please, could You look on It and fix this problem? Thank You.
Marco Oros

**Comment by RyanMetcalfeInt8** [comment]
https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2

**Comment by RyanMetcalfeInt8** [comment]
Closing this issue as new package is available.
