### ISSUE TITLE
OpenVino installation fails on the patch release 3.5.1

### ISSUE THREAD

**Issue by petersampsonaudacity** [intel/openvino-plugins-ai-audacity#138]
OpenVino install into the recent patch release directory I have for 3.5.1

But when I re-launch Audacity after enabling the module I get this error message:

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/e865b351-51fb-4b81-b582-596aeb6341b0)

And it crashes Audacity:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/4179e75e-5a4d-4724-aa16-8a8322be17a9)

**Comment by petersampsonaudacity** [comment]
And on subsequent relaunch I see this in Modules prefs
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/6be170c1-6eb7-4a8f-bec4-dbab46631828)

**Comment by vivadavid** [comment]
Hi,

I've got the same error message. The latest OpenVino release is specifically targeted for 3.5.0, but I was hoping that it might still work with version 3.5.1 as it contains only a few bug fixes compared to 3.5.0.

Will this issue be addressed in future OpenVino releases, so that the compatibility remains unless there's something fundamentally different in a new version of Audacity?

Otherwise, the only solution I can think of is not to update Audacity until the corresponding OpenVino update is released too.

**Comment by petersampsonaudacity** [comment]
@vivadavid   3.5.0 should be fine for you unless you are on a Mac with a macOS version of 11 or lower

And as an OpenVino user it's likely that you are not on a Mac ...

**Comment by vivadavid** [comment]
> @vivadavid 3.5.0 should be fine for you unless you are on a Mac with a macOS version of 11 or lower
> 
> And as an OpenVino user it's likely that you are not on a Mac ...

Yes, I'm actually on a PC running Windows 11. Maybe I should have stayed on 3.5.0, but I try to keep all my software as updated as possible.

**Comment by RyanMetcalfeInt8** [comment]
https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2

**Comment by vivadavid** [comment]
I've just installed it and it works: thanks!

I particularly appreciate the instructions to avoid downloading the models again. For a future release, it'd be great if the installer could detect:

1. Which models are already downloaded.
2. Which models are already downloaded but have been updated and, therefore, are worth reinstalling.

**Comment by RyanMetcalfeInt8** [comment]
Hi @vivadavid,

Thanks for the feedback.

Yes, we'll work on improving the model download / management mechanism. It definitely needs some refinement.

Thanks all -- I'll close this issue as completed for now.
