### ISSUE TITLE
both 2 Stem and 4 Stem Separation Modes worked only once and never worked again after that

### ISSUE THREAD

**Issue by akash07k** [intel/openvino-plugins-ai-audacity#14]
Hi there.

First of all, thanks a lot for this wonderful plugin. I tried the plugin for separating the music from the music, and used 2 Stem Separation modes for it. It worked exceptionally well, and I was very happy as well as amazed. I selected the CPU as the Inference Device. However, this worked only once for me, and after that one attempt, it never worked again. It surely is making 2 different tracks for vocals and instruments; however, both of those tracks are completely garbled and don't have any separation whatsoever. The instrumental track still contains the vocals with loud and bad-quality audio, and the vocal track is not producing any sound at all.

I then tried to choose GPU as the Inference Device, but got the same results. I also tried with 4 Stem mode, but encountered the same issues. I deleted the Audacity configuration directories from both %localappdata% and %appdata% directories, uninstalled and installed Audacity after deleting all the leftovers, reinstalled the plugin by following the instructions as per the documentation, and enabled the plugin, but still got the same results.

Please help. It is important to note that the separation is not working even for the song for which it worked in the first attempt. I also tried other songs, but had no luck.

**Comment by RyanMetcalfeInt8** [comment]
Hi @akash07k, thanks for the report. Can you give me some details about your setup such as CPU version, Windows version, etc.?

As you saw, this appears to be the same issue as https://github.com/intel/openvino-plugins-ai-audacity/issues/1 

It appears that there's something going on with the OpenVINO model caching. Basically, the very first time a model is used, it compiles that model for the specified device and caches the 'blob' in ```%appdata%\audacity\openvino-model-cache``` directory. 

Can you manually delete this folder (```%appdata%\audacity\openvino-model-cache```), and try the music separation effect again? (and no need to uninstall anything).

**Comment by akash07k** [comment]
@RyanMetcalfeInt8  Ah, my bad.
I forgot to mention my system details.
CPU: AMD Ryzen 9 7950X, 64 GB RAM.
Windows: Windows 11 22631.2861

And yes, I deleted the whole %appdata%\audacity folder but no luck.
However, I'll do a system image restore from my  Macrium Reflect backup tomorrow in order to see if it works then or not.

**Comment by RyanMetcalfeInt8** [comment]
@akash07k  Thanks!

> And yes, I deleted the whole %appdata%\audacity folder but no luck.

Hmm, very strange. The cache directory is the only 'stateful' thing that I can think of that could cause this kind of behavior (feature worked first time, but never again). 

As I suggested in issue #1 , can you see if the same behavior exists for other effects such as whisper transcription?

**Comment by akash07k** [comment]
I did a complete Windows restore from my Macrium Reflect backup,  and now all is well.
It works fine now, however, I'm still required to clean the cache directory everytime in order to make it work.
I hope your next update will fix this as well.
Hi @RyanMetcalfeInt8 
> @akash07k Thanks!
> 
> > And yes, I deleted the whole %appdata%\audacity folder but no luck.
> 
> Hmm, very strange. The cache directory is the only 'stateful' thing that I can think of that could cause this kind of behavior (feature worked first time, but never again).
> 
> As I suggested in issue #1 , can you see if the same behavior exists for other effects such as whisper transcription?
