### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by toland1h** [intel/openvino-plugins-ai-audacity#140]
I get this error when i try to install:
Unable to execute file in the temporary directory. Setup aborted. Error 5:Access is denied.

**Comment by RyanMetcalfeInt8** [comment]
Hi @toland1h,

Can you send screenshot? Which stage of installation do you receive this error?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @toland1h, 

Have you tried running this as administrator?

Thanks,
Ryan

**Comment by toland1h** [comment]
Thanks for all the help. I get the error a but 3 seconds after I try to run
the exe file. I did try to run as an administrator same result. I am not
much of a computer person so I am sure it is me.

**Comment by RyanMetcalfeInt8** [comment]
Hi @toland1h,

Can you try the latest patch release: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1

Thanks,
Ryan
