### ISSUE TITLE
Unable to load the "mod-openvino" module

### ISSUE THREAD

**Issue by hoseinhzk** [intel/openvino-plugins-ai-audacity#141]
Hi , I installed Audacity 3.5.1 x64 and openvino plugin v3.5.1-R2 but it shows error. can you plz help ?

Device name	DESKTOP-CQJ4GT9
Processor	Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.85 GB usable)
Device ID	F7D0DDF5-643E-4D2A-B3C5-0C99C69E3E2F
Product ID	00331-10000-00001-AA156
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎25/‎2024
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0

![err01](https://github.com/intel/openvino-plugins-ai-audacity/assets/168163032/6915a470-1545-4474-93a5-f33de0ade5a7)
![err2](https://github.com/intel/openvino-plugins-ai-audacity/assets/168163032/7fa4d265-4f31-4d0b-b28f-70ae30a69bc8)
![err3](https://github.com/intel/openvino-plugins-ai-audacity/assets/168163032/aab21e4b-574d-4d1f-9f9e-25563bcf125c)

also running of hello_query_device.exe doesn't show any output results...
also I have installed VC_redist.x64 but still it shows the same error.

thanks in advance

**Comment by RyanMetcalfeInt8** [comment]
Can you try the following?
1. Download this: https://github.com/KhronosGroup/OpenCL-SDK/releases/download/v2023.04.17/OpenCL-SDK-v2023.04.17-Win-x64.zip

2. Inside this zip folder, inside ```bin``` folder, you'll find ```OpenCL.dll```. Can you try copying this into your ```Audacity``` folder?

3. Re-set Audacity module to 'Enabled' in preferences, and restart Audacity.

Our installer doesn't package / distribute this, as we've found it to be included by Windows on all systems we've been testing. But recently we realized that may not necessarily be the case for *all* Windows installations... anyway, let me know if that resolves your issue.

**Comment by hoseinhzk** [comment]
Awesome ... Now it runs successfully!
thanks for your help.

**Comment by RyanMetcalfeInt8** [comment]
Great!
