### ISSUE TITLE
Unable to load the model

### ISSUE THREAD

**Issue by kylxbn** [intel/openvino-plugins-ai-audacity#144]
I have been using the plugin without a problem from the integrated Intel GPU (Intel i7-13700, UHD 770) but I upgraded to an NVidia 4070 Super and the plugin stopped working when using the GPU. This is the log:

```
18:10:41: Error: In Music Generation V2, exception: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for result:new_key_value_23_0/sink_port_0 node (type=reorder)
[GPU] Original name: new_key_value_23_0/sink_port_0
[GPU] Original type: Result
[GPU] Reason: Check '!kernels.empty()' failed at src\plugins\intel_gpu\src\kernel_selector\kernel_selector.cpp:70:
[GPU] Couldn't find a suitable kernel for result:new_key_value_23_0/sink_port_0 params raw string: F32_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v2_p0_0;F16_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v2_p0_0
```

Could this be incompatibility issues, or am I missing a driver or something?

Edit:

Oh. It seems that only the following GPUs are supported at the moment:

- Intel® HD Graphics
- Intel® UHD Graphics
- Intel® Iris® Pro Graphics
- Intel® Iris® Xe Graphics
- Intel® Iris® Xe Max Graphics
- Intel® Arc™ GPU Series
- Intel® Data Center GPU Flex Series
- Intel® Data Center GPU Max Series (limited support)

I thought that the "GPU" setting referred to any GPU. If I am mistaken, please close this issue. Apologies for the confusion.

**Comment by RyanMetcalfeInt8** [comment]
Hi @kylxbn,

Right, it looks like it's a lower level OpenVINO framework support issue. 

Thanks,
Ryan

**Comment by Astra060** [comment]
Any update or fix on this? I'm using RTX 2060, and I don't have Cuda Toolkit installed. I usually install it with python. any help?

**Comment by RyanMetcalfeInt8** [comment]
Hi @Astra060,

Nvidia GPUs aren't well supported by OpenVINO yet -- unfortunately, there's not really any fix for that. As @kylxbn listed, only those GPUs are supported right now.

Thanks,
Ryan
