### ISSUE TITLE
Option "Music Style Remix" does not appear

### ISSUE THREAD

**Issue by JaB43a** [intel/openvino-plugins-ai-audacity#145]
There is supposed to be (or was) an option to make a remix of an audio track, but either they have removed it, or it doesn't appear in option "OpenVINO AI effects"

**Comment by RyanMetcalfeInt8** [comment]
Hi @JaB43a,

Yes, this is a feature that we were supporting with the older 'Riffusion' based features. As we are transitioning to use MusicGen LLM's, we removed that feature (for now) in the latest 3.5.X releases. It may show back up in the future in some revised form.

Thanks!
Ryan

**Comment by Zenguycolorado** [comment]
That sucks.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Zenguycolorado,

Yes, it was a tough decision to remove it, and it was pretty fun to experiment with -- but found that it rarely resulted in something 'useful' (that's just our opinion though)-- but just curious -- was it something that you were already using, or something that you heard about and were hoping to use?

Thanks,
Ryan

**Comment by Zenguycolorado** [comment]
It was something that I'd just started to use.

**Comment by smartapp-ep** [comment]
@RyanMetcalfeInt8 : hope to have it back in near future, thanks!
