### ISSUE TITLE
error code 225

### ISSUE THREAD

**Issue by dolan26** [intel/openvino-plugins-ai-audacity#146]
When i run the set up it says "failed to set up directory permissions error code 225"

**Comment by dolan26** [comment]
![Screenshot 2024-04-26 184356](https://github.com/intel/openvino-plugins-ai-audacity/assets/168238107/6fd9935c-5130-4f2a-b316-b0a4bda62484)

**Comment by Tommiganci** [comment]
same problem... i've tried to lauche several time the exe but with no result

**Comment by RyanMetcalfeInt8** [comment]
Hi @Tommiganci, @dolan26,

Hmm, have you tried running as administrator?

Thanks,
Ryan

**Comment by Tommiganci** [comment]
Hi @RyanMetcalfeInt8 ,
i've tried many times as administrator and not but nothing changed. I have already updated Audacity to 3.5.1

**Comment by pdvigne** [comment]
same issue! What's solution besides try to enter as administrator?Any other suggestion?

**Comment by RyanMetcalfeInt8** [comment]
Hi all, can you try the latest patch release? 

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1

**Comment by RyanMetcalfeInt8** [comment]
Great! Glad it's working now.
