### ISSUE TITLE
Any openVINO app crashes

### ISSUE THREAD

**Issue by Ioannis-66** [intel/openvino-plugins-ai-audacity#149]
Hi!

On Audacity 3.5.1 any open VINO app just crashes.

I attached the crash report and log files, if any one can help.

Thank you
Ioannis

[Audacity 3.5.1 crash report.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/15139208/Audacity.3.5.1.crash.report.txt)
[log.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/15139209/log.txt)

**Comment by RyanMetcalfeInt8** [comment]
Hmm, can you let me know the details of your hardware setup (like CPU model, etc.)?

Also, can you give more detail what you mean by "any open VINO app crashes"?

**Comment by Ioannis-66** [comment]
Thanks for the reply.
Tried on a HP laptop and also on a Desktop PC, the Dell Precision 3650 with same crash of Audacity when it tries to run any openVINO app.

For example, on a selected sound sample, I go to menu Analyze-OpenVino Whisper Transcription, select Source Language Greek, then Apply.

Runs two times resampling progress bar and then crashes.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Ioannis-66,

Sorry for delayed response -- Can you try with the latest plugin release (v3.5.1-R2.2)?

**Comment by Ioannis-66** [comment]
Dear Ryan,

 

Thank you for the reply.

 

Indeed, the test show that the problem is fixed.

 

Amazing what computers do today!

 

Ioannis
