### ISSUE TITLE
Rocm for Windows

### ISSUE THREAD

**Issue by bennmann** [intel/openvino-plugins-ai-audacity#150]
Please considering making an AMD release on windows for those with the AMD HIPsdk for Windows.

It's probably a few compilation line changes to use HIP(hipblas etc) vs Cuda in Visual Studio compilation.

**Comment by RyanMetcalfeInt8** [comment]
Hello -- our release for Windows will continue to support OpenVINO-supported devices (listed here: https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html). 

I'm not familiar with HIP sdk, or if there is some way to make use of that within our project -- However, we have posted our full source code and build instructions for developers who want to experiment.
