### ISSUE TITLE
OpenVino and SurgeXT install unsuccessful

### ISSUE THREAD

**Issue by modernminstrel** [intel/openvino-plugins-ai-audacity#152]
I have tried to install both OpenVino and Surge XT Effects plugins but both are greyed out when opening the Effects menu. Additionally,  ALL of the submenus on the Effects tab are greyed out, as well. The only Effect to show an active submenu is Plugin Alliance.

Prior to upgrading to Build 3.5.1, all these effects were active. I need some help!

**Comment by RyanMetcalfeInt8** [comment]
Hi @modernminstrel,

Do you have any audio selected? Usually selections on the effect menu are greyed out until you select some audio.

Thanks,
Ryan

**Comment by modernminstrel** [comment]
Ryan,
Great! That fixed all of the greyed out commands!
BUT!
I am still not showing the OpenVino options. Suggestions?
TIA.
John
"Too often we enjoy the comfort of opinion without the discomfort of thought." - JFK 

    On Sunday, April 28, 2024 at 02:13:48 PM EDT, Ryan Metcalfe ***@***.***> wrote:  
 
 


Hi @modernminstrel,

Do you have any audio selected? Usually selections on the effect menu are greyed out until you select some audio.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @modernminstrel,

>I am still not showing the OpenVino options. Suggestions?

Sorry, I don't really understand -- what options are not showing?

Thanks,
Ryan

**Comment by modernminstrel** [comment]
Ryan,
I just upgraded my Audacity to v3.5.1. Under the previous version OpenVino appeared under the Effect menu and worked properly.
Now, under the Effect menu, the only options to appear are Melodyne, PlugIn Alliance, SurgeXT Effects and Waves.
Additionally, the Plugin Manager shows no OpenVino options.
Thanks for your help.
John
"Too often we enjoy the comfort of opinion without the discomfort of thought." - JFK 

    On Tuesday, April 30, 2024 at 10:32:00 AM EDT, Ryan Metcalfe ***@***.***> wrote:  
 
 


Hi @modernminstrel,


I am still not showing the OpenVino options. Suggestions?


Sorry, I don't really understand -- what options are not showing?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @modernminstrel, did you re-enable the plugins in Preferences->Modules after upgrading?

**Comment by modernminstrel** [comment]
Ryan,
That was it. Thank you so much for your help!
John    On Friday, May 3, 2024 at 03:19:10 PM EDT, Ryan Metcalfe ***@***.***> wrote:  
 
 


Hi @modernminstrel, did you re-enable the plugins in Preferences->Modules after upgrading?

**Comment by RyanMetcalfeInt8** [comment]
Glad to hear!
