### ISSUE TITLE
Theuns

### ISSUE THREAD

**Issue by TheunsWium** [intel/openvino-plugins-ai-audacity#155]
Unable to load the "mod-opnvino" module

Error: The specified procedure could not be found

**Comment by RyanMetcalfeInt8** [comment]
Hi @TheunsWium,

I'll need a little bit more info -- which version of Audacity are you using, and what version (release) of our plugins did you install?

Thanks,
Ryan

**Comment by TheunsWium** [comment]
Thankyou

 for replying , I downloaded the newest version of audacity and everything
is working 100% regards Theuns Wium

**Comment by RyanMetcalfeInt8** [comment]
Perfect, glad it's now working for you!
