### ISSUE TITLE
Setup not running

### ISSUE THREAD

**Issue by omar-alajlouni** [intel/openvino-plugins-ai-audacity#157]
All privilege on Audacity folder is accessed.
Windows Defender Disabled.
I have latest version Audacity 3.5.1 
The program audacity-win-v3.5.1-R2-64bit-OpenVINO-AI-Plugins not running.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/115810923/b8b8a232-0c9d-484f-9ceb-2436764cb1dd)

**Comment by RyanMetcalfeInt8** [comment]
Hi @omar-alajlouni,

I have seen a few reports of this... still trying to figure out why this is happening for some folks. Does this error occur before, or after this windows pops up?
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/e729db84-9240-4323-82bc-b9c9e3bfa491)

Thanks,
Ryan

**Comment by omar-alajlouni** [comment]
Thanks Mr. @RyanMetcalfeInt8 
this error occur after this windows pops.

**Comment by RyanMetcalfeInt8** [comment]
> Thanks Mr. @RyanMetcalfeInt8 this error occur after this windows pops.

Got it, and it also shows this error if you right-click and choose 'run as administrator'?

**Comment by omar-alajlouni** [comment]
> > Thanks Mr. @RyanMetcalfeInt8 this error occur after this windows pops.
> 
> Got it, and it also shows this error if you right-click and choose 'run as administrator'?
The error occurs when running as or without administrator.

**Comment by RyanMetcalfeInt8** [comment]
Hi @omar-alajlouni, can you try the updated release, here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1 

Thanks!

**Comment by omar-alajlouni** [comment]
Thanks Mr. @RyanMetcalfeInt8 
It's working.
Windows update which was problem

**Comment by RyanMetcalfeInt8** [comment]
Glad it's working now!
