### ISSUE TITLE
Fails to work on 3.5.0 alpha

### ISSUE THREAD

**Issue by petersampsonaudacity** [intel/openvino-plugins-ai-audacity#16]
I installed the OpenVino components in my latest 3.5.0 alpha - and it fails to run, I get the following message when I launch this modified 3.5.0
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/949895ac-a2cb-4069-b513-f5c45cbcab5f)

I can dismiss that message with the OK button and Audacity launches,

But when I go to Modules preferences I see that the mod-openvino is marked as **Failed** (I had previously enabled it on initial launch as per your installation instructions_
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/50205984/b1a50114-e228-476e-86ff-8d19f18cb438)

**Comment by petersampsonaudacity** [comment]
Also reported on Audacity's GitHub issues log:
https://github.com/audacity/audacity/issues/5840

**Comment by RyanMetcalfeInt8** [comment]
We have posted an updated release that is compatible with Audacity 3.5.0: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Thanks!
