### ISSUE TITLE
Transcripts cannot be (vertically) scrolled in Audacity.

### ISSUE THREAD

**Issue by The3IC** [intel/openvino-plugins-ai-audacity#162]
Only the first N lines are visible in the Audacity window, seems there is not way to scroll down when there are more lines?

**Comment by RyanMetcalfeInt8** [comment]
Hey @The3IC,

Could you post a screenshot? You're referring to N lines within a single label track here?

Thanks,
Ryan

**Comment by The3IC** [comment]
![scroll](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/ca9e3f3e-7803-49db-80e9-2cf2ccfecffe)
So I have more lines down where the arrow points but cannot find a way to access them within the window? 
Kind of expecting a scrollbar on the right side where the red up/down line is?

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC, I think in this case if you zoom in, it will collapse into a single line. Can you try it?

**Comment by The3IC** [comment]
> I think in this case if you zoom in, it will collapse into a single line. Can you try it?

There is two things here:

1) multiple transcripts, let's call then "languages" (in the screen grab "native" and translated. So I can access the underlying language, yes, by collapsing a language into a single row.
2) Scroll inside one language when there are more than 10-20 llines generated (number depends on your display lize).

So 1) is OK, but haven't found a way to do 2), the "scrollbar" I envisioned is just for one language so in the screen grab case, there would be 2, one for the native language and one for the translation.

**Comment by The3IC** [comment]
@RyanMetcalfeInt8 , I looked a little into this and seems you might be limited by Audacity label handling so added a feature request over at Audacity land (https://github.com/audacity/audacity/issues/6397 in case you want to support it :-) )

**Comment by RyanMetcalfeInt8** [comment]
Thanks @The3IC -- Right, this is something handled by Audacity itself, so I'll close this one.
