### ISSUE TITLE
OpenVINO Music Generation - no model selection in dropdown?

### ISSUE THREAD

**Issue by derwin12** [intel/openvino-plugins-ai-audacity#167]
Not seeing the model selection and I assume is the reason the generate is not enabled.
Anything I should be doing? Seems the readme/instructions is a bit out of date.
(Audacity 3.5.1 on Windows with NVDA card)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/4643499/9baf42f2-5286-4363-8288-234149f73a83)
(are there better forums for this question - as perhaps is not an issue)

**Comment by RyanMetcalfeInt8** [comment]
Hi @derwin12,

These models are typically downloaded by the installer. When you installed, did you check the MusicGen model boxes?
<img width="450" alt="image" src="https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/4958ce3e-8b32-4333-adae-f8bc9ad2f540">

You can always re-run the installer, and uncheck everything except the *new* models that you want to install. It won't delete the ones that you previously installed.

BTW, you may not have much luck with that NVidia GPU, as it's not officially supported by the OpenVINO framework.

Thanks,
Ryan

**Comment by derwin12** [comment]
Gotcha thanks -- missed the models at the bottom .. Thanks
