### ISSUE TITLE
Music Separation not working

### ISSUE THREAD

**Issue by raivologo** [intel/openvino-plugins-ai-audacity#168]
Hi!

When I select the Music Separation effect, I get the following error: 
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/87151260/16217958-0c0f-4eea-9bc0-1b0c5203512b)

I do as the pop up says, and this is what I get:
21:19:49: Operation 'OpenVINO Music Separation' took 0,032000 seconds. Poll was called 2 times and took 0,000002 seconds. Yield was called 0 times and took 0,000000 seconds.
21:20:18: Operation 'Pre-processing' took 0,000000 seconds. Poll was called 0 times and took 0,000000 seconds. Yield was called 0 times and took 0,000000 seconds.
21:20:18: Error: In Music Separation, exception: Exception from src\inference\src\cpp\core.cpp:126:
Exception from src\inference\src\model_reader.cpp:160:
Unable to read the model: C:\Program Files\Audacity\openvino-models\htdemucs_v4.xml Please check that model format: xml is supported and the model is correct. Available frontends: ir onnx paddle pytorch tf tflite 

What should I do?

**Comment by RyanMetcalfeInt8** [comment]
Hi @raivologo,

When you ran the installer, did you select the Music Separation models to install?

<img width="450" alt="image" src="https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/7aa574ef-b7e9-40da-8a77-f12c19b60bbe">

I would recommend that you re-run the installer, and select the models for the features that you want to use. 

Thanks,
Ryan

**Comment by raivologo** [comment]
Hi @RyanMetcalfeInt8! 

The OpenVINO installation tutorial instructs you to choose _Install no models_, which I did.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/87151260/00b43d53-70ce-4338-a156-3fbd8acb0a35)

But, I'll do as you say and see if it helps! Thanks in advance.

**Comment by raivologo** [comment]
Hi @RyanMetcalfeInt8 !

So it seems that I just made the mistake of not selecting any model when I first installed it. I just re-ran the installer and selected Music Separation (it's the only model I downloaded OpenVINO for, in fact). God, how idiot I was 😅

It all works now! Thank you, brother.

**Comment by RyanMetcalfeInt8** [comment]
Glad you were able to get it to work, @raivologo. Yes, I have to think about how to clarify wording of the instructions -- it was meant to imply that if you've already run a previous version of the installer, and already have the models installed, then choose 'Install no models'.
