### ISSUE TITLE
Can't use GPU for Music Separation

### ISSUE THREAD

**Issue by raivologo** [intel/openvino-plugins-ai-audacity#170]
Hi, it's me again! 😅

I'm using the Music Separation model now, but just discovered one issue:
When I selected the GPU device (so it wouldn't take as long as with CPU), I had that same mistake again:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/87151260/7609ac9f-6957-4e55-b3e5-62173747c562)

I checked the log, and here's what it says:
13:23:51: Error: In Music Separation, exception: Exception from src\inference\src\cpp\core.cpp:126:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for convert:Multiply_56787 node (type=reorder)
[GPU] Original name: Multiply_56787
[GPU] Original type: Convert
[GPU] Reason: Check '!kernels.empty()' failed at src\plugins\intel_gpu\src\kernel_selector\kernel_selector.cpp:70:
[GPU] Couldn't find a suitable kernel for convert:Multiply_56787 params raw string: F16_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0;F32_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0

What should I do now?

**Comment by RyanMetcalfeInt8** [comment]
Hi @raivologo,

Are you using an NVidia GPU by chance? I have seen this issue reported for Nvidia GPUs, but there is not much I can do, unfortunately, as they are not well-supported by underlying OpenVINO framework.

Thanks,
Ryan

**Comment by raivologo** [comment]
Hi @RyanMetcalfeInt8!

Yes, I use a NVidia GPU. NVidia GTX Ti 1050, for intsance.

You might already have guesses I tried using my GPU for Music Separation so it wouldn't consume my CPU, other than reducing the time it takes. My PC is really good overall but it does have a pretty small RAM (8GB), which is why I tend to reccur to my GPU for stuff like this.

But, it's just that OpenVINO is yet to have better support for NVidia GPUs, as of now, like you said.

Once again, thanks, brother!
