### ISSUE TITLE
Error message: mod-openvino is not a valid Win32 application

### ISSUE THREAD

**Issue by JACK-O-BEAN** [intel/openvino-plugins-ai-audacity#175]
I have installed and uninstalled openvino multiple times but keep getting the same error message. Is there a problem with the plug-in, do I need an extra bit of software I don't know about or is there a problem with my PC? I have the latest version of Audacity, so I don't think it is that and I have tried installing the different model options (none, basic and full) but get the same result: mod-openvino is not a valid Win32 application.

**Comment by RyanMetcalfeInt8** [comment]
Hi @JACK-O-BEAN,

I've heard of others having this issue when they install these plugins into a 32-bit Audacity installation. Can you double check that you are using the 64-bit version of Audacity?

Thanks,
Ryan

**Comment by JACK-O-BEAN** [comment]
> Hi @JACK-O-BEAN,
> 
> I've heard of others having this issue when they install these plugins into a 32-bit Audacity installation. Can you double check that you are using the 64-bit version of Audacity?
> 
> Thanks, Ryan

**Comment by JACK-O-BEAN** [comment]
Thanks Ryan. No problems with the 64-bit version. Vocal extraction worked a treat. Thanks again.

**Comment by JACK-O-BEAN** [comment]
> Hi @JACK-O-BEAN,
> 
> I've heard of others having this issue when they install these plugins into a 32-bit Audacity installation. Can you double check that you are using the 64-bit version of Audacity?
> 
> Thanks, Ryan

Thanks Ryan. No problems with the 64-bit version. Vocal extraction worked a treat. Thanks again.

**Comment by RyanMetcalfeInt8** [comment]
Glad you were able to get it working. Cheers!
