### ISSUE TITLE
Music Style Remix not showing up

### ISSUE THREAD

**Issue by Manwhosmokes** [intel/openvino-plugins-ai-audacity#179]
I have installed the latest Audacity (3.5.1 64bit) and I downloaded and installed the latest openvino plugin(3.5.1 R2.1). I did the preferences "Enabled" option, restarted Audacity. When I go to Effect>OpenVINO AI Effects, I only have 2 options, "OpenVino Music Separation" and "OpenVino Noise Suppression". There is no option for Music Style Remix. Please haaalp.
![Untitled-1](https://github.com/intel/openvino-plugins-ai-audacity/assets/169424647/2c618b4b-ff82-433d-ba50-b14f0a8ffec4)

**Comment by SplendidPiePizza** [comment]
you should put an audio first.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Manwhosmokes,

Music Style Remix was one of the features for our initial release [v3.4.2-R1](https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.4.2-R1). We removed this feature for our latest release ([v3.5.1-R2.1](https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1), as we are starting to replace all of the Riffusion-based features with MusicGen LLM features. We are hoping rework 'Style Remix' and add it back to the project at some later time.

**Comment by RyanMetcalfeInt8** [comment]
Note that latest release has Music Continuation feature, which isn't exactly 'Style Remix', but is pretty fun to play around with: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/feature_doc/music_generation/README.md#audio-continuation-on-same-track
