### ISSUE TITLE
Openvino Audacity Issue

### ISSUE THREAD

**Issue by Mojazz1231** [intel/openvino-plugins-ai-audacity#181]
I'm on a Windows 64 Bit computer with Windows 11 operating system. I have Audacity 3.5.1 installed. I installed the latest version of the  Openvino plugin  for Audacity 3.5.1 but when I go to reopen Audacity I get a message that says the Openvino is for Audacity 3.5 and will not be loaded or something to that effect. This was after I followed the instructions and went to Preferences and enabled Openvino in Audacity, closed the program and restart Audacity. What I'm I missing or doing wrong? Is the Openvino download not for the latest version of Audacity 3.5.1?

**Comment by RyanMetcalfeInt8** [comment]
Hi @Mojazz1231,

Can you share the screenshot for the popup message that you are getting?

Thanks,
Ryan

**Comment by Mojazz1231** [comment]
![Open](https://github.com/intel/openvino-plugins-ai-audacity/assets/169494802/6a70d6f1-08aa-4461-8e88-9a243b625da2)

**Comment by Mojazz1231** [comment]
![udacity 3 5 1](https://github.com/intel/openvino-plugins-ai-audacity/assets/169494802/50a04875-7328-4453-85b2-b1ba92bd0469)

**Comment by RyanMetcalfeInt8** [comment]
It seems like you installed the 3.5.0 version of these plugins. Can you try again with this version: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1 

Thanks,
Ryan

**Comment by Mojazz1231** [comment]
![Aud Pref](https://github.com/intel/openvino-plugins-ai-audacity/assets/169494802/f135e99d-977c-4cb5-a1a7-eecddfe2f1a1)

**Comment by Mojazz1231** [comment]
OK I see it now but I don't have anything loaded just yet to test it. Will have to do this later because I have to hurry and leave for now. Thank you and if I have additional problems with this I'll be back

**Comment by Mojazz1231** [comment]
Finally got some time to test this stem separator out. Very impressed! Very impressed indeed! Thanks for all the help to resolve the issue I had. I will be using this very much.
