### ISSUE TITLE
After enabling and relaunching Audacity 3.51 / 64 bit I get error that module can't be found

### ISSUE THREAD

**Issue by Ocalvopia** [intel/openvino-plugins-ai-audacity#182]
I have A windows 10 / 64 bit machine.  I removed all old Audacity and installed latest Windows 3.51 64 bit.  I installed v3.51-R2.1, deselected music models and one other set of models.   Mod-openvino is available in modules and I enabled it. Closed audacity and re-opened.  Then I get error below.  " unablle to load the "mod-openvino" module"  I checked and the module .dll is in modules folder.  Only one Audacity version loaded.   Any ideas what might be wrong?.  Oh and Audacity then loads and Mod-openvino is set to Failed.   Thanks for your help.  I am primarily interested is using the stem separator.

![Screenshot 2024-05-10 211221](https://github.com/intel/openvino-plugins-ai-audacity/assets/169507167/4053ee5b-8103-4691-a29f-d9dd2bd2edcb)

**Comment by RyanMetcalfeInt8** [comment]
Hi @Ocalvopia,

Can you try the following?
1. Download this: https://github.com/KhronosGroup/OpenCL-SDK/releases/download/v2023.04.17/OpenCL-SDK-v2023.04.17-Win-x64.zip

2. Inside this zip folder, inside ```bin``` folder, you'll find ```OpenCL.dll```. Can you try copying this into your ```Audacity``` folder?

3. Re-set Audacity module to 'Enabled' in preferences, and restart Audacity.

Our installer doesn't package / distribute this, as we've found it to be included by Windows on all systems we've been testing. But recently we realized that may not necessarily be the case for *all* Windows installations... anyway, let me know if that resolves your issue.

**Comment by ronkepos** [comment]
I am using Audacity v3.51 x64 bit as portable version (by creating Portable Setting folder inside audacity main folder) and I installed Audacity-OpenVINO-Module-3.4.2-R1.zip and also have encountered the same issues as @Ocalvopia. I have tried @RyanMetcalfeInt8 method and the problem still there.

**Comment by RyanMetcalfeInt8** [comment]
> I am using Audacity v3.51 x64 bit as portable version (by creating Portable Setting folder inside audacity main folder) and I extracted Audacity-OpenVINO-Module-3.4.2-R1.zip and openvino-models.zip to Audacity main folder, and also have encountered the same issues as @Ocalvopia. I have tried @RyanMetcalfeInt8 method and the problem still there. My os is Windows 10 Pro 64bit.

Hi @ronkepos, if you're using Audacity v3.5.1, then you need to be using this version of the plugins: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1

Thanks,
Ryan

**Comment by ronkepos** [comment]
Hi @RyanMetcalfeInt8 thank you for your respond. Is there a zip version for the v3.5.1-R2.1?

**Comment by RyanMetcalfeInt8** [comment]
> Hi @RyanMetcalfeInt8 thank you for your respond. Is there a zip version for the v3.5.1-R2.1?

There isn't -- only an installer for v3.5.1-R2.1.

**Comment by ronkepos** [comment]
@RyanMetcalfeInt8 I have downgraded to Audacity 3.4.2 and install the Audacity-OpenVINO-Module-3.4.2-R1.zip. Everything is running perfectly. Thanks.

**Comment by Ocalvopia** [comment]
Sorry for the delay.  yes your instructions to move the opencl.dll resolved the issue.  Thank you.

**Comment by Ocalvopia** [comment]
Thanks you fix worked 


Ozzie Calvopina

**Comment by RyanMetcalfeInt8** [comment]
Great!
