### ISSUE TITLE
Cannot install plugins without Administrator rights

### ISSUE THREAD

**Issue by PseudoPort** [intel/openvino-plugins-ai-audacity#183]
My windows computer has limited access to install any software. I have portable audacity on another drive.
When I installed openvino installer it needs Administrator right to be installed. 

Is there a way to install or extract it and manually install?
Suggestion, it is better to have manual installation also openvino module and models.

**Comment by RyanMetcalfeInt8** [comment]
Right now we only distribute as installer, as the installer will take care of user selection / download of the required models. Is it possible for you to install it on another PC, and then zip up Audacity installation?
