### ISSUE TITLE
Audacity becomes "Not responding" when generating transcipots

### ISSUE THREAD

**Issue by The3IC** [intel/openvino-plugins-ai-audacity#185]
Working with slightly longer audio clips and model V3, Audacity becomes "Not responding" when running the Whisper plugin.
- If you mouse over Audacity, the progress window shows "Not responding" 
- The "Remaining time" is only sporadically updated and sometimes the window disappears totally
- The "Cancel" button is not clickable

As a user this is quite annoying as you are never really sure if all is OK or if there is some error. Also the longer sessions, if needed, cannot be interrupted in a clean way.

Tested both on CPU/AMD and CPU/built.in GPU Intel, basic behavior is the same.

Target: OpenVINO/Whisper plugin should be a "good citizen" and not disable the Audacity UI.

**Comment by RyanMetcalfeInt8** [comment]
Yeah I might've noticed that too when using larger models. I think I can address this one pretty easily too -- thanks for filing an issue for it.

**Comment by The3IC** [comment]
Fixed in v3.5.1-R2.2, could still be a little smoother but this is more than adequate!
