### ISSUE TITLE
Unable to install Music separation

### ISSUE THREAD

**Issue by jazzpw** [intel/openvino-plugins-ai-audacity#188]
I've been trying unsuccessfully to install Openvino plugins and music separation to Audacity 3.5.1. Please can you offer any suggestions?
![Screenshot 2024-05-15 115827 Audacity](https://github.com/intel/openvino-plugins-ai-audacity/assets/169899694/5b18f38c-0132-4c3c-8711-5a5f23c20f6b)

**Comment by RyanMetcalfeInt8** [comment]
Can you try the following?

Download this: https://github.com/KhronosGroup/OpenCL-SDK/releases/download/v2023.04.17/OpenCL-SDK-v2023.04.17-Win-x64.zip

Inside this zip folder, inside bin folder, you'll find OpenCL.dll. Can you try copying this into your Audacity folder?

Re-set Audacity module to 'Enabled' in preferences, and restart Audacity.

Our installer doesn't package / distribute this, as we've found it to be included by Windows on all systems we've been testing. But recently we realized that may not necessarily be the case for all Windows installations... anyway, let me know if that resolves your issue.

**Comment by jazzpw** [comment]
Hi Ryan,

Thanks for the information; unfortunately this hasn't worked. I've attached
a screen print of the error message. Do you have any other suggestions
please?
For your information I'm using a brand new laptop running Windows 11.

Thanks and regards,
*Pete*

**Comment by RyanMetcalfeInt8** [comment]
Hi @jazzpw,

I might need a little bit info in order to help here. Which version of these plugins have you installed?

Also, can you follow this guide to provide more info? 
https://github.com/intel/openvino-plugins-ai-audacity/wiki/Debugging-DLL-dependency-issues-on-Windows

Thanks,
Ryan

**Comment by jazzpw** [comment]
Hi Ryan,

I downloaded all the latest versions of the plugins from github last week.

Thanks for the guide, I've followed the procedures and got to the point
where there are still a few missing DLLs. I've attached 2 screenshots so
that you can see which are still outstanding.

Any more help that you can give would be greatly appreciated.
Best wishes,
*Pete*

**Comment by RyanMetcalfeInt8** [comment]
Hi @jazzpw,

Looks like you commented via email, which for some reason doesn't post attached images. Can you comment and add screenshots here directly? Thanks!

**Comment by jazzpw** [comment]
Hi Ryan,
Hopefully you can see them now.
Pete

![Screenshot 2024-05-20 183625](https://github.com/intel/openvino-plugins-ai-audacity/assets/169899694/1f927f23-68ab-47e1-bd42-14457fc3d1f4)
![Screenshot 2024-05-20 183719](https://github.com/intel/openvino-plugins-ai-audacity/assets/169899694/6624396a-a304-4d60-8e90-e49630af4669)

**Comment by jazzpw** [comment]
Hi Ryan,
Have you had any more luck with my issue with missing DLLs?
Best wishes,
Pete

**Comment by RyanMetcalfeInt8** [comment]
Hi Pete,

Apologies, I must have missed your updated post. It looks like from the dependencies that you are using the original set of 3.4.2-R1 plugins (which is fine). The DLL's that the tool is showing as missing, do you see these in ```C:\Program Files\Audacity``` folder, or are they actually missing? 

Thanks,
Ryan

**Comment by jazzpw** [comment]
Hi Ryan
In my C:\Program Files\Audacity folder, torch_cpu, stable_diffusion_audio_ov and stable_diffusion_ov are showing as DLL files while openvino, c10 and whisper are showing as Plugins.
I hope this helps.
Thanks,
Pete

**Comment by RyanMetcalfeInt8** [comment]
Hi Pete,

I just noticed that your initial report said that you were using Audacity 3.5.1. Is that still true? If so, you should download and install this release: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.2

The DLL's that are being shown in your 'Dependencies' screenshots indicate that you are using plugin version v3.4.2-R1, which won't be compatible with Audacity 3.5.1.

Can you give it a shot? Thanks!

**Comment by jazzpw** [comment]
Hi Ryan,

I've downloaded and installed Audacity 3.6 but I'm still experiencing the same problem. I've run the Dependencies process again but I'm still coming up with the same problem.
![mod-openvino 1 180724](https://github.com/user-attachments/assets/b046a23f-39e6-4bfa-9d91-6e32974cb727)
![mod-openvino 2 180724](https://github.com/user-attachments/assets/9e293d3d-1361-46cf-8859-e90e49ad24cd)

Is there something I'm doing wrong or is this a common glich?

**Comment by RyanMetcalfeInt8** [comment]
Hi Pete,

If you've downloaded Audacity 3.6, then make sure that you install our 3.6-compatible plugins, from here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.0-R3.0

Let me know if you are able to get it working.

Thanks,
Ryan

**Comment by jazzpw** [comment]
Success!!!!
Brilliant, thanks very much for all your help Ryan.
All the best,
Pete.

**Comment by RyanMetcalfeInt8** [comment]
Awesome! Glad it's working for you now.
Cheers!
