### ISSUE TITLE
ENHANCEMENT: Allow single stem separation or selection

### ISSUE THREAD

**Issue by BlakePatricio** [intel/openvino-plugins-ai-audacity#190]
I would love the option to only separate out the stems that you want to remove. For example, I often want to remove only the drums from a track, sometimes just the drums and vocals, but generally want to keep the bass in with the rest of the instrumental. So far the only 2 options are to separate only the vocals and instrumental or 4 stem separation. 4 stem works if I only want the drums, but if I want to remove the drums and vocals, I have to do a 4 stem separation, remove the drums and vocals, then remix the bass back in with the rest of the instrumental. It's not the end of the world, but adds an extra step to achieve the desired results. Hopefully you consider adding this functionality in the future, but so far I'm loving this plugin!

**Comment by RyanMetcalfeInt8** [comment]
Hi @BlakePatricio,

Sorry! Seems I forgot to respond to this. Glad you're liking the plugin -- I think '2 step' behavior (apply music separation, select desired tracks and merge) makes more sense to me than adding more options to the drop-down list for music separation. I added a specific option for 2-stem (vocals + instrumental), as that seemed a very common case. But to add all possible combinations (like  'all but bass', 'all but drums', etc.) would just clutter the UI and cause unnecessary confusion, in my opinion. 

I still very much appreciate you taking the time to give feedback though!
