### ISSUE TITLE
CPU and GPU load profiles effectively load the GPU in the same way

### ISSUE THREAD

**Issue by The3IC** [intel/openvino-plugins-ai-audacity#191]
Doing testing here around issue #187 also noticed that selecting the GPU (Intel on-chip) essentially seem to have no impact on the GPU load profile? On my particular computer CPU load hovers in the 30s while GPU is hardly loaded at all for GPU selection? For CPU selection, CPU loads are higher and GPU seems the same. Processing times with GPU are actually longer than with CPU?

CPU is i7-12700H, GPU is whatever is on that chip.

Typical load when GPU selected:

![load](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/de214380-0334-4a60-9469-e4e4fea25ef3)

Typical load when CPU selected:

![cpu selected](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/a669cd1c-baa2-45b6-adec-c43eefa9a8b9)

**Comment by RyanMetcalfeInt8** [comment]
Hi @The3IC,

Do you see that tiny little drop down carrot to the left of the 'V' in 'Video Decode'? If you click that, you should be able to select more options. What you want to select here is 'Compute'. Can you see if that shows some more activity?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
And by the way -- the way that OpenVINO has been integrated into whisper.cpp is that only *part* of the whisper pipeline (the encoder, to be specific) is offloaded to OpenVINO -- the rest of the pipeline (the decode / token generation pieces) will still run on CPU. For larger whisper models, the encode portion of the pipeline is usually a small fraction of the overall pipeline -- so you'll still see CPU used quite heavily, and not so much GPU utilization.

**Comment by The3IC** [comment]
These are the Intel GPU processors shown in Windows:

![Options](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/75539d54-ca9f-4c2a-a1aa-e3ffa65d84c8)

Only the "3D" shows in usage. I'm just comparing with for instance AI functions in Resolve which consistently work the GPUs at 90+%. Here is Resolve video render running:

![resolve load](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/cc3c0b94-d094-4ada-a792-57a2286bb511)
