### ISSUE TITLE
OpenVINO development for MacOS coming?

### ISSUE THREAD

**Issue by jschubert6** [intel/openvino-plugins-ai-audacity#195]
I have tried the 3 methods for installing OpenVINO for my Mac, and have had no success. I don't know how to do DOS on my Mac. Any chance someone is developing a OpenVINO plug-in specifically designed for Mac?

**Comment by invent71** [comment]
Would be excellent to have this working on Mac

**Comment by RyanMetcalfeInt8** [comment]
Hi @jschubert6, @invent71,

There is some good work being done by members of the community to enable this plugin on Mac. See here: https://github.com/intel/openvino-plugins-ai-audacity/issues/28

I'll close this one as a duplicate -- feel free to join the conversation in the other thread. Cheers!

**Comment by Celebrateportraits** [comment]
Same exact query. Curious when the Ai Plugins will be available for MacOS.  Tis a shame to have Audacity 3.5 without the Ai.

**Comment by dimako88** [comment]
Would be amazing to have a more straightforward solution. @eukarpov made a great job, but I could not run it (
