### ISSUE TITLE
Music separation

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#196]
Hello.
I've found strange issue. When I have separated music second time on Audacity using Music separation plugin, music isn't separated but instead strangely played.
To separate music properly again, I'll have to remove content of OpenWino cache folder.
Please, could You look on It?
I use computer with 64-bit Windows 10.
Thank You.
Marco Oros

**Comment by RyanMetcalfeInt8** [comment]
Hi @Giovani93, 

This is a known issue (#1). A fix is coming very soon in an updated patch release. Stay tuned.

Thanks,
Ryan
