### ISSUE TITLE
%1 Error?

### ISSUE THREAD

**Issue by MerrillSDA** [intel/openvino-plugins-ai-audacity#199]
I just downloaded the OpenVino files. Installation seemed to go well, but when I opened Audacity I got this error message:
Unable to load the "mod-openvino" module. Error: %1 is not a valid Win32 application

Windows 10

![Screenshot 2024-05-19 161124](https://github.com/intel/openvino-plugins-ai-audacity/assets/170270222/84ec153e-eca3-4ae0-a24b-f13f77865b08)

Any idea what I did wrong?

Merrill

**Comment by RyanMetcalfeInt8** [comment]
Hi Merrill,

Usually this error indicates that you've installed the plugins into a 32-bit Audacity installation. These plugins require the 64-bit version of Audacity -- can you double check?

Thanks,
Ryan

**Comment by MerrillSDA** [comment]
That was the problem. I reloaded Audacity at 64-bit and everything's working well.

Thank you so much!

**Comment by RyanMetcalfeInt8** [comment]
Glad you were able to get it working! Cheers!
