### ISSUE TITLE
Error: Failed to load shared library 'avformat-60.dll'

### ISSUE THREAD

**Issue by pauloaoki** [intel/openvino-plugins-ai-audacity#20]
21:10:11: Audacity 3.4.2
21:10:11: Error: Failed to load shared library 'avformat-60.dll' (error 126: Não foi possível encontrar o módulo especificado.)
21:10:11: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
21:10:13: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
21:10:13: Error: Failed to load shared library 'avformat-60.dll' (error 126: Não foi possível encontrar o módulo especificado.)
21:10:13: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll

Audacity Version: Audacity 3.4.2

The Build
Program build date:
Nov 16 2023
Commit Id:
9dd60f of Thu Nov 16 14:58:21 2023 +0300
Build type:
CMake Release build (debug level 1), 64 bits
Compiler:
MSVC 19.37.32825.00

**Comment by RyanMetcalfeInt8** [comment]
Hi @pauloaoki, this is not an issue with these plugins. This error message will show up in the log even if openvino plugins are not installed.

Thanks,
Ryan
