### ISSUE TITLE
Error sending data (12002) The operation timed out

### ISSUE THREAD

**Issue by oscartitolopez** [intel/openvino-plugins-ai-audacity#200]
I'm trying to Install Openvino and receive this error message: openvino installation error sending data (12002) The operation timed out
What can I do?

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/170275377/5db08526-4d67-4a39-a4f3-6e109ce9bef7)

**Comment by nonspacial** [comment]
Same problem here.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/abca0cfe-488d-4856-a978-7d58c775942f)

**Comment by RyanMetcalfeInt8** [comment]
Hi @oscartitolopez, @nonspacial -- what version of Windows are you using?

**Comment by RyanMetcalfeInt8** [comment]
Also, can you check if you have access to this, for example? 

https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main

**Comment by nonspacial** [comment]
Win 11

> Hi @oscartitolopez, @nonspacial -- what version of Windows are you using?

clean installed yesterday.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/082b856a-cec5-4ff7-985e-eec4d150361a)

**Comment by nonspacial** [comment]
> Also, can you check if you have access to this, for example?
> 
> https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main

This link opens the page...& lets me download the zips manually. using FF dev edition.

**Comment by RyanMetcalfeInt8** [comment]
hmm, strange... I don't know why the download is failing then from the installer. From the installer, does it appear to actually start downloading anything? Or does it just throw that error after sitting there for a bit with an empty progress bar?

And you're not behind a proxy or anything, right?

**Comment by nonspacial** [comment]
not even a prog bar dude... litrerally sits there and then throws the error... I use rainmeter and i'm seeing KBs of up nad down but that's it. and nothing in taskmanager network for the running installer

**Comment by nonspacial** [comment]
it will install under the (no models) option so it's just something in the fetch?

**Comment by nonspacial** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/cc25980f-2c93-49c6-a234-ddb61a54dc77)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/80ee6c8f-73d3-406b-9195-df8ae99f339c)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/636252a0-3d3b-4d02-8b1a-d687e6f5a4a5)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/ac8fcdb3-03dc-4b8c-bbf4-29904e95fec3)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/03b698b1-1d87-42cc-83f3-abcbf6b5e454)

if this helps?

**Comment by RyanMetcalfeInt8** [comment]
Thanks, yes it does help. 

>it will install under the (no models) option so it's just something in the fetch?

Right, the 'no models' option will basically just skip downloading / installing any of the models.

It's kind of pain, but as a workaround you can do the 'no models' option, and then *manually* populate an ```openvino-models``` directory that would sit in the Audacity folder (next to Audacity.exe, etc.).

We have instructions for this here (https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/windows/README.md#installing-the-openvino-models).

Obviously the point of having the installer do all of this is that it's kind of a pain to do it manually...

**Comment by nonspacial** [comment]
Cool... workaround in effect... I want the separation mainly so which zip is it from?

**Comment by RyanMetcalfeInt8** [comment]
Ah okay, then it's pretty easy.

Basically, create a folder called ```openvino-models```, and then go here (https://huggingface.co/Intel/demucs-openvino/tree/main) and download htdemucs_v4.xml & htdemucs_v4.bin, and put those in the folder that you created. Then move this folder to your ```Audacity``` folder (the one that holds Audacity.exe) -- and then you should be all set.

**Comment by nonspacial** [comment]
Possible thought to make the workaround easier for some... maybe put a select local files/folder option, so if you can't get the installer download to work, but can do the direct download... then u can still use the installer on those files/folder of files? folder might be better to be fair.

**Comment by nonspacial** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/4a899206-c02a-4f41-874f-511ff74f2505)

well that worked!

**Comment by RyanMetcalfeInt8** [comment]
Thanks for the suggestion -- I'll think about it... hopefully we'll just be able to get the installer downloads to be reliable.

Also, really glad you were able to get it running -- at least with music separation.

When you get a chance, could you just try 1 experiment for me? Can you choose just this one model and see if it downloads (uncheck all others)?
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/57b32cc3-ca2d-4a6f-a208-7b5f8d6a60d6)

This is the only model that doesn't download from huggingface.co, and just curious if that changes things..

**Comment by nonspacial** [comment]
ok 2 secs i'll try it 4 u rn... still downloading zips 
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/99dd447d-81c7-43f2-a8a6-be077999acbc)

**Comment by oscartitolopez** [comment]
> Hi @oscartitolopez, @nonspacial -- what version of Windows are you using?

Windows 11 Home, completely updated.

**Comment by oscartitolopez** [comment]
> > Also, can you check if you have access to this, for example?
> > https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main
> 
> This link opens the page...& lets me download the zips manually. using FF dev edition.

Me too...

**Comment by nonspacial** [comment]
> Thanks for the suggestion -- I'll think about it... hopefully we'll just be able to get the installer downloads to be reliable.
> 
> Also, really glad you were able to get it running -- at least with music separation.
> 
> When you get a chance, could you just try 1 experiment for me? Can you choose just this one model and see if it downloads (uncheck all others)? ![image](https://private-user-images.githubusercontent.com/107415876/331911816-57b32cc3-ca2d-4a6f-a208-7b5f8d6a60d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjUyMTUsIm5iZiI6MTcxNjE2NDkxNSwicGF0aCI6Ii8xMDc0MTU4NzYvMzMxOTExODE2LTU3YjMyY2MzLWNhMmQtNGE2Zi1hMjA4LTdiNWY4ZDZhNjBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMDI4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDA0MjJjMDZlYTc2ZjI1YTNiODVhZjA2N2E3MGEzNjc4ZWY0MzQxYWM3NGIxMTZmZTFjNGY2YzhjNGFjNmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FKnSnVkj102hXfQkuvuSjCoYDCm9YvWFwjP78JXWbAI)
> 
> This is the only model that doesn't download from huggingface.co, and just curious if that changes things..

Sorry man, same shit. about 2-3mins of nothing but the white screen, then the 12002 error. 

Also what's weird is the window cannot be selected or moved whilst it's "checking the internet?"

**Comment by RyanMetcalfeInt8** [comment]
> > Thanks for the suggestion -- I'll think about it... hopefully we'll just be able to get the installer downloads to be reliable.
> > Also, really glad you were able to get it running -- at least with music separation.
> > When you get a chance, could you just try 1 experiment for me? Can you choose just this one model and see if it downloads (uncheck all others)? ![image](https://private-user-images.githubusercontent.com/107415876/331911816-57b32cc3-ca2d-4a6f-a208-7b5f8d6a60d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjUyMTUsIm5iZiI6MTcxNjE2NDkxNSwicGF0aCI6Ii8xMDc0MTU4NzYvMzMxOTExODE2LTU3YjMyY2MzLWNhMmQtNGE2Zi1hMjA4LTdiNWY4ZDZhNjBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMDI4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDA0MjJjMDZlYTc2ZjI1YTNiODVhZjA2N2E3MGEzNjc4ZWY0MzQxYWM3NGIxMTZmZTFjNGY2YzhjNGFjNmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FKnSnVkj102hXfQkuvuSjCoYDCm9YvWFwjP78JXWbAI)
> > This is the only model that doesn't download from huggingface.co, and just curious if that changes things..
> 
> Sorry man, same shit. about 2-3mins of nothing but the white screen, then the 12002 error.
> 
> Also what's weird is the window cannot be selected or moved whilst it's "checking the internet?"
> 
> as soon as the error pops up it's immediately movable again.

Thank you for trying that! Very strange...

**Comment by RyanMetcalfeInt8** [comment]
Another quick experiment for you guys, can you open a powershell window in your download folder and try to run this?

```
Invoke-WebRequest https://huggingface.co/Intel/whisper.cpp-openvino-models/resolve/194efafbee09390bbf33f33d02d9856dacfdd162/ggml-base-models.zip -OutFile ggml-base-models.zip
```

It will essentially just download and save ggml-base-models.zip to the current folder. 

I know that the download seems to work from your browser, but curious if it would also work from the cmd-line like this. Thanks!

**Comment by nonspacial** [comment]
Hey man, sorry yesterday the work gig was way longer than it should've been and I left computing out of my day!

I'm running the command now and it's not doing much? PS is just blinking the cursor at me and my internet connection isn't anymore active than it normally would be... Gonna see if it times out or not. been running a few mins as it is though.

**Comment by nonspacial** [comment]
Oh it just started
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/b41fc773-34fd-41a6-a697-aa225b440b34)

**Comment by RyanMetcalfeInt8** [comment]
Thanks! So it seemed like it worked, after some long pause?

**Comment by nonspacial** [comment]
yep exactly, like 5 mins.

I don't know where the file actually went though? "-OutFile ggml-base-models.zip" has no folders leading it and it's not directly on C.

**Comment by nonspacial** [comment]
I don't know how relevant this is, maybe the other dude has something that makes it a valid thing to consider... I'm on Starlink: In France, but not rural, just bullshit ADSL to the house.

**Comment by RyanMetcalfeInt8** [comment]
Got it, hmm -- thanks for trying it out for me!

**Comment by oscartitolopez** [comment]
Does openvino work with an AMD Ryzen processor? Could that be my problem?

**Comment by nonspacial** [comment]
> Does openvino work with an AMD Ryzen processor? Could that be my problem?

i'm on an intel 9980xe so...

**Comment by oscartitolopez** [comment]
I already solved the problem very easily. I simply had to make sure the "openvino-models" folder had the proper read and write permissions. I did this by right clicking on the folder, selecting "Properties" and then the "Security" tab.

Anyways, thanks for your kind help! (And thanks to Google's Gemini AI)

**Comment by RyanMetcalfeInt8** [comment]
Hi @oscartitolopez,

Hmm, I'm not sure that I follow exactly what you did to resolve this issue. The error that you reported was triggered during download stage of the installer -- but this happens before anything is copied to the 'final' openvino-models folder (in Audacity folder, right? ), so I'm not really sure how changing the permissions of that folder could have resolved the download issue..

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
But I am glad to hear that you did get it working :smile:

**Comment by oscartitolopez** [comment]
I am not a computer expert. I just want to install openVINO.
Seeing that I got the message "Error sending data (12002)" I started doing a search, and that's why I turned to this chat.
I installed the program without downloading the models, because it was impossible. So I went to ChatGPT 4.0, CoPilot and Gemini and asked what I could do.
One of Gemini's recommendations was "_Check the permissions of the "openvino-models" folder: Make sure the "openvino-models" folder has the appropriate read and write permissions. You can do this by right-clicking on the folder, selecting " Properties" and then the "Security" tab._"
Then I went to the folder that I had created (openvino-models), I right-clicked, I went to 'properties', then 'security' and these two user names appeared: "ALL APPLICATION PACKAGES" and "ALL RESTRICTED APPLICATION PACKAGES"
Then I went to "Edit" to change the permissions and gave "Full control" to both user names.
Then I clicked OK and went to the installer and it started working without problems. I am currently downloading the models.

**Comment by oscartitolopez** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/170275377/94bc889f-c2ff-49da-b67b-fa76a255de4e)

**Comment by oscartitolopez** [comment]
I'm almost finished, I think...

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/170275377/b162cd4c-8b1f-4722-adbc-adbc83e23be8)

**Comment by RyanMetcalfeInt8** [comment]
> right so because audacity is installed by default into the Program Files directory it's protected! goddamn windows... I totally missed that could be the problem.

Hmm, but it actually downloads everything to a tmp directory first, and once everything is downloaded it will install the models into the destination (possibly protected) folder. This is why I don't understand why the permission should affect the download at all...

**Comment by oscartitolopez** [comment]
Don't ask me! @RyanMetcalfeInt8  

All I know is that it seems to be working fine (though taking a lot of time to download the models)

**Comment by nonspacial** [comment]
> Don't ask me! @RyanMetcalfeInt8
> 
> All I know is that it seems to be working fine (though taking a lot of time to download the models)

was it slow to start the download or instant?

**Comment by nonspacial** [comment]
answered my own question... installed to C:/Audacity and still same error... however I have another thought... on a fresh install there's no models folder to have permissions

**Comment by nonspacial** [comment]
with no editing of permissions and just the folder created... no go.

> ![image](https://private-user-images.githubusercontent.com/170275377/332579901-94bc889f-c2ff-49da-b67b-fa76a255de4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjU0MDcsIm5iZiI6MTcxNjMyNTEwNywicGF0aCI6Ii8xNzAyNzUzNzcvMzMyNTc5OTAxLTk0YmM4ODlmLWMyZmYtNDlkYS1iNjdiLWZhNzZhMjU1ZGU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQyMDU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDRhNDIzNTg5MzNkMGMwYjk4NzBkOWI2OWIyM2U5MjdjMTkwYTdlM2ZlOTI5MTJmYWE0ZjYyZTNmNmIwNGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0SSmC61hek8VPrl3qqNxty5JDKU0TnqiOkmG-rZkpzM)

I also do not have these same Groups in my properties on the direct to C version, but I do see them on the C:/ProgramFiles page

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/6969498/281f866c-b5db-4de6-988e-941bf86758eb)

**Comment by nonspacial** [comment]
& finally I have not had the same luck with changing those permissions and target either install... I gave every user/group full access and ran the installer on each and same shit different day for me.

I will try restarting comp later but it's no can do rn.

**Comment by oscartitolopez** [comment]
Working like a charmmm
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/170275377/3fa1ab1b-ea77-4573-9f74-94bad1743f99)
Thanks again to all.

**Comment by RyanMetcalfeInt8** [comment]
Perfect, glad it's working for both of you now!

**Comment by RyanMetcalfeInt8** [comment]
(well, I think @nonspacial had to download things manually.. so maybe I shouldn't say it's working)
