### ISSUE TITLE
OpenVINO not loading correctly...

### ISSUE THREAD

**Issue by vizcoman** [intel/openvino-plugins-ai-audacity#201]
Hello!.
I am running a windows 10 Home version 22H2 with a 64-bit operating system desktop audio workstation PC with an Intel Core i9-10850K CPU @ 3.60Ghz with 32GB of RAM and 3 SSD's. 
Installed Audacity v3.5.1 and OpenVINO v3.5.1-R2.1 but upon loading a song file and trying to generate music separation I always get a pop-up screen that does not recognize the music file type, nor does it include OpenVINO plugins as shown in the install tutorial videos.
Please see attached JPEG screenshot.

Could you please advice me on how to correct this for I have installed and uninstall Audacity and OpenVINO many times with the same problematic results.

Best Regards,
Arturo Manfredi
![OpenVINO not loading correctly](https://github.com/intel/openvino-plugins-ai-audacity/assets/170341154/8383b619-03ec-4471-9234-9acbfa9a808e)

**Comment by RyanMetcalfeInt8** [comment]
Hi @vizcoman,

You attached a screenshot with 'Music Generation' dialog box, but are talking about Music Separation. But then you also mention an error pop up about music file type, which I don't see. Can you attach some better screenshots? What tutorial video are you referring to?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
By the way, 'Music Separation' is found in 'Effects' menu.. if that helps.

**Comment by vizcoman** [comment]
Hello Ryan,
Thank you for your quick response.
I just reinstalled Audacity and OpenVINO and my issue has been resolved!. I'm not sure what I did differently.
Best Regards,
Arturo Manfredi


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by vizcoman** [comment]
Hello again Ryan
I have resolved my issue. It seems that I did not load OpenVINO correctly.
Thank you once again!
Regards.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by RyanMetcalfeInt8** [comment]
Ah okay, great!
