### ISSUE TITLE
How to separate music fast by cpu? 

### ISSUE THREAD

**Issue by SplendidPiePizza** [intel/openvino-plugins-ai-audacity#205]
My device is only cpu, cause my GPU is Microsoft basic display adapter and I need help.

**Comment by RyanMetcalfeInt8** [comment]
Hi @SplendidPiePizza,

I'm not sure what your question is / what you are requesting. If you select 'CPU' from the drop-down list for Music Separation, then it will use CPU. 

Thanks,
Ryan

**Comment by SplendidPiePizza** [comment]
> Hi @SplendidPiePizza,
> 
> I'm not sure what your question is / what you are requesting. If you select 'CPU' from the drop-down list for Music Separation, then it will use CPU. 
> 
> Thanks,
> Ryan

What I mean is, How to make music separation faster by cpu? Is it openCL?

**Comment by RyanMetcalfeInt8** [comment]
There's not really anything that you can simply install that would make it somehow run faster.. if that is what you mean. You would need to replace the OpenVINO-based C++ pipeline with something else.
