### ISSUE TITLE
MusicGen models not showing up on Audacity UI

### ISSUE THREAD

**Issue by sponsfreixes** [intel/openvino-plugins-ai-audacity#207]
I have installed the module and the MusingGen models following https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/linux/README.md

I built Audacity 3.5.1-alpha-20240520. The OpenVino module seems to be correctly installed and enabled:

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/1104773/8bf2453c-a1d3-4269-bc9b-2179e6e1ba3e)

And I put the models on the right place:

```bash
sergi@eBLD:~/Downloads$ ls -lh /usr/local/lib/openvino-models/musicgen/
total 8.0K
drwxr-xr-x 2 root root 4.0K May 22 19:46 mono
drwxr-xr-x 2 root root 4.0K May 22 19:46 stereo
sergi@eBLD:~/Downloads$ ls -lh /usr/local/lib/openvino-models/musicgen/stereo/
total 1.3G
-rw-r--r-- 1 root root  33M May 22 19:46 embed_tokens.bin
-rw-r--r-- 1 root root  29K May 22 19:46 embed_tokens.xml
-rw-r--r-- 1 root root 3.1M May 22 19:46 enc_to_dec_proj.bin
-rw-r--r-- 1 root root 2.8K May 22 19:46 enc_to_dec_proj.xml
-rw-r--r-- 1 root root 193M May 22 19:46 initial_cross_attn_kv_producer.bin
-rw-r--r-- 1 root root 146K May 22 19:46 initial_cross_attn_kv_producer.xml
-rw-r--r-- 1 root root  33M May 22 19:46 lm_heads.bin
-rw-r--r-- 1 root root  22K May 22 19:46 lm_heads.xml
-rw-r--r-- 1 root root 673M May 22 19:46 musicgen_decoder_combined_weights.bin
-rw-r--r-- 1 root root 338M May 22 19:46 musicgen_decoder_combined_weights_int8.bin
-rw-r--r-- 1 root root 2.5M May 22 19:46 musicgen_decoder_static0_10s.xml
-rw-r--r-- 1 root root 2.5M May 22 19:46 musicgen_decoder_static0_5s.xml
-rw-r--r-- 1 root root 3.1M May 22 19:46 musicgen_decoder_static_batch1_int8.xml
-rw-r--r-- 1 root root 2.5M May 22 19:46 musicgen_decoder_static_batch1.xml
-rw-r--r-- 1 root root 3.1M May 22 19:46 musicgen_decoder_static_int8.xml
-rw-r--r-- 1 root root 2.5M May 22 19:46 musicgen_decoder_static.xml
-rw-r--r-- 1 root root 8.0M May 22 19:46 sinusoidal_positional_embedding_weights_2048_1024.raw
```

But on the Music Generation dialog, the model selection dropdown does not show any model:

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/1104773/53991d22-99a3-477a-b81b-c72c93d9f304)

And on the logs I see:

> 21:05:29: OpenVINO Music Generation V2 has no models installed.

Am I missing something?

**Comment by RyanMetcalfeInt8** [comment]
Hi @sponsfreixes,

It looks like you may missing some files in ```openvino-models/musicgen/```, which would have been populated from this step:
```
# unzip the 'base' set of models (like the EnCodec, tokenizer, etc.) into musicgen folder
unzip musicgen-static-openvino/musicgen_small_enc_dec_tok_openvino_models.zip -d openvino-models/musicgen
```

For example, that folder should have these contents:
<img width="582" alt="image" src="https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/92ccb3ca-7f17-47d1-b1a8-9442014924ab">

Thanks,
Ryan

**Comment by sponsfreixes** [comment]
Thanks! It seems that I missed that specific unzip command, my bad!
