### ISSUE TITLE
[Audacity] - My Mod-openvino got Fail

### ISSUE THREAD

**Issue by Renebrf** [intel/openvino-plugins-ai-audacity#21]
Hello friends, I tried to install Mod-Envino as a video tutorial, but after performing the installation, when opening Audacity appears a message saying that the mod Envino

Unable to load the "mod-openvino" module.
Error: Could not find the specified module.

Can someone help me? I used the same file here from Githhub, reinstalled Audacity and installed again, did all the installation process of the mod, and always appears this error.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Renebrf,

Which version of Windows are you using? Sometimes this issue indicated that may need to install MSVC redistributable package: https://aka.ms/vs/17/release/vc_redist.x64.exe

Can you give that a shot and let me know?

Thanks,
Ryan

**Comment by Renebrf** [comment]
I installed this C++ program, but it still keeps giving the same error.. :(
my windows is 11
![auda](https://github.com/intel/openvino-plugins-ai-audacity/assets/156235661/39403cc3-4d68-414b-a541-69df58bd4ca1)

**Comment by Renebrf** [comment]
It keeps giving "failure" :(

 I made a diagnosis through Audacity, this message appeared:

09:51:58: Audacity 3.4.2
09:51:58: Error: Failed to load shared library 'avformat-60.dll' (error 126: Could not find the specified module.)
09:51:58: Error: Failed to load shared library 'avformat-59.dll' (error 126: Could not find the specified module.)
09:51:58: Error: Failed to load shared library 'avformat-58.dll' (error 126: Could not find the specified module.)
09:51:58: Error: Failed to load shared library 'avformat-57.dll' (error 126: Could not find the specified module.)
09:51:58: Error: Failed to load shared library 'avformat-55.dll' (error 126: Could not find the specified module.)
09:52:14: Unable to load the module "C:\Program Files\Audacity\modules\mod-openvino.dll". Error: Could not find the specified module.
09:52:16: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
09:52:16: Error: Failed to load shared library 'avformat-60.dll' (error 126: Could not find the specified module.)
09:52:16: Error: Failed to load shared library 'avformat-59.dll' (error 126: Could not find the specified module.)
09:52:16: Error: Failed to load shared library 'avformat-58.dll' (error 126: Could not find the specified module.)
09:52:16: Error: Failed to load shared library 'avformat-57.dll' (error 126: Could not find the specified module.)
09:52:16: Error: Failed to load shared library 'avformat-55.dll' (error 126: Could not find the specified module.)

**Comment by Renebrf** [comment]
I have a question, I saw a person commenting on FFMPEG, I already had FFMPEG installed on my computer, can this be the problem?

**Comment by RyanMetcalfeInt8** [comment]
Hi @Renebrf,

>  I saw a person commenting on FFMPEG, I already had FFMPEG installed on my computer, can this be the problem?

No, this shouldn't affect anything

> 09:52:14: Unable to load the module "C:\Program Files\Audacity\modules\mod-openvino.dll". Error: Could not find the specified module.

I wish Windows was more specific about what module it couldn't find, but this usually means that there is some DLL dependency that is not met. 

Something that I typically use to debug DLL load issues is: https://github.com/lucasg/Dependencies/releases/tag/v1.11.1

For example, if you download [Dependencies_x64_Release.zip](https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip)

And then ppen a cmd.exe (Command Prompt) window, and do:
```
cd "C:\Program Files\Audacity"

set Path=C:\Program Files\Audacity;%Path%

%userprofile%\Downloads\Dependencies_x64_Release\DependenciesGUI.exe modules\mod-openvino.dll
```

This should open up a window that looks like this:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/a1ac73c3-5890-4e9b-ae1d-81a99198886a)


Could you send me a screenshot of that?

**Comment by afonsoajorge** [comment]
i have the same problem and i did the steps

**Comment by afonsoajorge** [comment]
![Captura de tela 2024-01-11 102258](https://github.com/intel/openvino-plugins-ai-audacity/assets/14251558/c9488907-d1c0-4864-88e2-ea0bdfb09590)
![Captura de tela 2024-01-11 102258](https://github.com/intel/openvino-plugins-ai-audacity/assets/14251558/f7c97d5f-2525-4b1b-82f4-a8d5e994a78e)

**Comment by RyanMetcalfeInt8** [comment]
> i have the same problem and i did the steps

Right, these steps won't solve the problem. They are just to diagnose what might be going wrong.

If you start 'expanding' the individual DLL's (click the little arrow next to the DLL name), is there anything that shows up in with a red symbol?

**Comment by RyanMetcalfeInt8** [comment]
By the way, in Audacity preferences, you may need to change 'mod-openvino' back to 'Enabled' if it's set to 'Failed', and then close and re-open Audacity.

**Comment by afonsoajorge** [comment]
![Captura de tela 2024-01-11 104710](https://github.com/intel/openvino-plugins-ai-audacity/assets/14251558/e3accd91-06e7-4d6e-9aaa-189de3650638)
![Captura de tela 2024-01-11 104718](https://github.com/intel/openvino-plugins-ai-audacity/assets/14251558/d4a9a9a6-b3ef-470b-a542-cad3647c2989)
![Captura de tela 2024-01-11 104738](https://github.com/intel/openvino-plugins-ai-audacity/assets/14251558/fde142b9-3af8-40cd-b1fb-e69b9f101173)

**Comment by RyanMetcalfeInt8** [comment]
Thanks -- I get the same thing for ext-ms-win-oobe-query-l1-1-0.dll, so that doesn't appear to be an issue. 

So everything under openvino.dll, whisper.dll, and torch_cpu.dll look okay?

**Comment by RyanMetcalfeInt8** [comment]
Hmm, I'm not too sure what is going wrong in your case. All of the dependencies seems to be getting resolved properly, and the few DLL's that it is showing as missing also seem to show missing for me (even in working case).

Which version of Windows are you using?

**Comment by afonsoajorge** [comment]
w11, i'll try it on w10, thank you very much

**Comment by afonsoajorge** [comment]
same error on notebook with win10, i tested another computer with very different configurations same error, i will install a previous version of audacity and test it

**Comment by afonsoajorge** [comment]
I managed to solve it, it was my mistake when unzipping the openvino-models folder it was inside another and I didn't see it. I put the right folder and everything was fine, thank you very much for your help

**Comment by RyanMetcalfeInt8** [comment]
> I managed to solve it, it was my mistake when unzipping the openvino-models folder it was inside another and I didn't see it

Interesting. So you only fixed the location of openvino-models folder, and then the plugin started loading? This is odd to me because the presence of this folder shouldn't affect anything related to DLL loading.

**Comment by Renebrf** [comment]
> > i will install a previous version of audacity and test it
> 
> This plugin is only compatible with latest version of Audacity (3.4.2).
> 
> Can you give more details about the hardware configuration for the platforms that failed? Like CPU version, etc.

Core i5 9300H

**Comment by afonsoajorge** [comment]
I just did that, put the folder in the right place and it worked normally

**Comment by Renebrf** [comment]
> I just did that, put the folder in the right place and it worked normally

![models](https://github.com/intel/openvino-plugins-ai-audacity/assets/156235661/066496ae-051d-4250-b7ac-427d77d0e680)

this one?

**Comment by afonsoajorge** [comment]
in my case, inside this folder there was another folder with the same name

**Comment by SoftDavix** [comment]
[log.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/13930130/log.txt)

**Comment by SoftDavix** [comment]
@RyanMetcalfeInt8  I have the same problem but in my case, I have everything installed correctly, I still cannot find the dll.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Renebrf , @SoftDavix,

It would be helpful to get some results of the experiment described here: https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1890998932


Thanks!
Ryan
