### ISSUE TITLE
Crash when using GPU

### ISSUE THREAD

**Issue by 1manfactory** [intel/openvino-plugins-ai-audacity#211]
Thanks for this great plugin. I hope you will be able to fix this error. I am looking forward.

All 4 functions seam to work very well. Except for the fact that the plugins fail when working with my GPU. They only work with CPU.

F.Y.I.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/7351b65a-af3f-4524-9572-8a405aec41a3)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/cb6328bd-b97d-470b-be97-eb0177302973)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/a20f396f-a23a-4cb3-9364-eff7194f80a2)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/aa9012f7-301a-4c0e-8b69-7b932b2982e3)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/052d40cc-e77a-4f69-aa41-45df22a6a4a1)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/232674/820d8055-cd3c-405c-a5eb-ac7218b49145)

**Comment by RyanMetcalfeInt8** [comment]
Hi @1manfactory,

Your 11th Gen i7 should have an integrated GPU, does it work with that? The GPU that you show in the screenshot above is an NVidia GPU, which is not well-supported by OpenVINO.

Thanks,
Ryan

**Comment by HyperUpscale** [comment]
I suspect the latest nvidia driver 555.85, as I nave the same error after the Nvidia driver update...  
But I am not 100% sure about that :)
