### ISSUE TITLE
"unable to load the mod openvino module"

### ISSUE THREAD

**Issue by whittyfnf** [intel/openvino-plugins-ai-audacity#217]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/112743991/b25f3d8f-3dbb-4a05-81e4-d081044486de)
how do i fix this? i have tried everything

**Comment by whittyfnf** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/112743991/a47b27ee-2022-473a-860f-147650387f20)
it is always set to failed automatically everytime i re open audacity and it just simply doesnt show up in generate or effect

**Comment by RyanMetcalfeInt8** [comment]
Hi @whittyfnf,

What version of these plugins have you installed? What version of Audacity are you using?
