### ISSUE TITLE
Ubuntu 24.04 LTS unsupported OS

### ISSUE THREAD

**Issue by Leoo97** [intel/openvino-plugins-ai-audacity#218]
I know that Ubuntu 24.04 LTS is new, the question for me it's just if there is a date about when it will be supported as OS for the openvino mod :(

**Comment by RyanMetcalfeInt8** [comment]
Hi @Leoo97,

There isn't really any date, but it will come down when underlying dependencies (like OpenVINO, Audacity, etc.) are well-supported on 24.04. You can always try to follow instructions anyway -- I'm not sure where things would go wrong, but I'm guessing it will require building more packages from scratch (such as OpenVINO itself).

**Comment by Leoo97** [comment]
When I try to install dependencies using install_openvino_dependencies.sh the konsole said that:
Unsupported OS: Ubuntu 24.04

**Comment by gblong1** [comment]
Hi @Leoo97 - You can get around this by doing the following:

```
sed "s/ubuntu22.04/ubuntu24.04/g" install_openvino_dependancies.sh > tmp
chmod +x tmp
sudo -E ./tmp
```

**Comment by Leoo97** [comment]
@gblong1 thank you very much!
