### ISSUE TITLE
 In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed

### ISSUE THREAD

**Issue by fperloff** [intel/openvino-plugins-ai-audacity#22]
16:04:03: Audacity 3.4.2
16:04:03: FFmpeg libraries loaded successfully from: F:\Users\Fred\Downloads\ffmpeg-6.1.1-full_build-shared\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
16:04:06: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
16:04:07: FFmpeg libraries loaded successfully from: F:\Users\Fred\Downloads\ffmpeg-6.1.1-full_build-shared\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
16:04:16: Loaded 74 string 1.666016 Kb in size
16:04:16: Project loaded in 29 ms
16:04:28: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
16:04:31: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed
16:04:32: Operation 'OpenVINO Whisper Transcription' took 2.808000 seconds. Poll was called 1402 times and took 0.221053 seconds. Yield was called 47 times and took 0.122712 seconds.
16:04:30: Error: whisper_init_from_file_with_params(D:\Program Files\Audacity\openvino-models\ggml-base.bin, ...) failed

Windows 11 Pro 10.0.22621
Audacity 3.4.2 x64 - build Nov 16 2023

**Comment by RyanMetcalfeInt8** [comment]
Hi @fperloff,

Can you double check that this file is present? 

```D:\Program Files\Audacity\openvino-models\ggml-base.bin```

Thanks,
Ryan

**Comment by fperloff** [comment]
Nope - openvino-modules directory is empty 😵 Guess I'm missing 
something important!

How do I install the models?

Thanks!
Fred

------ Original Message ------
From "Ryan Metcalfe" ***@***.***>
To "intel/openvino-plugins-ai-audacity" 
***@***.***>
Cc "fperloff" ***@***.***>; "Mention" ***@***.***>
Date 1/10/2024 4:16:56 PM
Subject Re: [intel/openvino-plugins-ai-audacity] In Whisper 
Transcription Effect, exception: whisper.cpp context creation / 
initialization failed (Issue #22)

**Comment by RyanMetcalfeInt8** [comment]
Hi Fred,

If the openvino-models directory was there, it seems like you at least attempted to follow instructions / video from here:
https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.4.2-R1

I would recommend to re-do the step where you download ```openvino-models.zip```, and then copy the contents into the Audacity folder -- as is shown in the video. 

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Awesome, glad it works now! 

Let us know if you have any other issues.

Cheers!
