### ISSUE TITLE
not showing in Audacity menu

### ISSUE THREAD

**Issue by concerro** [intel/openvino-plugins-ai-audacity#221]
I clicked on"[audacity-win-v3.5.1-R2.2-64bit-OpenVINO-AI-Plugins.exe](https://github.com/intel/openvino-plugins-ai-audacity/releases/download/v3.5.1-R2.2/audacity-win-v3.5.1-R2.2-64bit-OpenVINO-AI-Plugins.exe)"

It downloaded to my computer. I installed it. 

I've restarted Audible more than once, however when I go to "generate" in the audible menu it's not there. 

On Youtube I saw tutorials that said to download two zip files, but I don't see those zip files with the current version if Openvino so I figured I only needed the ".exe" file for the latest version of Openvino.

PS: I never downloaded the previous versions. I do have the most up to date version of Audacity (Audacity 3.5.1)

**Comment by TastyToast000** [comment]
Are you sure you selected version 3.5.1 in the installer?

**Comment by RyanMetcalfeInt8** [comment]
Did you enable ```mod-openvino``` under Preferences -> Modules?

**Comment by concerro** [comment]
> Are you sure you selected version 3.5.1 in the installer?

Yes.  The version number is in the title.

**Comment by concerro** [comment]
> Did you enable `mod-openvino` under Preferences -> Modules?

Thanks. That's what I needed to do.

**Comment by HyperUpscale** [comment]
After the installation of the plugins you need to ENABLE the MODULE from Edit - Preferences - Modules - mod-openvino

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/126105457/837aa1a9-597b-42a5-b916-4fb7407c3fdc)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/126105457/9185c31d-31bf-4c81-803a-8f671bfaa235)


### I am not sure why this is not stated in the installation instructions...

**Comment by RyanMetcalfeInt8** [comment]
> I am not sure why this is not stated in the installation instructions...

It is. 

At end of installation, it shows this:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/1c80da6f-75f6-400b-8cac-94f3186d289f)
