### ISSUE TITLE
How can I change for Audacity 3.5.1-Alpha to Audacity 3.5.1

### ISSUE THREAD

**Issue by hal8kb** [intel/openvino-plugins-ai-audacity#229]
This is probably a stupid question, or perhaps I cannot navigate github.

Im using Ubuntu 22.04 and have a working audacity but when audacity is launched it tells me to get the official release.
If i go help, about audacity I'm running:

Audacity 3.5.1-alpha-20240613

When I compiled audacity with the instructions below:
```
# clone Audacity
git clone https://github.com/audacity/audacity.git

# Optional: You may want to check out specific tag here, such as Audacity-3.4.2
# If so, replace <Audacity_Tag> in following command with tag.
cd audacity
git checkout <Audacity_Tag>
cd ..
```
I substituted  Audacity-3.5.1    in the <Audacity_Tag>

I can not find any way round to upgrade from alpha to the stable release version 3.5.1

Thanks in advance.

**Comment by RyanMetcalfeInt8** [comment]
Hi @hal8kb,

During the cmake step for audacity, add ```-DAUDACITY_BUILD_LEVEL=2```. So, 
```
# Run cmake (grab a coffee & a snack... this takes a while)
cmake -G "Unix Makefiles" ../audacity -DCMAKE_BUILD_TYPE=Release -DAUDACITY_BUILD_LEVEL=2
```

This will make it so that the Audacity version is ```Audacity 3.5.1```, instead of ```Audacity 3.5.1-alpha-20240613```
