### ISSUE TITLE
Error In Music Generation

### ISSUE THREAD

**Issue by Dog-1Superstar** [intel/openvino-plugins-ai-audacity#23]
hi good night, i'm having a problem when it comes to generating the songs, when it starts generating it kind of gives an error over time then i'm checking the log and i don't know what's going wrong, sorry for my bad english i'm brazilian

![Log](https://github.com/intel/openvino-plugins-ai-audacity/assets/156480883/ef3cdcc3-8b08-4e5c-9560-bde08b24de81)

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dog-1Superstar, 

Could you give me some details about your PC setup (like Windows version, CPU / GPU configuration, amount of RAM installed, etc.).

From the log, it looks like the GPU device tried to allocate ~500 MB of device memory, and failed.  I'm not sure from the log if this refers to GPU device memory (i.e. VRAM), or CPU system memory.

As a (potential) workaround -- In the Music Generation settings, on the right side you should see a bunch of drop-down lists -- some of them are probably set to 'GPU'. Try to change these to 'CPU' and try again.

Hope it helps!

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dog-1Superstar,

Were you able to get this working by switching GPU to CPU?

Thanks!
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dog-1Superstar,

I'll close this for now, but let me know if you are still having issues and I can re-open it.
