### ISSUE TITLE
I'm not seeing the Vino effects

### ISSUE THREAD

**Issue by 1GDEXTER** [intel/openvino-plugins-ai-audacity#232]
Hey there,

I installed the Open Vino Plugin [v3.5.1-R2.2]. The instalation went fine, without errors. But I don't see the plugins in Audacity, wheather in the activated, nor the deactivated category. I reinstalled it multiple times and deleted the temp files, but it didn't work. 
Do you have any suggestions?

Thanks a lot!!

**Comment by oxidian24** [comment]
Hello, did you downloaded the models? Are you speaking about Windows version?
What plugins you don't see? What plugins you installed? For linux there is a script to install them correctly. I have my own version, but mine is not official and was not tested by the programmers. From OpenVino programmer I got this link:
https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main

**Comment by 1GDEXTER** [comment]
Thx for trying to help me. But it seems like this tool isn't supported by a AMD CPU.

**Comment by oxidian24** [comment]
I don't think this is the reason why you don't see the openvino plugin.
So what did you do? You added the specific lines to cmakelists.txt and
compiled and copied the .so files to audacity/modules/openvino and then you activated the model, write?
I think then Intel simply has no reason to speak about AMD in the guide. Until specifically named that this CPUs are not supported we should not be worried.

**Comment by RyanMetcalfeInt8** [comment]
Hi @1GDEXTER,

Did you go to Preferences->Modules and change 'mod-openvino' to 'Enabled'?

**Comment by 1GDEXTER** [comment]
> I don't think this is the reason why you don't see the openvino plugin. So what did you do? You added the specific lines to cmakelists.txt and compiled and copied the .so files to audacity/modules/openvino and then you activated the model, write? I think that Intel simply has no reason to speak about AMD in the guide. Until specifically named that this CPUs are not supported we should not be worried.

I didn't compile anything. (Sorry, I'm totally new and noobish when it comes to that stuff). 

I only downloaded the .exe and installed it into the Audacity direction. After that I started Audacity and tried to find the Plugin in the Extentions section, but I couldn't find it. Whether in the activated nor the deactivated section. I thought that would be it, but obviously I missed something.

**Comment by 1GDEXTER** [comment]
But I saw this in the compatibility section, thats why I'm worried.
![2024-06-21_20h18_17](https://github.com/intel/openvino-plugins-ai-audacity/assets/172989986/faae62a5-6862-4dbd-9c22-06eb5d21b63f)

**Comment by 1GDEXTER** [comment]
> But I saw this in the compatibility section, thats why I'm worried. ![2024-06-21_20h18_17](https://private-user-images.githubusercontent.com/172989986/341855134-faae62a5-6862-4dbd-9c22-06eb5d21b63f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5OTQ0MDMsIm5iZiI6MTcxODk5NDEwMywicGF0aCI6Ii8xNzI5ODk5ODYvMzQxODU1MTM0LWZhYWU2MmE1LTY4NjItNGRiZC05YzIyLTA2ZWI1ZDIxYjYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxODIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWUxNGMzZGZmM2VhOWFiMmMwZDgwNDhlN2M4YjkyYjQzYTdjOGYyNGEyNmFiOGQyNTUyMDBhNzBjMmU2Nzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VCsFjvEz7pqoW6_eyi42ek3kLSRLNVBD15BKRFxbVzA)

I got an AMD R5 5500 btw.

**Comment by oxidian24** [comment]
I understand now. I am using linux so I had to compile the Audacity from source code with OpenVino (also compiled) and I don't have this problem. So if you installed the plugin on Windows, you still need to download the models which can take 3GB-16GB depending on how much models you download. The models are in .zip archive usually.

**Comment by RyanMetcalfeInt8** [comment]
For Windows, there is an installer which takes care of downloading the models and putting them in the right place (i.e. populating the openvino-models directory). The problem that @1GDEXTER is seeing would not be related to having the models downloaded, as the AI effects themselves should show up inside of Audacity regardless of whether the models are present.

**Comment by 1GDEXTER** [comment]
> For Windows, there is an installer which takes care of downloading the models and putting them in the right place (i.e. populating the openvino-models directory). The problem that @1GDEXTER is seeing would not be related to having the models downloaded, as the AI effects themselves should show up inside of Audacity regardless of whether the models are present, as long as the ```mod-openvino``` module has been enabled in Preferences->Modules.

Exactly, I downloaded the installer but I don't see the modules.

**Comment by 1GDEXTER** [comment]
> I understand now. I am using linux so I had to compile the Audacity from source code with OpenVino (also compiled) and I don't have this problem. So if you installed the plugin on Windows, you still need to download the models which can take 3GB-16GB depending on how much models you download. The models are in .zip archive usually.

For my understanding, I downloaded the models by the .exe. I had to decide which ones I wanted to download and I did so. But I still can't see the plugins in the extensions section, to enable it.

**Comment by RyanMetcalfeInt8** [comment]
> For my understanding, I downloaded the models by the .exe. I had to decide which ones I wanted to download and I did so. But I still can't see the plugins in the extensions section, to enable it.

Hmm, what do you mean by the 'extensions' section? Do you mean in Edit->Preferences->Modules? Is there an option for ```mod-openvino``` here?

**Comment by 1GDEXTER** [comment]
> > For my understanding, I downloaded the models by the .exe. I had to decide which ones I wanted to download and I did so. But I still can't see the plugins in the extensions section, to enable it.
> 
> Hmm, what do you mean by the 'extensions' section? Do you mean in Edit->Preferences->Modules? Is there an option for ```mod-openvino``` here?

I have the German version, so I don't know exactly what's the wording, but I think we talk about the same setting.

**Comment by 1GDEXTER** [comment]
> > For my understanding, I downloaded the models by the .exe. I had to decide which ones I wanted to download and I did so. But I still can't see the plugins in the extensions section, to enable it.
> 
> Hmm, what do you mean by the 'extensions' section? Do you mean in Edit->Preferences->Modules? Is there an option for `mod-openvino` here?

I found the problem. I actually was in the wrong extension. 
Tools->extension management.

In Edit->Preferences->Modules I found the to activating stuff.

Much thanks!!!
