### ISSUE TITLE
qustions about download size

### ISSUE THREAD

**Issue by oxidian24** [intel/openvino-plugins-ai-audacity#233]
Hello,
I just got some problems because I hadn't enough space on my disk when I tried to clone the repository of the Whisper files. I deleted the git/lfs files because I had no space on root and home partition. Maybe it was a mistake, I thought it was completed.

~/OpenVino/openvino-models/whisper.cpp-openvino-models$ ls -hC1 --size
total 1,3G
164M ggml-base-models.zip
581M ggml-small.en-tdrz-models.zip
583M ggml-small-models.zip

It seems like you are missing important section: HW requirements 1) for download 2) the expected size of the libraries.

I understand that the size change can change and grow after some time, but just to have an idea. 5 minutes to edit the readme.

It seems, like there is at least 6GB needed to clone + the library takes about 1.4GB of the space (but it was interrupted because no disk space ... So how much should I expect? 12GB to download?  ).
It would be better if user can download a zip file, but I couldn't find out how to do it. I would appreciate that. Please. I have seen YT tutorial for Windows user and I know he could download the zip alone. Much easier. This took so much time and I though that the process has been stopped so I interupted it when displayed 100%.

Also how much RAM will we need, and what is minumal CPU performance?
Is GPU needed? Maybe all this installation was just waste of time?

Also: Are the modules same for Windows and linux? It seems to be logical that should be. But still I didn't find the zip files to download.

**Comment by RyanMetcalfeInt8** [comment]
Hi @oxidian24,

If you go to the hugging face repo with a browser, you can see the size of each zip:
https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main

You can also download them individually using the download button to the right of the 'LFS' symbol.

Note that you don't need to download all of the models. Each zip provides a different variant of the whisper model (base, small, large-v1) in various sizes. The bigger the model, the more accurate the transcriptions / translations will be -- but will require more RAM and will take longer. 

>  Are the modules same for Windows and linux? 

Yes.

> 5 minutes to edit the readme.

Which README are you referring to?

**Comment by oxidian24** [comment]
Thank you for the link. I must download the zips directly I have no space for lfs files. lfs file are like 40.3 GB or more...

I refer to this guide...

https://github.com/intel/openvino-plugins-ai-audacity/tree/43de3af6087480ab2030404aba3f122fafa9bd73/doc/build_doc/linux

This is the guide I follow.

I found the openvino min. req. but they don't mention RAM and disk space. I have very old notebook CPU dual core intel Celeron, maybe it won't work on runtime... But I can install linux on newer PC with AMD CPU for any case, that one is 4 core, 8 threads.

**Comment by oxidian24** [comment]
Regarding the models
ggml-large-v1-models.zip
ggml-large-v2-models.zip
ggml-large-v3-models.zip
I don't need them all, right? Only the latest version ggml-large-v3-models.zip I suppose.

**Comment by RyanMetcalfeInt8** [comment]
> Regarding the models ggml-large-v1-models.zip ggml-large-v2-models.zip ggml-large-v3-models.zip I don't need them all, right? Only the latest version ggml-large-v3-models.zip I suppose.

Correct, if you want highest quality transcription, I would choose either V2 or V3 -- but you only need one.

And in general, you don't even need any of the large models. You can try with a smaller model (like 'base', which sounds like it may be more appropriate given your older system), and increase from there if you don't find transcription quality sufficient.

**Comment by oxidian24** [comment]
So I have downloaded all the archives and installed them in the /usr/local/lib/openvino-models folder.
If I have the directory structure correct ... like ... im not sure here: musicgen/mono , musicgen/stereo,
the Audacity 3.5.1 alpha, which is the version you suggested to me in the link, should open the OpenVino plugins. But instead of it Audacity crashed. There is no data in the log. I would like to know how to debug this or to find the error.

I also offer my installation script which is full control, equipped with logging and mechanism to continue in the interrupted installation (Except the gits ...). Yeah, it is long and it needs someone make final check of the correct installation, i.e the paths. See the code here:
https://github.com/intel/openvino-plugins-ai-audacity/issues/231

**Comment by RyanMetcalfeInt8** [comment]
> im not sure here: musicgen/mono , musicgen/stereo,

The directory structure should look like:
openvino-models/musicgen (a bunch of 'common' stuff here):
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/531690ec-d3c5-4c10-8f39-9ccbed48c363)

openvino-models/musicgen/mono ( a bunch of 'mono' specific stuff here):
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/8a55075d-85e5-485c-8382-8f8a079bba2a)

openvino-models/musicgen/stereo (and a bunch of stereo specific stuff here, no picture).

> the Audacity 3.5.1 alpha, which is the version you suggested to me in the link, should open the OpenVino plugins. But instead of it Audacity crashed.

Hmm, does Audacity crash only after enabling the plugin in Preferences->Modules?

**Comment by oxidian24** [comment]
Yes. Audacity crashes after I enable the plugin in Pref. modules.
Is there any way how I could try to debug it in Mint 21.3? I have Visual Code Studio with C/C++ installed but have no idea how to do that. I don't see any proper project for it.

**Comment by oxidian24** [comment]
qustions about download size and directory structure were answered so I close this issue

**Comment by oxidian24** [comment]
files sizes and directory information solved.

**Comment by oxidian24** [comment]
files sizes and directory information solved.
