### ISSUE TITLE
Audacity.exe problems with dll

### ISSUE THREAD

**Issue by Dylan12347** [intel/openvino-plugins-ai-audacity#241]
Hello, 
The problem I am having is that Audacity is not complying with the actual mod. I have followed the debuging DLL page and now have now found this. Can I have some help please?

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dylan12347,

>  I have followed the debuging DLL page and now have now found this

Did you intend to post a screenshot?

**Comment by RyanMetcalfeInt8** [comment]
@Dylan12347 ?
