### ISSUE TITLE
How to install these tools for a newbie

### ISSUE THREAD

**Issue by msualumni33** [intel/openvino-plugins-ai-audacity#244]
I am so confused. Since Audacity is now at 3.5.1 on a new install, how do I cleanly install these tools. There is an installer, but do I still need to copy all the files from the zip files into the Audacity folder myself, and then run the installer? Do I need to run the installer for each patch? What about this tar file I see?

Can anyone point me to a video on how to download Audacity (that a newbie can understand) and then properly download AI Tools.I am doing something wrong. I am using Windows. 

Thanks

**Comment by RyanMetcalfeInt8** [comment]
Hi @msualumni33,

For the releases that provide an installer, you only need to run the installer (there is no separate zip file to download). 

The installer will ask you to select which models to download & install. 

> Do I need to run the installer for each patch? What about this tar file I see?

Yes, if you are updating Audacity to a new version, then you probably also need to install a new version of these plugins (so download and re-run the installer). You can ignore the tar file -- GitHub automatically adds a tar file for the source code to each release which you do not need.
