### ISSUE TITLE
安装失败是为什么呢

### ISSUE THREAD

**Issue by ShiinaMayurii** [intel/openvino-plugins-ai-audacity#246]
![屏幕截图 2024-07-16 201625](https://github.com/user-attachments/assets/16b24b5d-319d-4e76-a49d-3b6a9b2cb6c2)

**Comment by RyanMetcalfeInt8** [comment]
Hmm, I would try running the installer again. It looks like one of the model files that was downloaded didn't have an expected checksum (i.e. it caught that the downloaded file was corrupted).
