### ISSUE TITLE
Re-adding Remix as well as a very interesting feature: Audio extender

### ISSUE THREAD

**Issue by luiscarlos2000** [intel/openvino-plugins-ai-audacity#247]
Well hi there, or hello, or ahoy, or what ever greeting what so ever.
I was asking if there's a possibility to re-add Remix to the package. Even, going beyond that, I want a feature that can extend an audio file. It's important and even necessary for a local alternative to websites like Suno or Udio which have the possibility that you upload an audio file, then tell the AI to extend it.
Hope you reseive my comments.

**Comment by RyanMetcalfeInt8** [comment]
Ahoy @luiscarlos2000!

We don't currently have any plans to add Remix back into the package -- at least the stable-diffusion based version that was included in original 3.4.2-R1 release. I would like to eventually add a remix-like effect using MusicGen LLM.

For 'Audio extender', we sort of already have this in the current set of plugins -- Audio Continuation. You can select up to a 10 second snippet and generate a continuation of it. See the example videos here: https://github.com/intel/openvino-plugins-ai-audacity/tree/main/doc/feature_doc/music_generation#audio-continuation-on-same-track

**Comment by luiscarlos2000** [comment]
Wow ryan you've responded so fast I couldn't imagine the speed!
Sorry to hear that, as it's the first time I'm using the plugins and I was not noticed about the change, as that thing looked interesting.
Also that audio continuation sounds interesting, although I have a question. Could be possible to have a clip that goes beyond 10 seconds or just that maximum point to extend it? HHow can I go to that audio continuation feature? As I only saw noice supression and music separation (style remix is paused I believed you've said), Music generation and whisper transcription, but not continuation. Maybe I did missed something or...

**Comment by RyanMetcalfeInt8** [comment]
> Could be possible to have a clip that goes beyond 10 seconds or just that maximum point to extend it?

Your clip can be longer than 10 seconds, but it will only use the last 10 seconds as 'context' to feed into the AI model. 

> As I only saw noice supression and music separation (style remix is paused I believed you've said), Music generation and whisper transcription, but not continuation. Maybe I did missed something or...

The audio continuation feature is part of 'Music Generation'. To use it, highlight a section of audio, choose 'Music Generation' from the generators menu, and you'll see some 'audio continuation' check boxes enabled in the pop-up dialog.

Again, see here for a couple video tutorials of how to use this feature: https://github.com/intel/openvino-plugins-ai-audacity/tree/main/doc/feature_doc/music_generation#audio-continuation-on-same-track
