### ISSUE TITLE
"Procedure Not Found" 

### ISSUE THREAD

**Issue by DioAkuma** [intel/openvino-plugins-ai-audacity#249]
I tried installing and uninstalling a bunch of times and keep coming up with this.
![image_2024-07-17_121800132](https://github.com/user-attachments/assets/2fa877e8-6739-472a-ae31-4b2dcedc94f7)

**Comment by RyanMetcalfeInt8** [comment]
Hello, can you give some details about which version of Audacity you have installed, as well as what version of these plugins you are using?
