### ISSUE TITLE
avformat-61.dll?

### ISSUE THREAD

**Issue by ELoVernahaa** [intel/openvino-plugins-ai-audacity#251]
Error: Failed to load shared library 'avformat-61.dll' (error 126: The specified module could not be found.)
Thats all it keep saying.

**Comment by linleo1234** [comment]
Have you solved this problem yet? I also have this problem now

**Comment by RyanMetcalfeInt8** [comment]
Hi @linleo1234, 

The ```avformat-X.dll``` errors in the log are not related to these plugins (they actually show up in the log even without the plugins installed). Is there a problem you're experiencing (other than seeing this error in the log)?

**Comment by linleo1234** [comment]
ok , Hey buddy, you replied to me here. It just appeared earlier and I tried many times but it didn't work. I'm reinstalling it now and trying again

**Comment by RyanMetcalfeInt8** [comment]
> Hey buddy, you replied to me here

Ah, right :) it's getting late and I wasn't paying attention to the username :)

**Comment by linleo1234** [comment]
its's ok

**Comment by linleo1234** [comment]
it‘s ok
