### ISSUE TITLE
Audacity 3.6.1 is released

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#252]
### Please, could You update OpenWINO AI plugins for Audacity 3.6.1, or to newest version for Audacity?
Thank You.
Best regards
Marco Oros

**Comment by NikolausRinge** [comment]
dito

**Comment by RyanMetcalfeInt8** [comment]
Hello @Giovani93, @NikolausRinge,

Yes, we will be posting an updated version soon (hopefully in a few hours) after some verification testing.

Thanks,
Ryan
