### ISSUE TITLE
NOT Loading "Procedure Cannot be found"

### ISSUE THREAD

**Issue by johns215pa** [intel/openvino-plugins-ai-audacity#255]
Get message saying "Procedure Cannot be found", Says failed in modules.
<img width="390" alt="igDIJq6a4t" src="https://github.com/user-attachments/assets/5072d8dc-28c6-4296-97f8-4a23a6ad4863">

**Comment by RyanMetcalfeInt8** [comment]
Hi @johns215pa, can you give some details about which version of Audacity you are using, as well as which version of these plugins that you downloaded / installed? Thanks!
