### ISSUE TITLE
hello,I have installed auditcity-win-v3.6.1-R3.1-64bit-OpenVINO-AI-Plugins, but I couldn't find the openvino plugin and restarted it

### ISSUE THREAD

**Issue by linleo1234** [intel/openvino-plugins-ai-audacity#256]
![1721812964172](https://github.com/user-attachments/assets/be09702b-8edc-40be-a990-850e672b490c)
![1721812991762](https://github.com/user-attachments/assets/78bed1ad-48bd-4ba8-8e8c-0cc339a0657c)
![cd86a9015753106dd0405e0c9e6e2df](https://github.com/user-attachments/assets/57832fe0-1eb9-4635-a0d8-d9f4f6fba999)

**Comment by RyanMetcalfeInt8** [comment]
Hello, did you enable the module in Preferences->Modules?

**Comment by linleo1234** [comment]
> 您好，您是否在“首选项”->“模块”中启用了该模块？
I have enabled it, but it seems that these two options cannot be selected. Is it because they are not installed properly or there are still functions that have not been enabled
![1721870040680](https://github.com/user-attachments/assets/ab9bde1e-c78d-4c51-b6f2-8da0379129c6)

![bdd6a92207ffe2eaa8a3215b846875c](https://github.com/user-attachments/assets/f91da019-4b0b-41f5-9461-bd57980e028f)

**Comment by linleo1234** [comment]
> 您好，您是否在“首选项”->“模块”中启用了该模块？

Sorry, I found out that I didn't import the music. It's fine now. If there are any other questions in the future, I'll come back for advice. Thank you

**Comment by linleo1234** [comment]
![1721870814115](https://github.com/user-attachments/assets/8ce83337-7e0f-4cbf-b341-e699edf87bd3)
New question, is there anything else that needs to be installed? Where is this located

**Comment by linleo1234** [comment]
It says it cannot find the specified module 'avformat-61.ll'

**Comment by RyanMetcalfeInt8** [comment]
Hi @linleo1234, 

The ```Error: Failed to load shared library``` messages in the log are okay.. they aren't related to these plugins. 

To double check -- Did you enable the ```mod-openvino``` module in Preferences, as is shown here?

![image](https://github.com/user-attachments/assets/64b397b5-430c-4c70-9a48-cfd8d03fea01)

**Comment by linleo1234** [comment]
> 你好@linleo1234，
> 
> 日志中的消息`Error: Failed to load shared library`没问题......它们与这些插件无关。
> 
> 仔细检查——您是否`mod-openvino`在“首选项”中启用了该模块，如下图所示？
> 
> ![图像](https://private-user-images.githubusercontent.com/107415876/351926898-64b397b5-430c-4c70-9a48-cfd8d03fea01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzE2MDAsIm5iZiI6MTcyMTg3MTMwMCwicGF0aCI6Ii8xMDc0MTU4NzYvMzUxOTI2ODk4LTY0YjM5N2I1LTQzMGMtNGM3MC05YTQ4LWNmZDhkMDNmZWEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMTM1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTA0MGE2ZTNiNTM5MzQ1YTNiNjI0M2E5ODliNWM5OGZhN2MwNTU1NWI0OTY3ZGQ5YzA4OTMyNWZhOWMxNDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HSL3uocYMTpDpwpPo0p9aQ-8ylyPNq89yCbhf3DfyKI)

**Comment by linleo1234** [comment]
![image](https://github.com/user-attachments/assets/22b592a7-db51-4301-9fb3-d794117ce775)
yes，Enabled=‘已启用’，but，It still prompts this, do I need to restart

**Comment by RyanMetcalfeInt8** [comment]
Yes, after you enable it, you will have to restart Audacity.

**Comment by linleo1234** [comment]
It's useless. I've already shut down and restarted many times, almost shut down and restarted. I'm currently deleting, reinstalling and trying again

**Comment by RyanMetcalfeInt8** [comment]
Hmm, is there any pop up error messages that show up when you launch Audacity after enabling the module & restarting? Also, once Audacity restarts, what is the state of ```mod-openvino``` in Modules->Preferences? Is it ```enabled``` or ```failed```?

**Comment by linleo1234** [comment]
No, after selecting 'enable' as the preferred option and then turning it off and back on, there was no pop-up error message. However, when selecting music and performing separation, there was an issue where the module could not be found

**Comment by linleo1234** [comment]
![image](https://github.com/user-attachments/assets/08e2470d-9682-49ec-9824-00b083a5e048)

Bro, I'm reinstalling now. Should we just install these plugins by default, or should we check if there are any missing ones

**Comment by RyanMetcalfeInt8** [comment]
Yes, those are a good default set of models to install -- and looks like you have Music Separation selected there, so that should work.

**Comment by linleo1234** [comment]
I have reinstalled it, but it still appears
24:14: Audacity 3.6.1
11:24:14: Error: Failed to load shared library 'avformat-61.dll' (error 126: 找不到指定的模块。)
11:24:14: Error: Failed to load shared library 'avformat-60.dll' (error 126: 找不到指定的模块。)
11:24:14: Error: Failed to load shared library 'avformat-59.dll' (error 126: 找不到指定的模块。)
11:24:14: Error: Failed to load shared library 'avformat-58.dll' (error 126: 找不到指定的模块。)
11:24:14: Error: Failed to load shared library 'avformat-57.dll' (error 126: 找不到指定的模块。)
11:24:14: Error: Failed to load shared library 'avformat-55.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-61.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-60.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-59.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-58.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-57.dll' (error 126: 找不到指定的模块。)
11:24:17: Error: Failed to load shared library 'avformat-55.dll' (error 126: 找不到指定的模块。)
11:24:23: File name is C:\Users\xxb\Downloads\3213094484 (1).mp3
11:24:23: Mime type is *
11:24:23: Opening with libmpg123
11:24:23: Open(C:\Users\xxb\Downloads\3213094484 (1).mp3) succeeded
11:24:23: Operation '正在导入 MP3文件' took 0.049000 seconds. Poll was called 1016 times and took 0.000038 seconds. Yield was called 0 times and took 0.000000 seconds.
11:24:23: Operation 'Music Information Retrieval' took 0.032000 seconds. Poll was called 2048 times and took 0.000049 seconds. Yield was called 0 times and took 0.000000 seconds.
11:24:30: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:24:30: Error: In Music Separation, exception: Exception from src/inference/src/cpp/core.cpp:124:
Exception from src/inference/src/model_reader.cpp:160:
Unable to read the model: C:\Leo\宸ュ叿\ai缈诲敱\audacity\openvino-models\htdemucs_v4.xml Please check that model format: xml is supported and the model is correct. Available frontends: ir onnx paddle pytorch tf tflite 


11:24:37: Operation 'OpenVINO Music Separation' took 0.079000 seconds. Poll was called 2 times and took 0.000001 seconds. Yield was called 0 times and took 0.000000 seconds.
