### ISSUE TITLE
Audacity 3.6.1 - Intel Core Ultra 7 155u NPU not listed (OpenVINO Music Separation)

### ISSUE THREAD

**Issue by odeevee** [intel/openvino-plugins-ai-audacity#261]
On a Lenovo Yoga 7 with a Core Ultra 7 155u, with the latest available NPU driver from Intel, the NPU is not listed when using the OpenVINO plugins in Audacity. The only 2 options are CPU and GPU. 

OS: Windows 11 23H2

Am I missing requirement components or a configuration change somewhere?

**Comment by RyanMetcalfeInt8** [comment]
Hmm.. does the NPU show up in device manager (usually as Intel AI Boost)?

**Comment by odeevee** [comment]
Yes, it does. After attempting to use the plugins and noticing the NPU wasn't showing up in the list, I went ahead and updated the NPU driver to the latest version. NPU still doesn't appear as an option.

**Comment by RyanMetcalfeInt8** [comment]
That’s strange. Which version of NPU driver do you have installed? I’ll try this on my end.

**Comment by odeevee** [comment]
This is the version currently installed on my laptop: 32.0.100.2540

**Comment by odeevee** [comment]
It dawned on me that I wrote this issue having only tested one of the features (music separation). I tried both noise suppression and transcription, the NPU shows up as inference device for both. It seems to only be missing when using the music separation feature.

**Comment by RyanMetcalfeInt8** [comment]
Ah got it. Actually that is expected. With the original NPU driver, there were some issues for NPU when running Music Separation — so I had disabled it for that feature. Let me try with latest release, and if it works I can enable it for the next release. Thanks!
