### ISSUE TITLE
Supported CPUs

### ISSUE THREAD

**Issue by LogicGirlUSA** [intel/openvino-plugins-ai-audacity#262]
My computer has
**AMD A6-3420M APU** with Radeon(tm) HD Graphics   1.50 GHz
will this be added to the list of supported cpu's in the future?

**Comment by RyanMetcalfeInt8** [comment]
Hi @LogicGirlUSA,

This is a question for the OpenVINO framework itself (https://github.com/openvinotoolkit/openvino). Our plugins use this framework to run the AI models, and so it's up to the *base* OpenVINO framework to implement support for specific hardware.

Thanks,
Ryan
