### ISSUE TITLE
Openwino noise suppression failed

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#266]
Here is note from My log of Audacity
20:56:20: Error: In Noise Suppression Compilation, exception: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:54:
Exception from src/plugins/intel_cpu/src/cpu_memory.cpp:232:
Failed to allocate 282441216 bytes of memory

After removing open wino ai cache files, everything works fine.
Please, could You look on It?
Thank You.
Best regards
Marco Oros

**Comment by Giovani93** [comment]
Hello again. I haven't got any response from You, so I don't know, what is this problem. I've sent You here log entry about It.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Giovani93, apologies, I forgot to reply to this one.

> Failed to allocate 282441216 bytes of memory

Any chance you're system is running low on system memory when you are trying this? 

So just to double check -- when you remove the openvino cache directory (in %appdata%), the issue goes away?

**Comment by Giovani93** [comment]
Yes. When I remove files in this directory (directory still exists), everything works good. What can be a problem?

**Comment by RyanMetcalfeInt8** [comment]
> What can be a problem?

Is it consistent, or did it happen just the one time? I ask because this kind of error (```Failed to allocate 282441216 bytes of memory```) usually indicates that your system doesn't have enough system memory (RAM) to accommodate the allocation request.   Or if it does happen again, can you check your system memory utilization in task manager.. is it close to 100%?

**Comment by Giovani93** [comment]
> Is it consistent, or did it happen just the one time? I ask because this kind of error (Failed to allocate 282441216 bytes of memory) usually indicates that your system doesn't have enough system memory (RAM) to accommodate the allocation request. Or if it does happen again, can you check your system memory utilization in task manager.. is it close to 100%?

Everything is now correct, but I'll watch It, if It'll happened again, because now My RAM is around 55%.

**Comment by RyanMetcalfeInt8** [comment]
Thanks, let me close this one for now -- but feel free to report back / re-open it in case you have some updates. Appreciate your feedback!
