### ISSUE TITLE
Error: In Music Generation V2, exception: Exception from src/inference/src/cpp/core.cpp:107:

### ISSUE THREAD

**Issue by mizabmdgg** [intel/openvino-plugins-ai-audacity#267]
16:48:36: Audacity 3.6.1
16:48:36: Error: Failed to load shared library 'avformat-61.dll' (error 126: Не найден указанный модуль.)
16:48:36: Error: Failed to load shared library 'avformat-60.dll' (error 126: Не найден указанный модуль.)
16:48:36: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
16:48:44: Error: Failed to load shared library 'avformat-61.dll' (error 126: Не найден указанный модуль.)
16:48:44: Error: Failed to load shared library 'avformat-60.dll' (error 126: Не найден указанный модуль.)
16:48:44: FFmpeg libraries loaded successfully from: C:\Program Files\FFmpeg For Audacity\avformat-59.dll
16:49:48: Operation 'OpenVINO Music Generation' took 15,845000 seconds. Poll was called 32 times and took 0,094482 seconds. Yield was called 31 times and took 0,076260 seconds.
16:49:36: Error: In Music Generation V2, exception: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:54:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program_builder.cpp:185:
[GPU] ProgramBuilder build failed!
Exception from src/plugins/intel_gpu/src/graph/include\primitive_type_base.h:58:
[GPU] Can't choose implementation for result:new_key_value_23_0/sink_port_0 node (type=reorder)
[GPU] Original name: new_key_value_23_0/sink_port_0
[GPU] Original type: Result
[GPU] Reason: Check '!kernels.empty()' failed at src/plugins/intel_gpu/src/kernel_selector/kernel_selector.cpp:70:
[GPU] Could not find a suitable kernel for result:new_key_value_23_0/sink_port_0 params raw string: F32_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v1_p0_0;F16_BFYX_v64_p0_0_v1_p0_0_v16_p0_0_v1_p0_0

idk what to do, i drop avformat-61.dll and avformat-60.dll to C:\Program Files\FFmpeg For Audacity\  where i have avformat-59.dll
but audacity dont see it, where i need to place it? it shows only if i use GPU in generation by the way

**Comment by RyanMetcalfeInt8** [comment]
Hi @mizabmdgg,

> idk what to do, i drop avformat-61.dll and avformat-60.dll to C:\Program Files\FFmpeg For Audacity\ where i have avformat-59.dll but audacity dont see it, where i need to place it?

The avformat errors are unrelated to Music Generation / this plugin. This is just Audacity looking for FFMpeg, and I believe it will still print some of these even if everything is okay (i.e. FFMpeg is found).

> it shows only if i use GPU in generation by the way

What kind of GPU is this? I've seen reports of these kinds of errors from NVidia GPUs, for example -- but they are not really supported by OpenVINO. Here is the list of 'officially' supported GPUs: https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html#gpu

Thanks,
Ryan

**Comment by mizabmdgg** [comment]
oh, i have rtx 3050, and i dont see, i just need to try reinstall ffmpeg and try again?

**Comment by RyanMetcalfeInt8** [comment]
>  i just need to try reinstall ffmpeg and try again?

Installing ffmpeg may resolve some of the avformat errors that you are seeing (in my experience, there are always some avformat error messages, even if ffmpeg is installed) -- but unfortunately, this isn't going to resolve the issues when trying to use that rtx 3050 to run music separation.

**Comment by mizabmdgg** [comment]
damn, thank you for anwser
