### ISSUE TITLE
Audacity build error : AboutDialog.cpp:572:10: error: ‘LINSTALL_PREFIX’

### ISSUE THREAD

**Issue by fmaskes** [intel/openvino-plugins-ai-audacity#268]
I try install openvino in ubuntu 22, but when run make -j`nproc`  shows this bellow.
Sorry, I dont speake english so so.

[ 70%] Building CXX object src/CMakeFiles/Audacity.dir/BatchCommandDialog.cpp.o
In file included from /home/casa/.conan2/p/wxwid26732179fffef/p/include/wx-3.1/wx/version.h:16,
                 from /home/casa/.conan2/p/wxwid26732179fffef/p/include/wx-3.1/wx/defs.h:194,
                 from /home/casa/.conan2/p/wxwid26732179fffef/p/include/wx-3.1/wx/event.h:14,
                 from /home/casa/.conan2/p/wxwid26732179fffef/p/include/wx-3.1/wx/window.h:18,
                 from /home/casa/.conan2/p/wxwid26732179fffef/p/include/wx-3.1/wx/panel.h:19,
                 from /home/casa/Downloads/audacity/libraries/lib-wx-wrappers/wxPanelWrapper.h:12,
                 from /home/casa/Downloads/audacity/src/AboutDialog.h:15,
                 from /home/casa/Downloads/audacity/src/AboutDialog.cpp:29:
/home/casa/Downloads/audacity/src/AboutDialog.cpp: In member function ‘void AboutDialog::PopulateInformationPage(ShuttleGui&)’:
/home/casa/Downloads/audacity/src/AboutDialog.cpp:572:10: error: ‘LINSTALL_PREFIX’ was not declared in this scope; did you mean ‘wxINSTALL_PREFIX’?
  572 |          wxT(INSTALL_PREFIX));
      |          ^~~
make[2]: *** [src/CMakeFiles/Audacity.dir/build.make:90: src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o] Erro 1
make[2]: ** Esperando que outros processos terminem.
make[1]: *** [CMakeFiles/Makefile2:5908: src/CMakeFiles/Audacity.dir/all] Erro 2

Tank's

**Comment by RyanMetcalfeInt8** [comment]
Hi @fmaskes,

I think I'll need some more info in order to help. Did you check out Audacity 3.6.1 tag? 

Can you attach a full log of your build steps and output?

**Comment by RyanMetcalfeInt8** [comment]
@fmaskes ?
