### ISSUE TITLE
How Do You Get The Exported Audio?

### ISSUE THREAD

**Issue by DataJuggler** [intel/openvino-plugins-ai-audacity#269]
I have the plug-in installed, it works, except the only thing I see is the text displayed in Audacity below the track.

Is there a way to get this text into say Notepad or my clipboard so I don't have to type it?

The interface closes if I try and right click on the track for the transcription. I must be missing something, as the text isn't useable if it is on screen only.

Thanks, perhaps this is obvious to others on how to do this if it is possible. 

![image](https://github.com/user-attachments/assets/cbd99b2b-8f0e-4906-8760-459a8139eddc)

**Comment by RyanMetcalfeInt8** [comment]
Hi @DataJuggler,

To export this to a .txt file, you can select the label track (the track containing the text), and then go to **File**->**Export Other**->**Export Labels...**.

**Comment by DataJuggler** [comment]
Thank you for the prompt response. I will try when I get off work.,Corby
        
        
          On Aug 15 2024, at 4:36 pm, Ryan Metcalfe ***@***.***> wrote:
          
        
        
          
Hi @DataJuggler,
To export this to a .txt file, you can select the label track (the track containing the text), and then go to File->Export Other->Export Labels....

**Comment by DataJuggler** [comment]
Hi, I will count this what I learned today. I did see Export Other, but didn't realize the text was considered Labels. 

Thanks,

**Comment by RyanMetcalfeInt8** [comment]
You're welcome!
