### ISSUE TITLE
Is it possible to install Audacity for Linux?

### ISSUE THREAD

**Issue by rafadesign** [intel/openvino-plugins-ai-audacity#27]
Is there any way to install Openvino on the Linux version of Audacity?

**Comment by RyanMetcalfeInt8** [comment]
Yes, but the caveat right now is that you'll need to build these plugins from scratch. 

There are build instructions posted here: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/linux/README.md

But note that these are for Ubuntu 22.04, so you may need to tweak some things if you're building for other Linux distros.

**Comment by rafadesign** [comment]
> Sim, mas a ressalva agora é que você precisará construir esses plugins a partir do zero.
> 
> Há instruções de compilação postadas aqui: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/linux/README.md
> 
> Mas note que estes são para o Ubuntu 22.04, então você pode precisar ajustar algumas coisas se você estiver construindo para outras distribuições Linux.

I use distros based on Red Hat/Fedora

**Comment by RyanMetcalfeInt8** [comment]
> I use distros based on Red Hat/Fedora

Got it. Most of what you'll need to tweak is probably at the part where you need to build Audacity itself. You can follow Fedora instructions instead, from here:
https://github.com/audacity/audacity/blob/master/BUILDING.md#linux
