### ISSUE TITLE
The module "mod-openvino" is matched with Audacity version "3.6.1"

### ISSUE THREAD

**Issue by WithBlueHorns** [intel/openvino-plugins-ai-audacity#270]
Google tells me nothing, so does this notification, any suggestions?
My current version is 3.6.1 64 bit, windows 10
![image](https://github.com/user-attachments/assets/7f0ba0a0-18cc-416d-88c0-47ef0089b2eb)

**Comment by RyanMetcalfeInt8** [comment]
This error indicates a mismatch between the plugin version, and the Audacity version. 

If you're using Audacity 3.6.1, then you should be using this version of the plugins: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.1-R3.1

Is this the version you're using?

**Comment by WithBlueHorns** [comment]
Yeah, it is
In the meantime, I reinstalled audacity and it fixed the issue somehow
Also shouldn't the error show "mismatch" instead of "match"?

**Comment by RyanMetcalfeInt8** [comment]
Glad you were able to resolve the issue by re-installing Audacity. 

> Also shouldn't the error show "mismatch" instead of "match"?

I think the error message is saying that the *mod-openvino* module is compatible with 3.6.1 (so it's *matched* with that version), but Audacity itself is some other version. But I agree, the message could be made much more clear... but by the way, this message is printed from Audacity, not our plugins..

**Comment by WithBlueHorns** [comment]
Thanks, good to know
