### ISSUE TITLE
How to run Openvino Acudacity in Mac?

### ISSUE THREAD

**Issue by Razakhan45** [intel/openvino-plugins-ai-audacity#273]
I have previously used window laptop . In that i could easily install openvino to use with audacity for Audio editing . Now I have Mac , i could not get any information or solution to make Openvino work with Audacity. If there is some video showing this tutorial it would be very helpful. Is it possible to integrate Openvino in Mac Audacity.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Razakhan45,

I would recommend reading through the discussion here: https://github.com/intel/openvino-plugins-ai-audacity/discussions/274

As you can see from the discussion, there are some nice contributions happening in an effort to get these plugins running on Mac. But, I out development team only has access to PCs running Windows and Linux, so it won't be a primary focus for this project. With that said, I'd be happy to review / accept contributions to this project that make it easier for folks to use on Mac.

Cheers!
