### ISSUE TITLE
OPenVINO Whisper Transcription does not pick up the model 

### ISSUE THREAD

**Issue by foxy123** [intel/openvino-plugins-ai-audacity#276]
I have followed the installation guide and the models are in /usr/local/lib/openvino-models:

```
ls /usr/local/lib/openvino-models
deepfilternet2             ggml-small-models
deepfilternet3             noise-suppression-denseunet-ll-0001.bin
ggml-base-models           noise-suppression-denseunet-ll-0001.xml
ggml-small.en-tdrz-models
```

But when I do Analyze/OpenVINO Whisper Transcription... in Audacity, the Whisper Model field is greyed out.
![Screenshot from 2024-08-24 16-01-25](https://github.com/user-attachments/assets/553b2681-28de-448f-9e97-217d41491a65)

**Comment by RyanMetcalfeInt8** [comment]
Hi @foxy123,

It looks like you may have some extra folders present for the whisper models. All of the ggml-*.bin / xml files should be sitting in /usr/local/lib/openvino-models. This is the reason why the 'apply' button is greyed out.

**Comment by foxy123** [comment]
Thanks a lot! It works perfectly now.

**Comment by krazyjakee** [comment]
```
ls /usr/local/lib/openvino-models
ggml-base.bin                    ggml-small.en-tdrz.bin
ggml-base-encoder-openvino.bin   ggml-small.en-tdrz-encoder-openvino.bin
ggml-base-encoder-openvino.xml   ggml-small.en-tdrz-encoder-openvino.xml
ggml-small.bin                   htdemucs_v4.bin
ggml-small-encoder-openvino.bin  htdemucs_v4.xml
ggml-small-encoder-openvino.xml
```

I have the same problem but for me, it doesn't work.

**Comment by RyanMetcalfeInt8** [comment]
@krazyjakee -- you're using a version of Audacity / these plugins that you built from source? On which distro?

**Comment by krazyjakee** [comment]
> you built from source

I'm not sure if I build from source, I just pasted the commands and let it roll.

Could someone who didn't build from source get as far as running the plugin? This is a screenshot of my instance:

<img width="1106" height="668" alt="Image" src="https://github.com/user-attachments/assets/2139b142-b865-4a3d-b868-56aa6d9585b4" />


> On which distro

Linux mint (cinnamon/deb)

**Comment by RyanMetcalfeInt8** [comment]
Okay, which instructions did you follow?

**Comment by RyanMetcalfeInt8** [comment]
On Linux, you can use the snap install method, or the build-from-source method. This is what I'm trying to understand.

**Comment by krazyjakee** [comment]
got you, yes I used the snap method.

**Comment by RyanMetcalfeInt8** [comment]
Got it, for snap installations the models are not looked for in `/usr/local/lib/openvino-models`. They will be downloaded / stored in some snap-specific location, but the way to install them are by running: `sudo audacity.fetch-models`

There should be an option that pops up with that cmd-line tool to install whisper transcription models.

**Comment by krazyjakee** [comment]
aaand this is where I discover this is an intel only project and I can't even fetch the models without the right hardware.

Have a great day.
