### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Lohan502** [intel/openvino-plugins-ai-audacity#279]
I hope this message finds you well. I am currently utilizing the latest Copilot+PC with Windows 11 ARM and x64 emulation capabilities. My experience with Audacity 3.6.1 has been seamless; however, I have encountered compatibility issues with OpenVINO AI Revision R3.1. The system indicates that the software is not compatible with my current setup.

Given the increasing prevalence of ARM64 architecture, I am keen to know if there are any plans to develop an ARM64 compatible version of OpenVINO AI for Audacity. Such development would not only enhance my current workflow but also benefit the wider user community transitioning to ARM-based systems.

I look forward to your response and any potential roadmap you might have for this compatibility update.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Lohan502,

OpenVINO itself (the underlying framework used for these plugins) supports ARM, so it may be possible to compile these plugins from source to run on ARM. 

But, providing pre-compiled releases (i.e. installers) for ARM (as we do for x86) is not something that our development team will be focusing on anytime soon.
