### ISSUE TITLE
Openvino - Audacity 3.61 Failure to transcribe 

### ISSUE THREAD

**Issue by mikeatrothvoicedotcom** [intel/openvino-plugins-ai-audacity#280]
I have installed the Intel Openvino Audacity module and enabled it in Audacity 3.61.  
The Voice Transcription Options do not show up on the Audacity menu system.
Music Separation & Music Suppression  shows up.

How do I see the Voice Transcription module?

Mike Roth
mike@rothvoice.com

**Comment by RyanMetcalfeInt8** [comment]
Hi Mike,

You'll find the voice transcription (OpenVINO Whisper Transcription) feature under the 'Analyzers' tab (as opposed to 'Effects'). Let me know if you still can't find it.

Thanks!
Ryan

**Comment by mikeatrothvoicedotcom** [comment]
Thanks,

Found it.

Mike
________________________________
