### ISSUE TITLE
Does this version compatible with Audacity Version 3.6.2?

### ISSUE THREAD

**Issue by homing-2k24** [intel/openvino-plugins-ai-audacity#282]
After installing and enabling it in Audacity v.3.6.2, when I restart Audacity, it gave me an error message that 'module "mod-ffmpeg" found' and asked if I want to load this module.  Regardless what I chose, it failed to load the openvino plugins.

**Comment by RyanMetcalfeInt8** [comment]
They are not yet compatible with 3.6.2 -- we are working on an upgraded set of plugins.

**Comment by homing-2k24** [comment]
Thanks for responding, Ryan!
I have another issue though, desiring to experiment & make use of the tool soon, I uninstall the latest version of Audacity and Retro it to version 3.6.1, but somehow it wouldn't run neither after I enabled the module.  
Thomas
 

    Ryan Metcalfe ***@***.***>) 在 2024年9月3日星期二 下午08:33:02 [PDT] 寫道：  
 
 


They are not yet compatible with 3.6.2 -- we are working on an upgraded set of plugins.

**Comment by RyanMetcalfeInt8** [comment]
Hmm, what is the error you are getting after downgrading to 3.6.1 version of Audacity?

**Comment by Giovani93** [comment]
I have a question. This error is in Audacity log or no? Or copy It here, maybe It helps.

**Comment by RyanMetcalfeInt8** [comment]
Hello, there is a new release available that is compatible with 3.6.2: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.2-R3.2

**Comment by homing-2k24** [comment]
yup!





    Ryan Metcalfe ***@***.***>) 在 2024年9月4日星期三 上午05:01:32 [PDT] 寫道：  
 
 


Hmm, what is the error you are getting after downgrading to 3.6.1 version of Audacity?

**Comment by homing-2k24** [comment]
Thanks for responding, but I didn't copy the error message.  But I remember it appeared after I selected the option and reopened Audacity afterward.



  
詩篇第二十二篇
1  我的神！我的神！你為甚麼離棄我？為甚麼遠離不救我，不聽我的哀號？
2  我的神啊，我白天呼求，你不應允；夜晚哀求，也不得安寧。3  但你是聖潔的，用以色列的讚美為寶座。
 

    Giovani93 ***@***.***>) 在 2024年9月5日星期四 上午12:33:13 [PDT] 寫道：  
 
 


I have a question. This error is in Audacity log or no? Or copy It here, maybe It helps.

**Comment by homing-2k24** [comment]
Thanks!



  
 

    Ryan Metcalfe ***@***.***>) 在 2024年9月6日星期五 上午08:56:00 [PDT] 寫道：  
 
 


Hello, there is a new release available that is compatible with 3.6.2: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.2-R3.2
