### ISSUE TITLE
Audacity 3.6.2 was released

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#283]
Hello.
I'd like to inform You, that new Audacity has been released, Audacity 3.6.2.
But I have a question, because It is annoyable from Me to inform You about It. Do You watch Audacity? If yes, I won't disturb You about this. Please, inform Me to be sure.
Thank You.
Best regards
Your user Marco Oros

**Comment by RyanMetcalfeInt8** [comment]
Hi Marco,

As always, thanks for the reminder! But yes, I do subscribe to receive Audacity release notifications. We are currently working to create a 3.6.1-compatible release.

Thanks!
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Whoops, yes, typo -- I meant 3.6.2

**Comment by Biotrioo** [comment]
> Whoops, yes, typo -- I meant 3.6.2

When we can expect a compatible release?

**Comment by RyanMetcalfeInt8** [comment]
Hopefully by end of day tomorrow (September 6th), Pacific Time.

**Comment by RyanMetcalfeInt8** [comment]
Hey all, updated plugins are now available here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.2-R3.2

Feel free to comment here or open a new issue if there are issues / questions. Thanks!

**Comment by joedale100** [comment]
I see 3.6.3 is now available. Will the updated plugins work with this or is another fix required?

**Comment by RyanMetcalfeInt8** [comment]
For Audacity 3.6.3, you'll need to install our 3.6.3-compatible release, here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.6.3-R3.3

**Comment by joedale100** [comment]
Hi Ryan, That worked. Thank you. Each time I launch Audacity now though, a dialogue box appears saying Audacity Module Loader: Module "mod-midi-import-export" found. Only use modules from trusted sources. Try and load this module? Yes or No. I clicked Yes, but do I have to do this every time? This message didn't use to appear.

**Comment by RyanMetcalfeInt8** [comment]
Hmm, I don't think this has to do with our plugins, but I think you can fix this by setting 'mod-midi-import-export' to 'Enabled' in Preferences->Modules. Perhaps it somehow got changed to 'Ask each time' or something?

**Comment by joedale100** [comment]
Sorted! Thanks!
