### ISSUE TITLE
Problem of My friend

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#293]
Hello.
I've tried to help with Openwino AI on computer's friend. We've tried operations for Windows 11 (maybe You know what I mean), but It didn't help. Problem can be for example, because My friend has user name with special letters (He is from Czech republic and I am from Slovakia), so maybe It can be the problem. I don't know, but My friend has sent Me a log. Maybe It helps, I don't know. My friend also can't speak English, so I rather post It here.
Thank You.
Marco
[log.txt](https://github.com/user-attachments/files/16947779/log.txt)

**Comment by RyanMetcalfeInt8** [comment]
Hi Marco,

Very interesting. A long time back (for our initial release, v3.4.2-R1) I remember seeing users report this issue.. and as you said, it was related to special characters present in the username. I reported the issue to OpenVINO, they fixed it, and it seemed to have been resolved... 

But now after seeing your report, I wonder if there was some regression... would it be too much effort to try adding a temporary user (with no special characters) on your friend's PC to see if the issue goes away?

I can try to reproduce this on my side if I can find some time. I'll also tag it as 'help wanted', in case anyone from the community wants to help check this.

Thanks,
Ryan

**Comment by Giovani93** [comment]
I think, that It won't be possible. But I'll try to do an other things, because My friend hasn't pressed button back manytimes, only one and will It be this problem?

**Comment by Giovani93** [comment]
So, We've repeated steps, as It had to be with this Windows 11 cause, but It didn't help It.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Giovani93 -- This issue should be fixed in the latest 3.7.0-based plugins. Closing this one for now, but feel free to re-open if you are still having trouble. Thanks!
