### ISSUE TITLE
Audacity crash after updating Openvino from v3.6.2-R3.2 to v3.6.3-R3.3

### ISSUE THREAD

**Issue by StanBoots** [intel/openvino-plugins-ai-audacity#295]
Hello. Today I updated Audacity from 3.6.2 to 3.6.3 and Openvino from v3.6.2-R3.2 to v3.6.3-R3.3.   I had been working fine on the previous releases.  I only use the transcription feature for language learning.

But after the update to Openvino (and setting preference to 'enabled'), Audacity crashed.  It gave the following error report, which I was unable to send to Audacity.

I have an older computer.  Is my CPU  of Intel(R) Pentium(R) CPU  N3520  @ 2.16GHz   2.16 GHz still supported?

Thanks for your help.

*********************************************

Operating system: Windows NT
                  10.0.19045 4894
CPU: amd64
     family 6 model 55 stepping 3
     4 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_ILLEGAL_INSTRUCTION
Crash address: 0x7ffcd24e41ea
Process uptime: 5 seconds

Thread 0 (crashed)
 0  openvino_intel_npu_plugin.dll + 0x141ea
    rax = 0x00000228fb904d10   rdx = 0x0000000000c605bb
    rcx = 0x000000007ffe0380   rbx = 0x00000228fb904d10
    rsi = 0x0000000000000000   rdi = 0x00000228fb7ecdc0
    rbp = 0x0000007193cfb0e0   rsp = 0x0000007193cfafe0
     r8 = 0x00000000000000c6    r9 = 0x0000000000000040
    r10 = 0x00000000000000c0   r11 = 0xfffffffeffff7fff
    r12 = 0x0000000000000000   r13 = 0x00000228fb8a4ba0
    r14 = 0x00000228fb7ece48   r15 = 0x00000228fb8a4ba0
    rip = 0x00007ffcd24e41ea
    Found by: given as instruction pointer in context

    Stack contents:
     0000007193cfafe0 c0 cd 7e fb 28 02 00 00 00 00 00 00 00 00 00 00  ÀÍ~û(...........
     0000007193cfaff0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb010 00 00 00 00 00 00 00 00 10 4d 90 fb 28 02 00 00  .........M.û(...
     0000007193cfb020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb060 90 b1 cf 93 71 00 00 00 00 00 00 00 00 00 00 00  .±Ïq...........
     0000007193cfb070 a0 b1 cf 93 71 00 00 00 34 00 36 00 00 00 00 00   ±Ïq...4.6.....
     0000007193cfb080 e0 66 97 08 fd 7f 00 00                          àf.ý...        
    Possible instruction pointers:

 1  ntdll.dll + 0x1266e0
    rbp = 0x0000007193cfb0e0   rsp = 0x0000007193cfb088
    rip = 0x00007ffd089766e0
    Found by: stack scanning

    Stack contents:
     0000007193cfb088 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb098 32 00 34 00 00 00 00 00 18 67 97 08 fd 7f 00 00  2.4......g.ý...
    Possible instruction pointers:

 2  ntdll.dll + 0x126718
    rbp = 0x0000007193cfb0e0   rsp = 0x0000007193cfb0a8
    rip = 0x00007ffd08976718
    Found by: stack scanning

    Stack contents:
     0000007193cfb0a8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb0b8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb0c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb0d8 00 00 00 00 00 00 00 00 35 79 3d 19 cd 9b 00 00  ........5y=.Í..
     0000007193cfb0e8 18 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
     0000007193cfb0f8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
     0000007193cfb108 85 7a 3d 19 cd 9b 00 00 30 b4 cf 93 71 00 00 00  z=.Í..0´Ïq...
     0000007193cfb118 a1 5b 87 08 fd 7f 00 00                          ¡[.ý...        
    Possible instruction pointers:

 3  ntdll.dll + 0x25ba1
    rsp = 0x0000007193cfb120   rip = 0x00007ffd08875ba1
    Found by: stack scanning

    Stack contents:
     0000007193cfb120 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
     0000007193cfb130 d0 b2 cf 93 71 00 00 00 90 b3 cf 93 71 00 00 00  Ð²Ïq....³Ïq...
     0000007193cfb140 b8 b5 cf 93 71 00 00 00 b9 53 08 08 fd 7f 00 00  ¸µÏq...¹S..ý...
    Possible instruction pointers:

 4  KERNEL32.DLL + 0x153b9
    rsp = 0x0000007193cfb150   rip = 0x00007ffd080853b9
    Found by: stack scanning

    Stack contents:
     0000007193cfb150 40 bf 86 fa 28 02 00 00 ba 04 00 00 ff ff ff ff  @¿ú(...º...ÿÿÿÿ
     0000007193cfb160 2c 00 2e 00 00 00 00 00 40 40 16 fb 28 02 00 00  ,.......@@.û(...
     0000007193cfb170 90 b1 cf 93 71 00 00 00 98 b1 cf 93 71 00 00 00  .±Ïq....±Ïq...
     0000007193cfb180 00 00 b5 f4 28 02 00 00 00 00 00 00 00 00 00 00  ..µô(...........
     0000007193cfb190 58 b0 c5 af fc 7f 00 00                          X°Å¯ü...        
    Possible instruction pointers:

 5  igdfcl64.dll + 0x15cb058
    rsp = 0x0000007193cfb198   rip = 0x00007ffcafc5b058
    Found by: stack scanning

    Stack contents:
     0000007193cfb198 7d 01 00 00 00 00 00 00 18 00 00 00 00 00 00 00  }...............
     0000007193cfb1a8 02 00 00 00 00 00 00 00 30 b4 cf 93 71 00 00 00  ........0´Ïq...
     0000007193cfb1b8 00 00 00 00 00 00 00 00 d0 b2 cf 93 71 00 00 00  ........Ð²Ïq...
     0000007193cfb1c8 00 00 00 00 00 00 00 00 00 07 18 fb 28 02 00 00  ...........û(...
     0000007193cfb1d8 b1 47 87 08 fd 7f 00 00                          ±G.ý...        
    Possible instruction pointers:

 6  ntdll.dll + 0x247b1
    rsp = 0x0000007193cfb1e0   rip = 0x00007ffd088747b1
    Found by: stack scanning

    Stack contents:
     0000007193cfb1e0 80 ae cf 93 71 00 00 00 00 00 b7 f4 28 02 00 00  .®Ïq.....·ô(...
     0000007193cfb1f0 30 b3 cf 93 71 00 00 00 00 00 00 00 00 00 00 00  0³Ïq...........
     0000007193cfb200 00 00 00 00 00 00 00 00 f0 9b e6 cc 83 44 00 00  ........ðæÌD..
     0000007193cfb210 00 00 00 00 00 00 00 00 a2 49 08 08 fd 7f 00 00  ........¢I..ý...
    Possible instruction pointers:

 7  KERNEL32.DLL + 0x149a2
    rsp = 0x0000007193cfb220   rip = 0x00007ffd080849a2
    Found by: stack scanning

Thread 1
 0  ntdll.dll + 0xa0ff4
    rax = 0x00000000000001d5   rdx = 0x00000228f4b791c0
    rcx = 0x0000000000000074   rbx = 0x00000228f4b79540
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b79540
    rbp = 0x0000000000000000   rsp = 0x0000007193dff768
     r8 = 0x00000000000000f0    r9 = 0x0000007193dff210
    r10 = 0x00007ffce68000f0   r11 = 0x0000000000000001
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd088f0ff4
    Found by: given as instruction pointer in context

    Stack contents:
     0000007193dff768 07 d4 89 08 fd 7f 00 00                          .Ô.ý...        
    Possible instruction pointers:

 1  ntdll.dll + 0x4d407
    rax = 0x00000000000001d5   rdx = 0x00000228f4b791c0
    rcx = 0x0000000000000074   rbx = 0x00000228f4b79540
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b79540
    rbp = 0x0000000000000000   rsp = 0x0000007193dff770
     r8 = 0x00000000000000f0    r9 = 0x0000007193dff210
    r10 = 0x00007ffce68000f0   r11 = 0x0000000000000001
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd0889d407
    Found by: simulating a return from leaf function

Thread 2
 0  ntdll.dll + 0xa0ff4
    rax = 0x00000000000001d5   rdx = 0x00000228f4b7e770
    rcx = 0x0000000000000074   rbx = 0x00000228f4b7eaf0
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b7eaf0
    rbp = 0x0000000000000000   rsp = 0x0000007193eff858
     r8 = 0x0000000000000100    r9 = 0x0000007193eff300
    r10 = 0x00007ffcfc380100   r11 = 0x0000000000000001
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd088f0ff4
    Found by: given as instruction pointer in context

    Stack contents:
     0000007193eff858 07 d4 89 08 fd 7f 00 00                          .Ô.ý...        
    Possible instruction pointers:

 1  ntdll.dll + 0x4d407
    rax = 0x00000000000001d5   rdx = 0x00000228f4b7e770
    rcx = 0x0000000000000074   rbx = 0x00000228f4b7eaf0
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b7eaf0
    rbp = 0x0000000000000000   rsp = 0x0000007193eff860
     r8 = 0x0000000000000100    r9 = 0x0000007193eff300
    r10 = 0x00007ffcfc380100   r11 = 0x0000000000000001
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd0889d407
    Found by: simulating a return from leaf function

Thread 3
 0  ntdll.dll + 0xa0ff4
    rax = 0x00000000000001d5   rdx = 0x00000228f4b7f990
    rcx = 0x0000000000000074   rbx = 0x00000228f4b7fd10
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b7fd10
    rbp = 0x0000000000000000   rsp = 0x0000007193fff5d8
     r8 = 0x00000000000003ab    r9 = 0x00000000000003ab
    r10 = 0x00000000000003a3   r11 = 0x00000000000003b4
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd088f0ff4
    Found by: given as instruction pointer in context

    Stack contents:
     0000007193fff5d8 07 d4 89 08 fd 7f 00 00                          .Ô.ý...        
    Possible instruction pointers:

 1  ntdll.dll + 0x4d407
    rax = 0x00000000000001d5   rdx = 0x00000228f4b7f990
    rcx = 0x0000000000000074   rbx = 0x00000228f4b7fd10
    rsi = 0x00000228f4b73510   rdi = 0x00000228f4b7fd10
    rbp = 0x0000000000000000   rsp = 0x0000007193fff5e0
     r8 = 0x00000000000003ab    r9 = 0x00000000000003ab
    r10 = 0x00000000000003a3   r11 = 0x00000000000003b4
    r12 = 0x0000000000000000   r13 = 0x0000000000000000
    r14 = 0x0000000000000000   r15 = 0x0000000000000000
    rip = 0x00007ffd0889d407
    Found by: simulating a return from leaf function

Loaded modules:
0x7ff791a70000 - 0x7ff7927fcfff  Audacity.exe  3.6.3.0  (main)
0x7ffcae690000 - 0x7ffcafc71fff  igdfcl64.dll  10.18.10.4276  (WARNING: No symbols, igdfcl64.pdb, FA979DB19ED44EE5BF3D26DD33E2028A1)
0x7ffcafc80000 - 0x7ffcb20bdfff  openvino_intel_cpu_plugin.dll  2024.3.0.16041
0x7ffcb20c0000 - 0x7ffcc0939fff  torch_cpu.dll  0.0.0.0
0x7ffcd24d0000 - 0x7ffcd2661fff  openvino_intel_npu_plugin.dll  2024.3.0.16041  (WARNING: No symbols, openvino_intel_npu_plugin.dll, 000000000000000000000000000000000)
0x7ffcd2730000 - 0x7ffcd2923fff  igdrcl64.dll  10.18.10.4276
0x7ffcd29b0000 - 0x7ffcd2a1cfff  openvino_hetero_plugin.dll  2024.3.0.16041
0x7ffcd2a20000 - 0x7ffcd2a7efff  igdbcl64.dll  10.18.10.4276
0x7ffcd2a80000 - 0x7ffcd2ae8fff  tbb.dll  4.0.2012.408
0x7ffcd2af0000 - 0x7ffcd2b84fff  cpu_device64.dll  3.0.1.10891
0x7ffcd2b90000 - 0x7ffcd2c05fff  task_executor64.dll  3.0.1.10891
0x7ffcd2c10000 - 0x7ffcd2d0cfff  intelocl64.dll  3.0.1.10891
0x7ffcd2d10000 - 0x7ffcd2d71fff  IntelOpenCL64.dll  10.18.10.4276
0x7ffcd2d80000 - 0x7ffcd43b1fff  openvino_intel_gpu_plugin.dll  2024.3.0.16041
0x7ffcd43c0000 - 0x7ffcd43f1fff  tbbbind_2_5.dll  2021.2.5.0
0x7ffcd4400000 - 0x7ffcd4431fff  openvino_auto_batch_plugin.dll  2024.3.0.16041
0x7ffcd4440000 - 0x7ffcd44b4fff  openvino_auto_plugin.dll  2024.3.0.16041
0x7ffcd44c0000 - 0x7ffcd461cfff  libiomp5md.dll  5.0.2024.320
0x7ffcd4620000 - 0x7ffcd48dcfff  uv.dll  0.0.0.0
0x7ffcd48e0000 - 0x7ffcd4daffff  fbgemm.dll  0.0.0.0
0x7ffcd4db0000 - 0x7ffcd4f67fff  whisper.dll  0.0.0.0
0x7ffcd5710000 - 0x7ffcd5738fff  mod-wavpack.dll  0.0.0.0
0x7ffcd5740000 - 0x7ffcd5777fff  mod-pcm.dll  0.0.0.0
0x7ffcd5780000 - 0x7ffcd5999fff  c10.dll  0.0.0.0
0x7ffcd59a0000 - 0x7ffcd662afff  openvino.dll  2024.3.0.16041
0x7ffcd66b0000 - 0x7ffcd66e5fff  mod-opus.dll  0.0.0.0
0x7ffcd66f0000 - 0x7ffcd672bfff  tbbmalloc.dll  2021.2.5.0
0x7ffcd6730000 - 0x7ffcd678bfff  asmjit.dll  0.0.0.0
0x7ffcd6790000 - 0x7ffcd67bffff  tbb12.dll  2021.2.5.0
0x7ffcd67c0000 - 0x7ffcd67d1fff  OpenCL.dll  3.0.6.0
0x7ffcd67e0000 - 0x7ffcd691bfff  mod-openvino.dll  0.0.0.0
0x7ffcd6920000 - 0x7ffcd6935fff  vorbisfile.dll  0.0.0.0
0x7ffcd6940000 - 0x7ffcd695ffff  mod-ogg.dll  0.0.0.0
0x7ffcd6960000 - 0x7ffcd69c8fff  mpg123.dll  0.0.0.0
0x7ffcd69d0000 - 0x7ffcd69eafff  mod-mpg123.dll  0.0.0.0
0x7ffcd69f0000 - 0x7ffcd6a98fff  libmp3lame.DLL  0.0.0.0
0x7ffcd6aa0000 - 0x7ffcd6afbfff  mod-mp3.dll  0.0.0.0
0x7ffcd6b00000 - 0x7ffcd6b5bfff  mod-mp2.dll  0.0.0.0
0x7ffcd6b60000 - 0x7ffcd6ba4fff  mod-midi-import-export.dll  0.0.0.0
0x7ffcd6bb0000 - 0x7ffcd6bc8fff  mod-lof.dll  0.0.0.0
0x7ffcd6bd0000 - 0x7ffcd6bf8fff  FLAC++.dll  0.0.0.0
0x7ffcd6c00000 - 0x7ffcd6c34fff  mod-flac.dll  0.0.0.0
0x7ffcd6c40000 - 0x7ffcd6ca7fff  lib-ffmpeg-support.dll  0.0.0.0
0x7ffcd6cb0000 - 0x7ffcd6d20fff  mod-ffmpeg.dll  0.0.0.0
0x7ffcd6d30000 - 0x7ffcd6d6cfff  wavpackdll.dll  5.6.0.0
0x7ffcd6d70000 - 0x7ffcd6e88fff  lib-cloud-audiocom.dll  0.0.0.0
0x7ffcd6e90000 - 0x7ffcd6f4efff  mod-cloud-audiocom.dll  0.0.0.0
0x7ffcd6f50000 - 0x7ffcd6f81fff  mod-cl.dll  0.0.0.0
0x7ffcd6f90000 - 0x7ffcd6fc6fff  mod-aup.dll  0.0.0.0
0x7ffcd6fd0000 - 0x7ffcd7054fff  opus.dll  0.0.0.0
0x7ffcd7060000 - 0x7ffcd7149fff  vorbis.dll  0.0.0.0
0x7ffcd8430000 - 0x7ffcd8440fff  lib-crypto.dll  0.0.0.0
0x7ffcd8450000 - 0x7ffcd84fefff  vorbisenc.dll  0.0.0.0
0x7ffcd8720000 - 0x7ffcd8733fff  ogg.dll  0.0.0.0
0x7ffcd8740000 - 0x7ffcd879efff  FLAC.dll  0.0.0.0
0x7ffcd87a0000 - 0x7ffcd87c2fff  zlib1.dll  1.2.13.0
0x7ffcd87d0000 - 0x7ffcd87f1fff  lib-uuid.dll  0.0.0.0
0x7ffcd8800000 - 0x7ffcd889efff  libcurl.dll  7.82.0.0
0x7ffcd88e0000 - 0x7ffcd8916fff  libexpat.dll  2.5.0.0
0x7ffcd8920000 - 0x7ffcd8930fff  lib-concurrency.dll  0.0.0.0
0x7ffcd8940000 - 0x7ffcd8a02fff  jpeg8.dll  8.2.2.0
0x7ffcd8ad0000 - 0x7ffcd8ae4fff  lib-ipc.dll  0.0.0.0
0x7ffcd8af0000 - 0x7ffcd8b03fff  lib-audio-graph.dll  0.0.0.0
0x7ffcd8b10000 - 0x7ffcd8b54fff  libpng16.dll  0.0.0.0
0x7ffcd8b60000 - 0x7ffcd8c38fff  sqlite.dll  0.0.0.0
0x7ffcd8c40000 - 0x7ffcd8c64fff  lib-sqlite-helpers.dll  0.0.0.0
0x7ffcd8c70000 - 0x7ffcd8c8efff  wxbase313u_xml_vc_x64_custom.dll  3.1.3.0
0x7ffcd8c90000 - 0x7ffcd8ca4fff  lib-transactions.dll  0.0.0.0
0x7ffcd8cb0000 - 0x7ffcd8d5dfff  sndfile.dll  1.0.31.0
0x7ffcd8d60000 - 0x7ffcd8d9afff  portaudio_x64.dll  0.0.0.0
0x7ffcd8da0000 - 0x7ffcd8dbdfff  VCRUNTIME140.dll  14.40.33810.0
0x7ffcd8dc0000 - 0x7ffcd8e4cfff  MSVCP140.dll  14.40.33810.0
0x7ffcd8e50000 - 0x7ffcd8e97fff  lib-sentry-reporting.dll  0.0.0.0
0x7ffcd8ea0000 - 0x7ffcd9229fff  wxbase313u_vc_x64_custom.dll  3.1.3.0
0x7ffcd9230000 - 0x7ffcd9255fff  lib-strings.dll  0.0.0.0
0x7ffcd9260000 - 0x7ffcd9281fff  lib-utility.dll  0.0.0.0
0x7ffcd9290000 - 0x7ffcd92b5fff  lib-string-utils.dll  0.0.0.0
0x7ffcd92c0000 - 0x7ffcd92e0fff  lib-components.dll  0.0.0.0
0x7ffcd92f0000 - 0x7ffcd9330fff  lib-preferences.dll  0.0.0.0
0x7ffcd9340000 - 0x7ffcd9ddefff  wxmsw313u_core_vc_x64_custom.dll  3.1.3.0
0x7ffcd9de0000 - 0x7ffcda015fff  lib-theme-resources.dll  0.0.0.0
0x7ffcda780000 - 0x7ffcda7aafff  lib-files.dll  0.0.0.0
0x7ffcda7b0000 - 0x7ffcda7fbfff  lib-track.dll  0.0.0.0
0x7ffcda800000 - 0x7ffcda890fff  lib-math.dll  0.0.0.0
0x7ffcda8a0000 - 0x7ffcda8e3fff  lib-audio-devices.dll  0.0.0.0
0x7ffcda8f0000 - 0x7ffcda938fff  lib-numeric-formats.dll  0.0.0.0
0x7ffcdb340000 - 0x7ffcdb365fff  lib-registries.dll  0.0.0.0
0x7ffcdb370000 - 0x7ffcdb425fff  lib-wave-track.dll  0.0.0.0
0x7ffcdb7f0000 - 0x7ffcdb804fff  lib-basic-ui.dll  0.0.0.0
0x7ffcdb810000 - 0x7ffcdb855fff  lib-time-and-pitch.dll  0.0.0.0
0x7ffcdbed0000 - 0x7ffcdbf32fff  lib-module-manager.dll  0.0.0.0
0x7ffcdbf40000 - 0x7ffcdbf93fff  lib-effects.dll  0.0.0.0
0x7ffcdc0f0000 - 0x7ffcdc173fff  lib-project-file-io.dll  0.0.0.0
0x7ffcdc180000 - 0x7ffcdc239fff  wxmsw313u_html_vc_x64_custom.dll  3.1.3.0
0x7ffcdd860000 - 0x7ffcdd88dfff  lib-xml.dll  0.0.0.0
0x7ffcdd8f0000 - 0x7ffcdd931fff  lib-network-manager.dll  0.0.0.0
0x7ffcdda30000 - 0x7ffcdda45fff  lib-exceptions.dll  0.0.0.0
0x7ffcddc00000 - 0x7ffcddce6fff  wxmsw313u_aui_vc_x64_custom.dll  3.1.3.0
0x7ffcddcf0000 - 0x7ffcddd6efff  lib-wx-wrappers.dll  0.0.0.0
0x7ffcdddc0000 - 0x7ffcdddf2fff  lib-mixer.dll  0.0.0.0
0x7ffcdde00000 - 0x7ffcdde79fff  lib-theme.dll  0.0.0.0
0x7ffcddfa0000 - 0x7ffcde15bfff  MFPlat.DLL  10.0.19041.4597
0x7ffcde160000 - 0x7ffcde18dfff  lib-project.dll  0.0.0.0
0x7ffcde2a0000 - 0x7ffcde2c0fff  lib-project-history.dll  0.0.0.0
0x7ffcde2d0000 - 0x7ffcde362fff  lib-vst3.dll  0.0.0.0
0x7ffcde4b0000 - 0x7ffcde4e3fff  lib-snapping.dll  0.0.0.0
0x7ffce2d50000 - 0x7ffce2dbafff  lib-import-export.dll  0.0.0.0
0x7ffce2eb0000 - 0x7ffce2edbfff  lib-time-frequency-selection.dll  0.0.0.0
0x7ffce37c0000 - 0x7ffce382dfff  lib-shuttlegui.dll  0.0.0.0
0x7ffce3830000 - 0x7ffce38bafff  lib-lv2.dll  0.0.0.0
0x7ffce45b0000 - 0x7ffce4609fff  lib-audio-io.dll  0.0.0.0
0x7ffce47d0000 - 0x7ffce482efff  lib-crashpad-configurer.dll  0.0.0.0
0x7ffce4c90000 - 0x7ffce4cbdfff  lib-track-selection.dll  0.0.0.0
0x7ffce5150000 - 0x7ffce51a8fff  lib-note-track.dll  0.0.0.0
0x7ffce53f0000 - 0x7ffce5407fff  lib-channel.dll  0.0.0.0
0x7ffce5410000 - 0x7ffce549afff  lib-wx-init.dll  0.0.0.0
0x7ffce62a0000 - 0x7ffce63c7fff  OPENGL32.dll  10.0.19041.4842
0x7ffce6720000 - 0x7ffce6744fff  lib-stretching-sequence.dll  0.0.0.0
0x7ffce6800000 - 0x7ffce682bfff  GLU32.dll  10.0.19041.3636
0x7ffce6c80000 - 0x7ffce6c9afff  lib-playable-track.dll  0.0.0.0
0x7ffce6d00000 - 0x7ffce6d38fff  lib-realtime-effects.dll  0.0.0.0
0x7ffce6e50000 - 0x7ffce6e8ffff  wxmsw313u_qa_vc_x64_custom.dll  3.1.3.0
0x7ffce72c0000 - 0x7ffce7309fff  lib-vst.dll  0.0.0.0
0x7ffce7310000 - 0x7ffce7343fff  RTWorkQ.DLL  10.0.19041.4842
0x7ffce9240000 - 0x7ffce92b2fff  lib-menus.dll  0.0.0.0
0x7ffcea570000 - 0x7ffcea5b9fff  lib-dynamic-range-processor.dll  0.0.0.0
0x7ffcea620000 - 0x7ffcea633fff  lib-sample-track.dll  0.0.0.0
0x7ffcef870000 - 0x7ffcef88cfff  lib-project-rate.dll  0.0.0.0
0x7ffcef980000 - 0x7ffcef996fff  lib-command-parameters.dll  0.0.0.0
0x7ffcf28c0000 - 0x7ffcf2b59fff  COMCTL32.dll  6.10.19041.4355
0x7ffcf2bb0000 - 0x7ffcf2bd6fff  WINMM.dll  10.0.19041.3636
0x7ffcf2be0000 - 0x7ffcf2c45fff  OLEACC.dll  7.2.19041.3636
0x7ffcf2c50000 - 0x7ffcf2cf3fff  WINSPOOL.DRV  10.0.19041.4597
0x7ffcf3090000 - 0x7ffcf3096fff  MSIMG32.dll  10.0.19041.3636
0x7ffcf3110000 - 0x7ffcf3122fff  lib-file-formats.dll  0.0.0.0
0x7ffcf4490000 - 0x7ffcf44dffff  lib-music-information-retrieval.dll  0.0.0.0
0x7ffcf5aa0000 - 0x7ffcf5aa9fff  VERSION.dll  10.0.19041.3636
0x7ffcf9640000 - 0x7ffcf966afff  lib-fft.dll  0.0.0.0
0x7ffcf9dd0000 - 0x7ffcf9deefff  lib-tags.dll  0.0.0.0
0x7ffcf9e60000 - 0x7ffcf9e86fff  lib-ladspa.dll  0.0.0.0
0x7ffcf9ff0000 - 0x7ffcfa012fff  lib-preference-pages.dll  0.0.0.0
0x7ffcfa080000 - 0x7ffcfa0a5fff  lib-wave-track-paint.dll  0.0.0.0
0x7ffcfa0e0000 - 0x7ffcfa0f6fff  lib-graphics.dll  0.0.0.0
0x7ffcfa100000 - 0x7ffcfa123fff  lib-viewport.dll  0.0.0.0
0x7ffcfbdd0000 - 0x7ffcfbde3fff  portmidi.dll  0.0.0.0
0x7ffcfc030000 - 0x7ffcfc03efff  lib-export-ui.dll  0.0.0.0
0x7ffcfc380000 - 0x7ffcfc7defff  igdusc64.dll  10.18.10.4276
0x7ffcfd2a0000 - 0x7ffcfd2b9fff  lib-url-schemes.dll  0.0.0.0
0x7ffcfd3d0000 - 0x7ffcfd3edfff  lib-time-track.dll  0.0.0.0
0x7ffcfd430000 - 0x7ffcfd436fff  MSVCP140_CODECVT_IDS.dll  14.40.33810.0
0x7ffcfe5b0000 - 0x7ffcfe5bbfff  VCRUNTIME140_1.dll  14.40.33810.0
0x7ffcfe940000 - 0x7ffcfe94ffff  lib-screen-geometry.dll  0.0.0.0
0x7ffd034b0000 - 0x7ffd0354dfff  UxTheme.dll  10.0.19041.4529
0x7ffd03b80000 - 0x7ffd04322fff  windows.storage.dll  10.0.19041.4894
0x7ffd043f0000 - 0x7ffd045d3fff  dbghelp.dll  10.0.19041.3636
0x7ffd04610000 - 0x7ffd04618fff  WSOCK32.dll  10.0.19041.1
0x7ffd04770000 - 0x7ffd04781fff  kernel.appcore.dll  10.0.19041.3758
0x7ffd05130000 - 0x7ffd05162fff  ntmarta.dll  10.0.19041.3636
0x7ffd052a0000 - 0x7ffd052dafff  IPHLPAPI.DLL  10.0.19041.3636
0x7ffd057b0000 - 0x7ffd057bbfff  CRYPTBASE.DLL  10.0.19041.3636
0x7ffd058c0000 - 0x7ffd058edfff  Wldp.dll  10.0.19041.4780
0x7ffd05db0000 - 0x7ffd05dddfff  USERENV.dll  10.0.19041.4355
0x7ffd05de0000 - 0x7ffd05e11fff  SspiCli.dll  10.0.19041.4239
0x7ffd05e30000 - 0x7ffd05e53fff  profapi.dll  10.0.19041.4355
0x7ffd05f00000 - 0x7ffd05ffffff  ucrtbase.dll  10.0.19041.3636
0x7ffd06070000 - 0x7ffd060f1fff  bcryptPrimitives.dll  10.0.19041.3636
0x7ffd06100000 - 0x7ffd06121fff  win32u.dll  10.0.19041.4894
0x7ffd06130000 - 0x7ffd06246fff  gdi32full.dll  10.0.19041.4717
0x7ffd06250000 - 0x7ffd063abfff  CRYPT32.dll  10.0.19041.4894
0x7ffd063b0000 - 0x7ffd063d6fff  bcrypt.dll  10.0.19041.3636
0x7ffd063e0000 - 0x7ffd066dcfff  KERNELBASE.dll  10.0.19041.4842
0x7ffd06790000 - 0x7ffd0682cfff  msvcp_win.dll  10.0.19041.3636
0x7ffd06830000 - 0x7ffd0687dfff  cfgmgr32.dll  10.0.19041.3996
0x7ffd068e0000 - 0x7ffd06c32fff  combase.dll  10.0.19041.4717
0x7ffd06c40000 - 0x7ffd06d6afff  ole32.dll  10.0.19041.4355
0x7ffd06d70000 - 0x7ffd06d9afff  GDI32.dll  10.0.19041.4474
0x7ffd06da0000 - 0x7ffd06da7fff  PSAPI.DLL  10.0.19041.3636
0x7ffd06db0000 - 0x7ffd06e04fff  SHLWAPI.dll  10.0.19041.4355
0x7ffd06e10000 - 0x7ffd06f24fff  MSCTF.dll  10.0.19041.4842
0x7ffd06fe0000 - 0x7ffd070b9fff  COMDLG32.dll  10.0.19041.4355
0x7ffd07170000 - 0x7ffd075ddfff  SETUPAPI.dll  10.0.19041.4355
0x7ffd075f0000 - 0x7ffd07712fff  RPCRT4.dll  10.0.19041.4597
0x7ffd07720000 - 0x7ffd077cffff  ADVAPI32.dll  10.0.19041.4597
0x7ffd077d0000 - 0x7ffd07f3efff  SHELL32.dll  10.0.19041.4894
0x7ffd07fa0000 - 0x7ffd07fcefff  IMM32.DLL  10.0.19041.4474
0x7ffd07fd0000 - 0x7ffd0806ffff  sechost.dll  10.0.19041.4597
0x7ffd08070000 - 0x7ffd08130fff  KERNEL32.DLL  10.0.19041.4842  (WARNING: No symbols, kernel32.pdb, 8EA8A9E71B2052223360BD22C65057DD1)
0x7ffd08140000 - 0x7ffd081aafff  WS2_32.dll  10.0.19041.3636
0x7ffd08210000 - 0x7ffd082adfff  msvcrt.dll  7.0.19041.3636
0x7ffd082b0000 - 0x7ffd0837cfff  OLEAUT32.dll  10.0.19041.3636
0x7ffd08390000 - 0x7ffd0852cfff  USER32.dll  10.0.19041.4717
0x7ffd08760000 - 0x7ffd0880cfff  shcore.dll  10.0.19041.4522
0x7ffd08850000 - 0x7ffd08a47fff  ntdll.dll  10.0.19041.4842  (WARNING: No symbols, ntdll.pdb, 4DAAF819E9D25E52EEC34F8B9E638DE01)

**Comment by RyanMetcalfeInt8** [comment]
Hello,

This was also reported on the Audacity forums [here](https://forum.audacityteam.org/t/how-to-fix-unable-to-load-the-mod-openvino-module-error/116996/9). 

it seems like there is some kind of compatibility regression for the OpenVINO NPU plugin DLL (openvino_intel_npu_plugin.dll) between OpenVINO versions 2024.2 and 2024.3.

The workaround is to simply delete ```openvino_intel_npu_plugin.dll``` from ```C:\Program Files\Audacity```. 

Thanks,
Ryan

**Comment by StanBoots** [comment]
Ryan,  Thanks for the quick reply.  Your suggestion worked perfectly.  Audacity and Openvino transcription are working fine now after deleting that file 'openvino_intel_npu_plugin.dll'.

Thanks for developing this module.  It's really a great tool!

Stan

**Comment by RyanMetcalfeInt8** [comment]
Perfect, glad it's now working for you -- and that you're enjoying the tool!
