### ISSUE TITLE
Issue with downloading openvinoAI plugins for audacity

### ISSUE THREAD

**Issue by Nmis742** [intel/openvino-plugins-ai-audacity#299]
Hello
Wonder if you can help
I am a first time used of audacity and came across your openvino AI plug-ins download
However when installing I came across an error  @0
![image](https://github.com/user-attachments/assets/609bd75c-7d7c-4847-99ee-f5053f3575b9)
x800700c1, 99ml- base encorder- operative - bin is not a valid Win32 application.

I am not a musician and was looking at audacity to edit tracks and remove vocals as a 
Project. Wonder if you can help please.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Nmis742, this error looks very strange -- I haven't observed this issue before.

1. What version of Windows are you using?
2. What kind of CPU are you using?
3. Which version of these plugins are you using?

**Comment by Nmis742** [comment]
Hello  Ryan 

Thank you for replying so quickly and so pleased to talk to you.

As I have said I am not a IT person and I am totally new at audacity or plugins !
Thank you for your patience and support.

I am using windows 10 
The CPU is 4 core N4200 up to 2.5GHz
I have tried your newest version 3.6.4 R 3.4
I have tried 3.6.2 R 3.2 There was link from K pranavik that you sent to him 2 weeks ago. Thought I would try the link you sent him.
I have also tried 3.5.1 R 2.2 from having seen  this on a video on YouTube.

Hope this is what you needed

kind regards

Nilesh

**Comment by RyanMetcalfeInt8** [comment]
Hi @Nmis742,

For each of the versions that you have tried, are you getting this same error?

**Comment by Nmis742** [comment]
Hello Ryan

My word you are good to get back to me at this time. Thank you
I feel guilty that I am wasting your time.
I am just starting my  music journey!!  and am getting started on audacity ..

Yes I have had the same message Ryan.

You have a very good weekend

I was interested in removing vocals completely  from tracks and being able to match the pitch of a song to me playing( learning to play a Mouth organ !!  at the moment) Not really  into creating music at the moment. Just want to learn ! what is possible.. No music knowledge just enjoy learning. Recovering from a cardiac arrest in october.. so keeps the brain ticking..

Thank you once again for trying to help me and if you cannot please do not waste your time . I am sure you have other important things..

Kind regards

Nilesh





Sent from my Samsung Galaxy smartphone.


-------- Original message --------
From: Ryan Metcalfe ***@***.***>
Date: 20/09/2024 19:32 (GMT+00:00)
To: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: Nmis742 ***@***.***>, Mention ***@***.***>
Subject: Re: [intel/openvino-plugins-ai-audacity] Issue with downloading openvinoAI plugins for audacity (Issue #299)


Hi @Nmis742<https://github.com/Nmis742>,

For each of the versions that you have tried, are you getting this same error?

**Comment by RyanMetcalfeInt8** [comment]
Hi Nilesh,

Hmm, to be honest I'm not too sure why the installer would be throwing those kinds of errors. Not specific to these plugins, but googling the error code you are getting from other installers -- I have found mention that it could be caused from lack of various Windows updates. So, is your system up to date in terms of updates?

Thanks,
Ryan

**Comment by Nmis742** [comment]
Hi Ryan

Thank you again

You are a star!

I will look into this and will let you know if still ok with you. I am no IT person!!
Just more question .. What version should I use for audacity and plugins to include that of AI  Pl ?
Is it possible for you to guide me with this and perhaps when you have the time to attach links for me so I know I am doing what I should be doing. Also
Do I purchase anyting to help with the sort of things I  have mentioned?

Kind regards

Nilesh




Sent from my Samsung Galaxy smartphone.

-------- Original message --------
From: Ryan Metcalfe ***@***.***>
Date: 21/09/2024 13:46 (GMT+00:00)
To: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: Nmis742 ***@***.***>, Mention ***@***.***>
Subject: Re: [intel/openvino-plugins-ai-audacity] Issue with downloading openvinoAI plugins for audacity (Issue #299)


Hi Nilesh,

Hmm, to be honest I'm not too sure why the installer would be throwing those kinds of errors. Not specific to these plugins, but googling the error code you are getting from other installers -- I have found mention that it could be caused from lack of various Windows updates. So, is your system up to date in terms of updates?

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
The two packages that you need to download and install (in this order):
1. Audacity 3.6.4: https://github.com/audacity/audacity/releases/download/Audacity-3.6.4/audacity-win-3.6.4-64bit.exe
2. Our 3.6.4-compatible plugins: https://github.com/intel/openvino-plugins-ai-audacity/releases/download/v3.6.4-R3.4/audacity-win-v3.6.4-R3.4-64bit-OpenVINO-AI-Plugins.exe

And that should be it -- there is certainly nothing that you'll need to purchase.

Thanks,
Ryan

**Comment by Nmis742** [comment]
Thank you so so  much Ryan

 You have been a tremendous help and thank you for your kind support.

Will work through what you have suggested and the links in that order.

Have a wonderful day

Regards

Nilesh






Sent from my Samsung Galaxy smartphone.


-------- Original message --------
From: Ryan Metcalfe ***@***.***>
Date: 21/09/2024 14:48 (GMT+00:00)
To: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: Nmis742 ***@***.***>, Mention ***@***.***>
Subject: Re: [intel/openvino-plugins-ai-audacity] Issue with downloading openvinoAI plugins for audacity (Issue #299)


The two packages that you need to download and install (in this order):

  1.  Audacity 3.6.4: https://github.com/audacity/audacity/releases/download/Audacity-3.6.4/audacity-win-3.6.4-64bit.exe
  2.  Our 3.6.4-compatible plugins: https://github.com/intel/openvino-plugins-ai-audacity/releases/download/v3.6.4-R3.4/audacity-win-v3.6.4-R3.4-64bit-OpenVINO-AI-Plugins.exe

And that should be it -- there is certainly nothing that you'll need to purchase.

Thanks,
Ryan

**Comment by Nmis742** [comment]
Hi Ryan

Sorry to be a pain again..

Just need your opinion pl

If I was going to purchase a laptop to be able to be able to do things like what I mentioned and in the future to be able to create music or backing tracks etc
What machine would you suggest? I believe I might need one!. I know this depends on the budget but for a beginner what spec. would I need?

I will so grateful to you if you can suggest a starting point for me.

Hoping you can help again..

Nilesh



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
From: Ryan Metcalfe ***@***.***>
Date: 21/09/2024 14:48 (GMT+00:00)
To: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: Nmis742 ***@***.***>, Mention ***@***.***>
Subject: Re: [intel/openvino-plugins-ai-audacity] Issue with downloading openvinoAI plugins for audacity (Issue #299)


The two packages that you need to download and install (in this order):

  1.  Audacity 3.6.4: https://github.com/audacity/audacity/releases/download/Audacity-3.6.4/audacity-win-3.6.4-64bit.exe
  2.  Our 3.6.4-compatible plugins: https://github.com/intel/openvino-plugins-ai-audacity/releases/download/v3.6.4-R3.4/audacity-win-v3.6.4-R3.4-64bit-OpenVINO-AI-Plugins.exe

And that should be it -- there is certainly nothing that you'll need to purchase.

Thanks,
Ryan
