### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by ususdushdusd** [intel/openvino-plugins-ai-audacity#30]
![Cat Meaow](https://github.com/intel/openvino-plugins-ai-audacity/assets/157147952/57b2730a-d709-47e8-848c-d540f9e29c24)

**Am' i doing things wrong?** I cannot get this thing to work and my audacity version is 3.4.2

**Comment by RyanMetcalfeInt8** [comment]
Hi @ususdushdusd,

One other user posted something similar. Which version of Windows are you using, and what CPU do you have?

We have an issue here with folks reporting similar module load issues: https://github.com/intel/openvino-plugins-ai-audacity/issues/8

And it might help to give the results with the experiment described here: https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1890998932

Thanks,
Ryan

**Comment by ususdushdusd** [comment]
> Hi @ususdushdusd,
> 
> One other user posted something similar. Which version of Windows are you using, and what CPU do you have?
> 
> Also, just double checking -- you are using 64-bit version of Audacity 3.4.2 (not 32-bit)?
> 
> We have an issue here with folks reporting similar module load issues: #8
> 
> And it might help to give the results with the experiment described here: [#8 (comment)](https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1890998932)
> 
> Thanks, Ryan

What version shoud i install?

**Comment by RyanMetcalfeInt8** [comment]
You should install 64-bit version of Audacity 3.4.2 -- but looks like from the other issue you submitted, you fixed it?
