### ISSUE TITLE
inference device only has cpu, no gpu

### ISSUE THREAD

**Issue by wzm1972** [intel/openvino-plugins-ai-audacity#301]
Your suggestion for  Error reading data: (12002) Operation time out:
You can look here (https://github.com/intel/openvino-plugins-ai-audacity/tree/main/doc/build_doc/windows#installing-the-openvino-models) for the commands that can manually assemble this openvino-models folder with the right content & structure.

I download the openvino-models folder and copy it to audacity directory.  It work. But open vino inference device only show cpu option,
there is no gpu option.  I have a GTX1650 video card, i think gpu should be available.  Has someone met same problem? Thanks. 
![image](https://github.com/user-attachments/assets/d7c6d6e8-baed-429f-a929-d60a1e13bf3b)

**Comment by AumThakore** [comment]
heyy I'm facing the same issue, have you found any solution?

**Comment by RyanMetcalfeInt8** [comment]
Hi @wzm1972, @AumThakore, 

The OpenVINO framework currently only supports Intel integrated & discrete GPUs. See here for full list:
https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html#gpu

**Comment by AumThakore** [comment]
@RyanMetcalfeInt8 

oh does that mean there's no way for me to utilize the 4090 I have?
CPU is taking way too long for a 2 hrs video

**Comment by RyanMetcalfeInt8** [comment]
Hey @AumThakore,

> oh does that mean there's no way for me to utilize the 4090 I have?
Unfortunately, yes :(
