### ISSUE TITLE
Win 7 installer for VINO AI plugins reports a security error -- error sending data: (12175)

### ISSUE THREAD

**Issue by akaeroz** [intel/openvino-plugins-ai-audacity#305]
![Capture](https://github.com/user-attachments/assets/2ceb4afd-bcf9-4f8c-97b7-56584bc1d0f7)
Nothing helps:
running as an admin
allowing to pass thru firewall (inbound and outbound both secure and not secure)

Have no more concepts -- can you help?

**Comment by RyanMetcalfeInt8** [comment]
Which version of Windows are you using?

**Comment by akaeroz** [comment]
Maybe this helps: I unticked downloading any of the models and the program installed correctly creating necessary folders and  storing .dll 's. Can I download the models separately (from what repository)? If so, is there any requiered subfolders structure for the models (and where --openvino-models folder?) or should they be stored flat like other plugins?  Would appreciate your reply. Thank you.
