### ISSUE TITLE
cant choose GPU for whisper.

### ISSUE THREAD

**Issue by NeverBeLazyG** [intel/openvino-plugins-ai-audacity#309]
![image](https://github.com/user-attachments/assets/9c0cfa73-6d0a-46a5-a423-24460eec4de0)

any idea, why i cant choose gpu when using whisper ?

i am using a windows machine with rtx 4080

**Comment by RyanMetcalfeInt8** [comment]
Hi @NeverBeLazyG,

The list of supported GPUs that the OpenVINO framework supports are listed here: https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html#gpu

Unfortunately, Nvidia GPUs are not supported at this time.

Thanks,
Ryan

**Comment by NeverBeLazyG** [comment]
ok thanks
