### ISSUE TITLE
Openvino cannot read my username with special Unicode characters

### ISSUE THREAD

**Issue by Courteous-Cheetah** [intel/openvino-plugins-ai-audacity#313]
Hi,

I am having a simple issue. Here is the log:
```
11:34:12: Error: In Noise Suppression Compilation, exception: Exception from src\inference\src\cpp\core.cpp:206:
Couldn't create directory [C:\Users\_[redacted]_ďż˝ch _[redacted]_lďż˝k], err=Permission denied)
```
In other words, I have "special symbols" in my username ("ě" and "í"), openvino cannot read them, tries to create a new folder under a different username (the one with broken characters), fails to do so (because it obviously does not have rights to create a new user) and halts.

Could you please teach openvino the special Unicode characters? Without this, I have no way of making it work.

Thanks!

Edit: This seems to be a similar, if not the same issue as the user @Giovani93 is having in his issue thread #293. I am using Windows 10 22H2. I will delete this thread if admins want to merge these issues.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Courteous-Cheetah,

Thanks for reporting this. Yes, I have seen a few reports of this issue recently -- let me see if I can reproduce this on my side.

There was a similar bug a while back that I submitted an issue for, and was fixed in underlying openvino framework (https://github.com/openvinotoolkit/openvino/issues/23072). This was fixed for some time, but perhaps it popped back up again for whatever reason.. let me check.

**Comment by RyanMetcalfeInt8** [comment]
And just curious, what language do you have Audacity set to?

**Comment by Courteous-Cheetah** [comment]
Hi @RyanMetcalfeInt8,

Thank you for your quick reply and care.

My Audacity is set to Czech. I switched it to English and restarted Audacity; it made zero difference. My OS (Win 10 22H2) language is Czech.
Honestly, this is not the first time when I face similar issues; Anjok07's [ultimatevocalremovergui](https://github.com/Anjok07/ultimatevocalremovergui) refused to work for the exact same reason; in that case, after I installed it, I "dirty" moved the files away from its default installation directory (which could not be edited in the installer to something "neutral" like Program Files). That proved to be a successful workaround. That, however, is a standalone app (meaning I could "move the files freely"), so I believe the same workaround cannot be applied here, openvino being a plug-in to Audacity.

**Comment by RyanMetcalfeInt8** [comment]
Got it, thanks for the info! 

> so I believe the same workaround cannot be applied here, openvino being a plug-in to Audacity.

Right, in some sense it's my fault that a workaround isn't possible. The problem occurs when attempting to create the OpenVINO 'cache' folder, which I have hard-coded to use ```%appdata%\audacity\openvino-model-cache``` -- regardless of where the 'base' Audacity installation is located. 

But anyway, I think I've been able to reproduce it on my side, and working on a potential fix. Perhaps if you're willing, I can share a DLL + some patch instructions for you to verify on your side (probably next few days)?

**Comment by Courteous-Cheetah** [comment]
I am more than willing to collaborate on this! Count on my help, for sure. Also, if you need any more logs or details from my side, I am happy to provide them.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Courteous-Cheetah,

I think I've fixed the issue. I was able to reproduce by creating a user with special characters, and the issue went away with my latest code changes into main branch. But anyway, if you want to also validate this, it would be helpful.
1. Download this package: [mod-openvino_unicode_fix.zip](https://drive.google.com/file/d/1CzpA3IuuAo0cffTfqAUcWwwRRw3Ko8Wl/view?usp=sharing)
2. Inside this package, you'll find a single file, ```mod-openvino.dll```
3. You'll want to copy ```mod-openvino.dll``` into ```C:\Program Files\Audacity\modules``` (replacing the existing one.. you can of course back up the old one if you wish -- just back it up outside of the modules folder)
4. After copying the file there, open Audacity, go to Edit->Preferences->modules, set 'mod-openvino' to Enabled, and then close & re-open audacity
5. Is issue resolved?

Thank you!

**Comment by Courteous-Cheetah** [comment]
> Hi @Courteous-Cheetah,
> 
> I think I've fixed the issue. I was able to reproduce by creating a user with special characters, and the issue went away with my latest code changes into main branch. But anyway, if you want to also validate this, it would be helpful.
>(...)
>     5. Is issue resolved?

Hi @RyanMetcalfeInt8,
**yeees**, I can confirm it is resolved! I can finally fiddle with tracks we'd otherwise have to give to an external contractor. Thank you so much for your time you put into this! You made my day, my week, and possibly much more.

**Comment by RyanMetcalfeInt8** [comment]
awesome! Thank you for helping me verify this!
