### ISSUE TITLE
AUDICITY, AI PLUGIN, is there a MAC version available?

### ISSUE THREAD

**Issue by Fripoen** [intel/openvino-plugins-ai-audacity#315]
[https://mrc.fm/aiplugins]
is there a MAC VERSION available?
thanks a lot

**Comment by RyanMetcalfeInt8** [comment]
Hi @Fripoen,

No, not currently. Our team is focused on Windows and Linux support, but happy to accept contributions from the community that would enable Mac users in some way. Here's an existing discussion about this topic: https://github.com/intel/openvino-plugins-ai-audacity/discussions/274

Thanks,
Ryan
