### ISSUE TITLE
A question about the CPU

### ISSUE THREAD

**Issue by PETRUHA63** [intel/openvino-plugins-ai-audacity#321]
Is it possible to change the CPU parameter on the GPU somehow, I don't really like the fact that the rendering takes place on the processor

**Comment by RyanMetcalfeInt8** [comment]
Hi @PETRUHA63, 

Could you explain a bit more about what you mean? Does the drop-down list only list CPU? This could happen, for example, if you are running on a system that doesn't contain GPUs that are supported by the OpenVINO framework. Here's the list of supported devices: https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html#gpu

Thanks,
Ryan
