### ISSUE TITLE
For non-internet pc how to install

### ISSUE THREAD

**Issue by Birdqetygfh** [intel/openvino-plugins-ai-audacity#329]
I want to install in non-internet pc so kindly suggest and procedure of installation steps, any plugins required for windows pc

**Comment by RyanMetcalfeInt8** [comment]
Hi @Birdqetygfh,

Sorry for the delay. My recommendation here is to:

1. First, install on a PC that is connected to the internet. The selected models will get downloaded at installation time.
2. zip up the folder `C:\Program Files\Audacity\openvino-models` -- this has all of the required models.
3. On an offline PC, run the AI plugins installer and choose 'install no models'. 
4. Transfer the 'openvino-models.zip' that you created in step 2 to the offline PC, and replace `C:\Program Files\Audacity\openvino-models` with the zipped up folder.
