### ISSUE TITLE
Erro ao tentar usar Openvino

### ISSUE THREAD

**Issue by vanatf** [intel/openvino-plugins-ai-audacity#34]
Baixei os arquivos, movi a pasta para Audacity, ativei nas preferencias e reiniciei o programa, Porem ao tentar usar, reporta um erro e nao consigo resolver . 
podem me ajudar 
![Captura de tela 2024-01-23 125504](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/758bc25e-0b93-41f4-8013-b1ab8eb364aa)

**Comment by RyanMetcalfeInt8** [comment]
Hi,

Can you post the contents of Help -> Diagnostics -> Show Log?

Thanks,
Ryan

**Comment by vanatf** [comment]
Sim encaminhando


12:53:38: Audacity 3.4.2
12:53:38: Error: Failed to load shared library 'avformat-60.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:38: Error: Failed to load shared library 'avformat-59.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:38: Error: Failed to load shared library 'avformat-58.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:38: Error: Failed to load shared library 'avformat-57.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:38: Error: Failed to load shared library 'avformat-55.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:41: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
12:53:41: Error: Failed to load shared library 'avformat-60.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:41: Error: Failed to load shared library 'avformat-59.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:41: Error: Failed to load shared library 'avformat-58.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:41: Error: Failed to load shared library 'avformat-57.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:53:41: Error: Failed to load shared library 'avformat-55.dll' (error 126: Não foi possível encontrar o módulo especificado.)
12:54:01: File name is C:\Users\Vanato\Downloads\Wind Riders - Asher Fulero.mp3
12:54:01: Mime type is *
12:54:01: Opening with libmpg123
12:54:01: Open(C:\Users\Vanato\Downloads\Wind Riders - Asher Fulero.mp3) succeeded
12:54:02: Operation 'Importando Arquivo MP3' took 0,251000 seconds. Poll was called 5119 times and took 0,000246 seconds. Yield was called 0 times and took 0,000000 seconds.
12:54:29: Operation 'Pre-processing' took 0,000000 seconds. Poll was called 0 times and took 0,000000 seconds. Yield was called 0 times and took 0,000000 seconds.
12:57:45: Operation 'OpenVINO Noise Suppression' took 195,543000 seconds. Poll was called 387 times and took 0,562492 seconds. Yield was called 386 times and took 0,330986 seconds.
12:54:29: Error: Directory 'C:\Program Files\Audacity\openvino-models' couldn't be created (error 5: Acesso negado.)
12:54:30: Error: In Noise Suppression Compilation, exception: Exception from src\inference\src\core.cpp:100:
[ GENERAL_ERROR ] Model file C:\Program Files\Audacity\openvino-models\noise-suppression-denseunet-ll-0001.xml cannot be opened!

**Comment by RyanMetcalfeInt8** [comment]
> [ GENERAL_ERROR ] Model file C:\Program Files\Audacity\openvino-models\noise-suppression-denseunet-ll-0001.xml cannot be opened!

It looks like openvino-models folder was perhaps not installed correctly. Double check that the above file exists.

For example, other users have also experienced this issue when they have extracted openvino-models.zip such that it produces```C:\Program Files\Audacity\openvino-models\openvino-models```

And please let me know if you are able to resolve your issue. Thanks!

**Comment by vanatf** [comment]
Não esta aparecendo, devo mover a pasta ou copiar novamente?

**Comment by RyanMetcalfeInt8** [comment]
> Não esta aparecendo, devo mover a pasta ou copiar novamente?

Yes, I would download / re-do the copy of openvino-models into the Audacity folder. You can follow along to installation video that is here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.4.2-R1

Thanks,
Ryan

**Comment by vanatf** [comment]
Bom copie a pasta novamente , reinicie o programa e tentei fazer uma transcrição e deu erro .
vou desinstalar tudo remover todas as pastas , apesar que ja fiz isso e nao foi 
![Captura de tela 2024-01-23 145522](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/4e30142e-ce36-45e3-98a2-2015f511c970)

**Comment by RyanMetcalfeInt8** [comment]
Is the error in the Help -> Diagnostics -> Show Log the same as before?

Can you double check that ```C:\Program Files\Audacity\openvino-models\noise-suppression-denseunet-ll-0001.xml``` exists?

**Comment by vanatf** [comment]
sim log e o mesmo .
diretorio existe sim

**Comment by vanatf** [comment]
enquanto isso tire me uma duvida: estou utlizando versao 64 bits e wind 11 home
algum problema ?

**Comment by RyanMetcalfeInt8** [comment]
Windows 11 Home, 64-bit should be no problem.

Can you send a screenshot of the contents of your openvino-models directory?

**Comment by vanatf** [comment]
ja encaminho sim , vou fazer download novamente

**Comment by vanatf** [comment]
Uhhh sucesso meu amigo , quero agradecer valeu demais tudo certo aqui resolvido .
baixei fiz os procedimentos novamente e fiz o teste e funcionando. segue diretorio 
tirei print quando fazia copia dos arquivos

![Captura de tela 2024-01-23 162828](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/aabcd4a5-230e-485b-bea9-6ab2313acc32)
![Captura de tela 2024-01-23 163918](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/e7dd7b89-ffd4-42ab-b468-a19890822898)

**Comment by RyanMetcalfeInt8** [comment]
> ![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/5b2dab11-26ff-4fa5-bd74-99bf009ef378)

Can you show contents of this directory please?

**Comment by vanatf** [comment]
o final ficou assim, veja se é isso.
![Captura de tela 2024-01-23 171933](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/ab00683c-f41e-4c9e-898c-a1b36895eee1)

**Comment by vanatf** [comment]
pronto assim 

![Captura de tela 2024-01-23 173851](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/f14e935d-e76d-477f-9bc9-a97067dc9714)

**Comment by RyanMetcalfeInt8** [comment]
Thanks -- now I'm wondering of the specific path is a problem. Can you open up cmd.exe and do:
```
>dir "C:\Program Files\Audacity\openvino-models"
```

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/1a8535bf-c9f8-4f92-bce4-f0ffc991ba5e)

And let me know the output?

**Comment by vanatf** [comment]
reportou esta msg apos o comando

![Captura de tela 2024-01-23 185154](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/68797eb0-d364-438d-80ba-d840c502b02c)

**Comment by RyanMetcalfeInt8** [comment]
Thanks, and can you post the contents of your **Help -> Diagnostics -> Show Log** once more?

**Comment by vanatf** [comment]
simm

![Captura de tela 2024-01-23 185649](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/b96ae1b6-022c-4281-b5ea-ec87e45a9b07)

**Comment by RyanMetcalfeInt8** [comment]
Can you scroll down? I think you missed the capture the end of the log.

**Comment by vanatf** [comment]
![Captura de tela 2024-01-23 190219](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/f39da1c5-89d5-4079-b6bd-9c70b80bef64)

**Comment by RyanMetcalfeInt8** [comment]
I'm a little bit confused. Is it still failing? I don't see any error messages in the log. I also see what looks like successful runs of 'Whisper Transcription' and 'Music Generation' -- did those effects work?

**Comment by vanatf** [comment]
aqui 

![Captura de tela 2024-01-23 190414](https://github.com/intel/openvino-plugins-ai-audacity/assets/157512862/9a195888-1c34-4bd8-93c4-41589a03d5dc)

**Comment by vanatf** [comment]
a trancricao nao teve sucesso quando testei

**Comment by vanatf** [comment]
se puder mandar onde encontro por favor , conhecendo aos poucos audacity

**Comment by RyanMetcalfeInt8** [comment]
This is the log that you were already sending contents of, and you were just taking screenshots of it. I'm just asking you to collect the log after a single try with noise-suppression.

**Comment by cesar-correa-souza** [comment]
[Erro Audacity_OpenVINO.pdf](https://github.com/intel/openvino-plugins-ai-audacity/files/14069665/Erro.Audacity_OpenVINO.pdf)

**Comment by RyanMetcalfeInt8** [comment]
Hi @cesar-correa-souza,

Could you give me some details of your system setup, such as Windows version and CPU version?

It's possible that not having distributing a signed DLL may cause issues -- I'm not too sure actually. I haven't encountered any issues like this so far.

Thanks,
Ryan

**Comment by cesar-correa-souza** [comment]
![imagem](https://github.com/intel/openvino-plugins-ai-audacity/assets/157849682/93451834-e909-4030-a5be-a4597fb82505)

**Comment by cesar-correa-souza** [comment]
Sorry to use an image, but I thought it was faster.
Note: Translated using the GOOGLE tool.

**Comment by RyanMetcalfeInt8** [comment]
Thanks @cesar-correa-souza.

I'm not exactly sure what is going wrong in your case, but there are two potential issues.
1. You're using Windows 7 -- I don't know if these DLL's are compatible with this version of Windows.
2. Your CPU appears to be quite old, and I don't know if it would have the right instruction sets to support running this module.

Do you have anything more recent (OS, or hardware) to try on?

Thanks,
Ryan

**Comment by cesar-correa-souza** [comment]
Hi @RyanMetcalfeInt8

Unfortunately not.
I only have this machine.
I already suspected that this could be an (insoluble) problem.
Thank you for your dedication and time in trying to resolve this. Next time maybe.

Thank you for your attention,
Cesar Souza.



Translated into English by Google tool
​

**Comment by RyanMetcalfeInt8** [comment]
Hi @cesar-correa-souza,

Just to close out this issue. I think it's due to your CPU lacking AVX / AVX2 instruction set support.

Thanks,
Ryan

**Comment by Gutierrez7** [comment]
![Captura de tela 2024-08-29 135321](https://github.com/user-attachments/assets/c8bf8bac-0553-4819-a14e-d2b646352f68)

**Comment by Gutierrez7** [comment]
O que pode ser isso?

**Comment by RyanMetcalfeInt8** [comment]
Hmm, which version of Audacity are you using, and which version of these plugins did you install?
