### ISSUE TITLE
SuperResolution doesn't seem available on Linux 3.7.1 built from source

### ISSUE THREAD

**Issue by dankamongmen** [intel/openvino-plugins-ai-audacity#340]
I'm probably doing something wrong (or even simply missing the feature in the UI), but I don't seem to have SuperResolution in my freshly built OpenVINO on Debian Unstable linux.

I built from current source of Audacity and OpenVINO-plugins-ai-audacity. All other expected features (separation, suppression, whisper) appear and seem to function, but I don't see SuperResolution anywhere. I believe I have contents set up properly in `/usr/local/lib/openvino-models`. I don't see any error messages in the console.

Is there any guide to using/debugging this feature? Thanks!

**Comment by RyanMetcalfeInt8** [comment]
Hey @dankamongmen!

Hmm, so you built from latest master branch and don't see it? It should show up in 'Effects' menu (next to music separation, and noise suppression):
![image](https://github.com/user-attachments/assets/15822fc7-4db6-435d-b4cc-b23b4fd77105)

I guess can you can double check that the `mod-openvino` src folder that you copied into Audacity src tree includes the files listed here: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/mod-openvino/CMakeLists.txt#L52

**Comment by dankamongmen** [comment]
> And by the way, content of /usr/local/lib/openvino-models shouldn't really affect the visibility of Super Res in the Effects menu.

i figured, just stuffing in details.

yeah, i've definitely only got two options in that menu.

![2024-12-18-223809_3440x1440_scrot](https://github.com/user-attachments/assets/641c6b49-30ba-4792-ab95-d2bcb8861b41)

let me dig around in the source and look for conditionals...thanks for the quick reply!

**Comment by dankamongmen** [comment]
hrmm i see a file for each effect, save SuperResolution, in my source:

```sh
[schwarzgerat](0) $ ls mod-openvino/
build           htdemucs.h  noise_suppression         OVMusicGenerationLLM.h  OVNoiseSuppression.cpp  OVWhisperTranscription.cpp
CMakeLists.txt  ittutils    OpenVINO.cpp              OVMusicSeparation.cpp   OVNoiseSuppression.h    OVWhisperTranscription.h
htdemucs.cpp    musicgen    OVMusicGenerationLLM.cpp  OVMusicSeparation.h     OVStringUtils.h
[schwarzgerat](0) $ 
```

this likewise seems sus:

```
[schwarzgerat](0) $ grep -ri 'ai effects' *
mod-openvino/OVWhisperTranscription.cpp:   return XO("OpenVINO AI Effects");
mod-openvino/OVMusicSeparation.cpp:   return XO("OpenVINO AI Effects");
mod-openvino/OVNoiseSuppression.cpp:   return XO("OpenVINO AI Effects");
mod-openvino/OVMusicGenerationLLM.cpp:   return XO("OpenVINO AI Effects");
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
as in, i have exactly four hits for `ai effects`, and they're the four i see in my menus, with SuperResolution conspicuously absent

**Comment by dankamongmen** [comment]
jfc, my checkout was somehow old. i thought i just grabbed it yesterday. ignore me.

**Comment by dankamongmen** [comment]
confirmed SuperResolution now shows up in my Effects menu. audacity 3.7.1-20241218

**Comment by dankamongmen** [comment]
ahhh, initial experimentation is very promising! i was a bit dismayed by the somewhat washed-out output using MusicSeparator to strip a vocal section, but pushing that result through SuperResolution really pumps the vocals back up! alright, let's violate some copyrights!

**Comment by RyanMetcalfeInt8** [comment]
Awesome, glad you were able to get it working -- and thrilled that you also found it useful!
