### ISSUE TITLE
[R4.1] AudioSR not available

### ISSUE THREAD

**Issue by MarcoRavich** [intel/openvino-plugins-ai-audacity#343]
Hi there,
yesterday I've installed the new 4.1 into Audacity 3.7.1 with these settings:
![OVinstall](https://github.com/user-attachments/assets/81d3c190-9c77-4d61-860e-7f39092a944e)

But no SR options:
![noASR](https://github.com/user-attachments/assets/42bc0d01-b6e6-4a8e-9b78-702bcc25711b)

Of course tried to reinstall but the option isn't displayed anyway.

However these are models in Audacity\openvino-models dir:
![OVmodels](https://github.com/user-attachments/assets/64307957-545a-4467-8e8e-f04d1ae93931)

Did I do something wrong?

**Comment by RyanMetcalfeInt8** [comment]
Hi @MarcoRavich,

You're not doing anything wrong -- the last release (4.1) did not yet contain the latest SR features. We are planning to post a new release later today that includes this new feature. Stay tuned!

**Comment by RyanMetcalfeInt8** [comment]
Okay, new release is posted! https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.7.1-R4.2

Very interested to hear your thoughts!
