### ISSUE TITLE
Request for a Custom Audacity Plug-In to Generate Sequential Tones from Multiple Frequencies

### ISSUE THREAD

**Issue by eemanee** [intel/openvino-plugins-ai-audacity#347]
Good day,
In Audacity, the generate tone can take in only one input. is there (can you create) a plug-in that can input many frequencies (separated by commas; spaces; or both)? The tones will be generated and appended sequentially and the resulting audio will play all tones one after the other. All other settings will remain unchanged except for the duration. It will now be the duration of each tone. I would like to be able to copy and paste up to ten thousand (10,000) frequency values.
 I know nothing about coding

**Comment by RyanMetcalfeInt8** [comment]
Hi @eemanee, for this project we specialize in AI-related features. This request might be better suited for the base Audacity project (https://github.com/audacity/audacity), as it seems most related to their existing 'Generate tone' feature (but with more customization). I would recommend that you file an issue over there, or create a new thread in the Audacity forum: https://forum.audacityteam.org/

Perhaps someone over there is willing to help. thanks!
