### ISSUE TITLE
Unsupported OS: arch

### ISSUE THREAD

**Issue by cooldudeseven7Dev** [intel/openvino-plugins-ai-audacity#35]
I use arch linux, but running build instructions for linux simply gives the error: `unsupported OS: arch.`

Please add support or give an alt. are there .ny files?

**Comment by RyanMetcalfeInt8** [comment]
Hi @cooldudeseven7Dev,

What step gives this ```unsupported OS: arch``` error? Can you provide more detail?

These plugins are not available as .ny files.

**Comment by RyanMetcalfeInt8** [comment]
Hi @cooldudeseven7Dev,

I haven't used OpenVINO on arch linux before, so you may need to research a method for enabling OpenVINO on that distro. You can probably file a question on OpenVINO issues page (https://github.com/openvinotoolkit/openvino/issues) to see if there is some best known method to enable OpenVINO on arch linux.

Thanks,
Ryan

**Comment by cooldudeseven7Dev** [comment]
> Hi @cooldudeseven7Dev,
> 
> I haven't used OpenVINO on arch linux before, so you may need to research a method for enabling OpenVINO on that distro. You can probably file a question on OpenVINO issues page (https://github.com/openvinotoolkit/openvino/issues) to see if there is some best known method to enable OpenVINO on arch linux.
> 
> Thanks, Ryan

Thank you!
