### ISSUE TITLE
transcription effect does not appear after installing v3.7.1-64bit

### ISSUE THREAD

**Issue by t2ibrahim** [intel/openvino-plugins-ai-audacity#350]
After installing (audacity-win-3.7.1-64bit) and (audacity-win-v3.7.1-R4.2-64bit-OpenVINO-AI-Plugins) with the objective of using AUDIO TRANSCRIPTION feature..

and following the instructions to (1) enable the module for the openvino plugin under preferences, and (2) restarting the audacity app, and (3) importing the audio file, and (4) selecting the Audio Track

ISSUE: under "Effect" --> OpenVINO AI --> CANT FIND TRANSCRIPTION.. only see three option: Music Separation, Noise Suppression, Super Resolution

**Comment by RyanMetcalfeInt8** [comment]
Hi @t2ibrahim,

Transcription is found under 'Analyzers' menu. Thanks!

**Comment by t2ibrahim** [comment]
Your prompt response is greatly appreciated.. U can tell I'm a novice user :) 
Thanks!
