### ISSUE TITLE
Failed to load multiple shared library (The dreaded error 126)

### ISSUE THREAD

**Issue by Meowdoleon** [intel/openvino-plugins-ai-audacity#36]
I am on Windows 10, I have the latest VC redist, on v3.4.2-R1 with Audacity 3.4.2.

I got the following error log when I try to use any of the OpenVino function (Music Separation, Music Style Remix and Noise Suppression):
12:20:54: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
12:20:54: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
12:20:54: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
12:20:54: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
12:20:54: Error: Failed to load shared library 'avformat-55.dll' (error 126: The specified module could not be found.)
12:21:00: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"

I am using my GPU, which is an RX 580.

Also yes, I did install it correctly (I copied the content inside the two folder on the root of the Audacity folder)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/4290639/a8da6353-c080-4fc7-97fb-fe504c185a1d)

**Comment by RyanMetcalfeInt8** [comment]
Hi @Meowdoleon, those errors are unrelated to this plugin. Even with 'vanilla' Audacity 3.4.2 (without installing these OpenVINO plugins), I get those errors as well. I think you can ignore them. 

The OpenVINO effects are working?

**Comment by Meowdoleon** [comment]
No, they are not that is the issue :/
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/4290639/10dac8ee-8bc3-4084-8ec5-9b3c2dd75900)

**Comment by Meowdoleon** [comment]
Aaaah I got it working.

**Comment by RyanMetcalfeInt8** [comment]
@Meowdoleon,

Glad you got it working. I can probably update the instructions to be more clear, but doesn't the installation video demonstrate this very clearly?

Thanks!
Ryan

**Comment by Meowdoleon** [comment]
Well... The video does not work for me 😅
