### ISSUE TITLE
rotina de inicialização da biblioteca de vínculo dinâmico 

### ISSUE THREAD

**Issue by ADNILSONSANBRI** [intel/openvino-plugins-ai-audacity#37]
Uma rotina de inicialização da biblioteca de vínculo dinâmico (dll) falhou

**Comment by RyanMetcalfeInt8** [comment]
Hi @ADNILSONSANBRI,

I think this is a duplicate of this issue (https://github.com/intel/openvino-plugins-ai-audacity/issues/8), which I am still trying to determine the reason. 

I'll probably close this issue as duplicate, but can you please share some system info such as CPU version & Windows version? Thanks!

**Comment by RyanMetcalfeInt8** [comment]
closing as duplicate
