### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by VamuveTV** [intel/openvino-plugins-ai-audacity#38]
Does it runs on a AMD ?

I read that OpenVino does not have support for AMD yet, but someone seems to managed to make it work properly. 

https://github.com/blakeblackshear/frigate/discussions/9417

I have no idea, if this will also work too for the Audacity plugins using OpenVno. Someone tested it ?

**Comment by RyanMetcalfeInt8** [comment]
You should be able to run on AMD CPU without any issues.
