### ISSUE TITLE
Transcribe and Translate doesn't work properly

### ISSUE THREAD

**Issue by odorizzioficial** [intel/openvino-plugins-ai-audacity#40]
Hi, the transcribe plugin isn't working, I'm from Brazil, I tested it in my language and in English and the same problem happens, I'm using Windows 10 pro

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/110546717/817f5dbd-c10c-40cd-8b0d-f91201030382)

**Comment by RyanMetcalfeInt8** [comment]
Hi @odorizzioficial,

Hmm, strange -- I haven't seen any reports of this kind of issue yet. Can you give me some details of your hardware setup (Just CPU model is fine).

Thanks,
Ryan

**Comment by odorizzioficial** [comment]
It's a normal Intel i7-7700 without the K, the installation was done correctly according to the video

**Comment by RyanMetcalfeInt8** [comment]
Got it, thanks -- I believe running with this processor should give ability to run with either CPU or GPU. Do both of those devices show up in the device selection drop-down? If so, does the issue occur for both?

**Comment by odorizzioficial** [comment]
Yes, I tested it with both the GPU and the CPU, the GPU is an RTX 2060, when I apply it to translate it loads very quickly and remains without translation or that 0 value appears.

**Comment by RyanMetcalfeInt8** [comment]
Thanks -- So CPU also gives that 0 value?

**Comment by odorizzioficial** [comment]
Yes, both, GPU and CPU

**Comment by RyanMetcalfeInt8** [comment]
Hi @odorizzioficial,

Sorry I never got back to you on this one... when you get a chance, can you try on the latest release, found here?

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Thanks!
Ryan

**Comment by odorizzioficial** [comment]
Hello, it is failing to open OPEN, I reinstalled Audacity and the same problem occurs
![2024-05-04_00-45_1](https://github.com/intel/openvino-plugins-ai-audacity/assets/110546717/a0bc25fc-4510-480d-be5c-5af8b205a921)
![2024-05-04_00-45](https://github.com/intel/openvino-plugins-ai-audacity/assets/110546717/c68e4b75-94cd-4a5f-9b4f-64e4f011e8ec)

**Comment by odorizzioficial** [comment]
https://github.com/intel/openvino-plugins-ai-audacity/assets/110546717/8bf09a6d-3e51-47b0-8008-555f0a686b70

**Comment by RyanMetcalfeInt8** [comment]
Hi @odorizzioficial,

Make sure that you are using the exact version of Audacity that is listed in the release notes. For example, for the latest release (https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1), you need to be using Audacity 3.5.1, otherwise you'll get this kind of version mismatch error that you are seeing.

Thanks,
Ryan

**Comment by odorizzioficial** [comment]
Now my friend, but the first audio I tested transcribed correctly, but the other tests I did didn't.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/110546717/8574c4f5-94f0-42f5-b0ca-0587dd5dbc7a)
