### ISSUE TITLE
Copy Audacity AI plugin zip files

### ISSUE THREAD

**Issue by halrose2** [intel/openvino-plugins-ai-audacity#41]
The installation instructions (the MP4) need to include a step to unblock the .zip files before copying them to the /program files/Audacity folder - saves one a lot of post-processing. Just saying.

HJR

**Comment by RyanMetcalfeInt8** [comment]
Hi @halrose2,

Thanks for the feedback. I didn't really understand though -- what do you mean by 'unblock' the .zip files?

**Comment by RyanMetcalfeInt8** [comment]
Nevermind -- I see what you mean now. I didn't realize that folks needed to do that! Probably because the video that I recorded didn't download the zip (as I had just created it). I will keep this in mind. Thanks again!

**Comment by halrose2** [comment]
So my machine is a 64-bit Windows 11 machine. The first time I copied the files from the .zip file to the destination folder, when I right clicked one of the copied files and selected properties from the context menu, there was a warning that “this file has been copied from another computer and has been blocked” and a check box to unblock the file. So I deleted the two folders that had been copied over, unblocked the original zip files (under properties) and then re-copied everything using the option to overwrite the existing files. A couple extra steps that could have been avoided had I checked the properties of the zip files before copying.

Harold
Sent from my iPhone

On Feb 6, 2024, at 9:58 AM, Ryan Metcalfe ***@***.***> wrote:

﻿

Hi @halrose2<https://github.com/halrose2>,

Thanks for the feedback. I didn't really understand though -- what do you mean by 'unblock' the .zip files?

**Comment by halrose2** [comment]
LOL, I just now saw this email.

Harold
Sent from my iPhone

On Feb 6, 2024, at 10:02 AM, Ryan Metcalfe ***@***.***> wrote:

﻿

Nevermind -- I see what you mean now. I didn't realize that folks needed to do that! Probably because the video that I recorded didn't download the zip (as I had just created it). I will keep this in mind. Thanks again!

**Comment by RyanMetcalfeInt8** [comment]
> So my machine is a 64-bit Windows 11 machine. The first time I copied the files from the .zip file to the destination folder, when I right clicked one of the copied files and selected properties from the context menu, there was a warning that “this file has been copied from another computer and has been blocked” and a check box to unblock the file. So I deleted the two folders that had been copied over, unblocked the original zip files (under properties) and then re-copied everything using the option to overwrite the existing files. A couple extra steps that could have been avoided had I checked the properties of the zip files before copying.

Oh interesting -- So in this case it actually let you extract the files to the destination folder, but it marked all of them as 'blocked' -- which made them unusable? Did I understand that right? 

I haven't actually observed this behavior on any of the systems that I went through the download / install process -- but perhaps it's enabled with some extra security options under Windows settings.

**Comment by halrose2** [comment]
It’s a feature 😆
Sent from my iPhone

On Feb 6, 2024, at 10:55 AM, Ryan Metcalfe ***@***.***> wrote:

﻿

So my machine is a 64-bit Windows 11 machine. The first time I copied the files from the .zip file to the destination folder, when I right clicked one of the copied files and selected properties from the context menu, there was a warning that “this file has been copied from another computer and has been blocked” and a check box to unblock the file. So I deleted the two folders that had been copied over, unblocked the original zip files (under properties) and then re-copied everything using the option to overwrite the existing files. A couple extra steps that could have been avoided had I checked the properties of the zip files before copying.

Oh interesting -- So in this case it actually let you extract the files to the destination folder, but it marked all of them as 'blocked' -- which made them unusable? Did I understand that right?

I haven't actually observed this behavior on any of the systems that I went through the download / install process -- but perhaps it's enabled with some extra security options under Windows settings.

**Comment by MarcD501** [comment]
Copied both unzipped folders to Audacity installation folder but when opening preferences in Audacity they dont show up in the modules tab. Should I copy the content to the Audacity folder or the modules folder? Thanks for your advice.

**Comment by halrose2** [comment]
I am giving directions for a 64 bit Windows 11 machine for the 64 bit version of Audacity.

There is a really helpful video that walks through the process. If you have already copied the .zip files to the "?:/program files/audacity" folder you can leave them there.


  1.  If you are on a Windows machine, first check the properties of the zip files (right mouse click and select properties from the context menu). You might see a message that says something like "this file has been copied from another computer..." and a checkbox with the label Unblock. If that is the case, check the "Unblock" check box and click the "apply" button. Do so for both .zip files. If you don't see this in the properties pop up window then you can proceed to the next step.


  1.  Then right click each file and select "extract all..." from the pop up menu. This will bring up another pop up window with a suggested location to extract to. Be sure that the contents are extracted to the current location ("?:/program files/audacity")

Hope this helps
Harold
________________________________

**Comment by RyanMetcalfeInt8** [comment]
Hi all,

We have posted an updated release which uses an installer: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

So, you shouldn't have to deal with this zip file nonsense anymore. I'll close this issue, but feel free to keep commenting if you have questions or other feedback. Thanks!
