### ISSUE TITLE
Unable to load the module

### ISSUE THREAD

**Issue by cparker24** [intel/openvino-plugins-ai-audacity#42]
After following the installation steps I get the error "Unable to load the "mod-openvino" module. Error: %1 is not a valid Win32 application." Is this because my Audacity is installed in Program Files x86 instead of just Program Files?

**Comment by RyanMetcalfeInt8** [comment]
Hi @cparker24, 

Do you have the 32-bit version of Audacity installed? It sounds like this may be the case, if it is installed in 'Program Files x86'. 

As these are 64-bit plugins, you need to use them with 64-bit Audacity.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @cparker24, any updates?

**Comment by cparker24** [comment]
I installed the 64 but version and it worked like a charm. Thanks!

**Comment by RyanMetcalfeInt8** [comment]
perfect, glad to hear that! Cheers!
