### ISSUE TITLE
Enabled but not appearing

### ISSUE THREAD

**Issue by Unreadhyperion** [intel/openvino-plugins-ai-audacity#43]
When I go to Edit - Preferences - Modules - Mod-Openvino has been set to Enabled. I've closed out and reopened (a few times now) and still no "OpenVINO AI Effects" in my effects menu. When I load Plugin Manager no OpenVino is listed either. Using the same install of audacity as provided on page. Windows 10, 64 Bit.

**Comment by Unreadhyperion** [comment]
Ah I uninstalled Audacity and reinstalled and that appears to have worked.

**Comment by RyanMetcalfeInt8** [comment]
Glad to hear it resolved itself! Cheers!
