### ISSUE TITLE
AMD Ryzen & Radeon compatibility

### ISSUE THREAD

**Issue by NathanRichards007** [intel/openvino-plugins-ai-audacity#46]
I am wondering if the AMD Ryzen cpu & Radeon gpu are supported with the plugin or for the cpu case, if its for Intel platform only (like on the main OpenVINO toolkit)?

I am interested in using the plugin to help out with some extended mixes & certain other audible things.

**Comment by RyanMetcalfeInt8** [comment]
Hi @NathanRichards007,

These plugins should support anything that OpenVINO toolkit supports -- I think this would cover AMD Ryzen cpu, but I'm not too sure about Radeon gpu. OpenVINO GPU plugin uses OpenCL at its core, so if Radeon GPU supports OpenCL it might work.

You'll just have to try it out.

Cheers!
