### ISSUE TITLE
Music Generation failed 

### ISSUE THREAD

**Issue by breadteam** [intel/openvino-plugins-ai-audacity#47]
Hey folks - I have tried to use the OpenVINO Music Generation feature (from under the Generate menu) multiple times.

I did the thing where I "unblocked" the .zip files and moved them into Audacity. Still fails.
Can you give me any advice? Is there anything I should change to make this work? I even tried running Audacity as Administrator.

Here's what I'm on:

Audacity 3.4.2 64-bit

Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	32.0 GB (31.7 GB usable)

Edition	Windows 11 Home
Version	23H2
Installed on	‎6/‎15/‎2022
OS build	22635.3139
Experience	Windows Feature Experience Pack 1000.22685.1000.0

Downloaded and installed Audacity and the OpenVINO module/plugin today, Feb 9, 2024

Error from the log:

14:54:23: Audacity 3.4.2
14:54:23: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
14:54:23: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
14:54:23: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
14:54:23: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
14:54:23: Error: Failed to load shared library 'avformat-55.dll' (error 126: The specified module could not be found.)
14:54:26: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
14:54:26: Error: Failed to load shared library 'avformat-60.dll' (error 126: The specified module could not be found.)
14:54:26: Error: Failed to load shared library 'avformat-59.dll' (error 126: The specified module could not be found.)
14:54:26: Error: Failed to load shared library 'avformat-58.dll' (error 126: The specified module could not be found.)
14:54:26: Error: Failed to load shared library 'avformat-57.dll' (error 126: The specified module could not be found.)
14:54:26: Error: Failed to load shared library 'avformat-55.dll' (error 126: The specified module could not be found.)
14:55:28: Error: In Music Generation, exception: If num_output_segments is set, it must be <= num_interpolation_steps
14:55:31: Operation 'OpenVINO Music Generation' took 49.334000 seconds. Poll was called 98 times and took 0.240555 seconds. Yield was called 98 times and took 0.151529 seconds.

**Comment by breadteam** [comment]
Hmmm ... okay I got it to work. I looked at the "Music separation failed" issue and their logs looked similar to mine. Somebody recommended uninstalling Audacity and reinstalling everything all over.

I did that and it still failed in the same way.

My "prompt" was: "goofy playful downtempo beat" with everything else using the default settings. This is what I had been using the whole time.

So I changed the prompt to just one word: "goofy" and it failed again.

So I tried again with the mode as "Advanced" (everything else with the default settings) after hitting "Unload Models" and this time it worked.

**Comment by RyanMetcalfeInt8** [comment]
Hi @breadteam,

Hmm, strange. Is it consistently working now? I'm trying to think of why you would have needed to click 'unload models' for it to work.

Thanks!

**Comment by DIE020HARDZ** [comment]
So, it seems that the problems only occurred when I used simple mode in Music Generation.
When I used Advanced mode, everything was fine.

**Comment by kilgenmus** [comment]
I am getting the same error with Simple, also solved with Advanced but I think it is related to the **length of the generation** & **num_interpolation_steps** set. You need to make sure the interpolation steps (* 5) exceed the total time you want it to run. 

Playing around with it I couldn't figure out if interpolation step change is meant to set/modify the duration, but since duration can be edited afterwards we see the error.

**Comment by doogle758** [comment]
how do u turn on advanced mode?

**Comment by yeyi913** [comment]
Does anyone know how to solve my problem?

9:25:35: Audacity 3.4.2
9:25:35: FFmpeg libraries loaded successfully from: C:\Program Files\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
9:25:41: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
9:25:41: FFmpeg libraries loaded successfully from: C:\Program Files\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
9:29:39: Error: In Music Generation, exception: If num_output_segments is set, it must be <= num_interpolation_steps
9:29:41: Operation 'OpenVINO Music Generation' took 5.003000 seconds. Poll was called 10 times and took 0.018326 seconds. Yield was called 10 times and took 0.009556 seconds.

What can be problem?
Start Prompt (in Advanced Mode using Chinese input):
In the depths of the night, neon lights flash, and the bustling streets are filled with a dense atmosphere of electronic music. A unique melody, a blend of traditional Chinese melodies and futuristic electronic bass, rises quietly. The notes dance, like fireworks exploding, dazzling and captivating.
The strings are gently plucked, and the melodious sound of the guzheng intertwines with the modern feel of the electronic synthesizer, creating a unique sense of time and space. The melody gradually rises, as if traversing a millennium-old temporal tunnel, perfectly fusing the ancient oriental charm with modern electronic music.
The drum beats grow stronger, and the bass thumps deeply and powerfully, like the heartbeat of the city, pulsating in every corner. The electronic effects soar like meteors across the night sky, leaving behind a brilliant glow.

End Prompt:
The music gradually builds to a climax, the melody more intense and passionate, like a raging river, unstoppable. Each note is filled with strength and emotion, making one feel as if they are immersed in a vibrant future world.
Finally, the music fades away in a long, lingering coda, like the serene night sky after a fireworks display. That unique melody, that music that blends Chinese charm with futuristic electronic bass, is like a beautiful dream, leaving a lasting impression that is difficult to forget.

（Below is the Chinese translation）
Start Prompt：
深夜的都市，霓虹灯闪烁，繁华的街头弥漫着浓厚的电子音乐氛围。一曲独特的旋律，融合了中式旋律与未来电子Bass，悄然响起。音符跳跃，如同烟花绽放，绚烂夺目。
琴弦轻拨，古筝的悠扬与电子合成器的现代感交织在一起，创造出一种独特的时空感。旋律逐渐升高，仿佛穿越千年的时空隧道，将古老的东方韵味与现代电子乐完美融合。
鼓点渐强，Bass音深沉而有力，如同都市的心跳，跳动在每一个角落。电子音效如同流星划过夜空，留下璀璨的光芒。
End Prompt：
乐曲渐入高潮，旋律更加激昂，如同江河奔腾，势不可挡。每一个音符都充满了力量与激情，让人仿佛置身于一个充满活力的未来世界。
最终，乐曲在一段悠长的尾声中缓缓落下，如同烟花绽放后的宁静夜空。那独特的旋律，那融合了中式韵味与未来电子Bass的音乐，如同一个美丽的梦，让人久久难以忘怀。

**Comment by RyanMetcalfeInt8** [comment]
Hi all,

We've replaced the Riffusion-based Music Generation feature with a version that is powered by MusicGen LLM (from Meta). Take a look at the [documentation page](https://github.com/intel/openvino-plugins-ai-audacity/blob/43de3af6087480ab2030404aba3f122fafa9bd73/doc/feature_doc/music_generation/README.md) which include a couple of short videos that demonstrate Music Generation & Continuation features.

Let us know what you think!

Thanks,
Ryan
