### ISSUE TITLE
Audacity failed to launch after module enable

### ISSUE THREAD

**Issue by DJPasTime** [intel/openvino-plugins-ai-audacity#50]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/159821344/1d037587-1e3d-4687-81bd-889b327ed55d)

Followed the install instructions;
- extracted the 2 .zip files and copied contents into "C:\Program Files (x86)\Audacity"
- launched audacity
- Changed the mosule from "new" to "enabled"
- Error "Unable to load the "mod-openvino" module." "Error: %1 is not a valid Win32 application." (screenshot attached)

**Comment by RyanMetcalfeInt8** [comment]
Hmm, do you have 64-bit version of Audacity installed?

**Comment by DJPasTime** [comment]
32-bit

**Comment by RyanMetcalfeInt8** [comment]
These plugins require you to have 64-bit version of Audacity installed.

**Comment by DJPasTime** [comment]
Ah, thank you for your help.

**Comment by RyanMetcalfeInt8** [comment]
No problem!
