### ISSUE TITLE
Error: "Attempting to initialize the following efect

### ISSUE THREAD

**Issue by kendevine1980** [intel/openvino-plugins-ai-audacity#51]
![VINO error](https://github.com/intel/openvino-plugins-ai-audacity/assets/159651795/14de9451-e4f8-48f8-806c-09b5edda7c47)
![Computer Info](https://github.com/intel/openvino-plugins-ai-audacity/assets/159651795/fa6d3a1b-09f4-4127-a988-9be4c9fb2ab8)

I'd been using the Music Separation tool several times without any issue, then suddenly got this error. I restarted my computer, but got the same message.

How can I resolve this?

**Comment by RyanMetcalfeInt8** [comment]
Hi @kendevine1980,

After you receive that error message, can you copy and paste the contents of Help -> Show Log? 

Thanks,
Ryan

**Comment by kendevine1980** [comment]
Sure thing. Here you go:

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/159651795/4ce435b4-7c11-4aca-8ea3-cbbe29e87ab9)

**Comment by RyanMetcalfeInt8** [comment]
Hmm, looks like you're running Audacity 2.1.2? These plugins only work when running Audacity 3.4.2. Do you have a couple of Audacity installations or something, as you said it was previously working.

**Comment by RyanMetcalfeInt8** [comment]
Perfect, glad you were able to fix it! And also happy that you're finding these plugins useful. I'll close this issue, feel free to submit another if you have any other issues / questions. Cheers!
