### ISSUE TITLE
Whisper Transcribe doesn't work.

### ISSUE THREAD

**Issue by komutesu** [intel/openvino-plugins-ai-audacity#53]
Hello developers,

I'm Komutesu, and I want to express my gratitude for the fantastic software you've provided. Recently, I encountered an error when trying to launch the software and am seeking your assistance via GitHub.

The error message is as follows:
[exception code 0xc000001d.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/14274958/exception.code.0xc000001d.txt)

When I push APPLY transcripsion, audacity stops. I get the following code, but it also says send to audacity failed lol.
I have tried changing the device, changing the language, adding ffmpeg for audacity, etc. and get the same error.

Details about my environment:

OS: Windows 10 Pro 22H2
Software version: audacity 3.4.2
If you have any suggestions or if there are specific steps I should follow to resolve this issue, please let me know. Additionally, any guidance on providing further information would be appreciated.

Thank you for your time and support.

Best regards,

Komutesu

**Comment by RyanMetcalfeInt8** [comment]
Hi @komutesu,

Could you give the CPU version that you are using? From the exception code log that you posted, it says "family 6 model 58 stepping 9", which I *think* is ```Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz```. Just double check that.

If that is your CPU, my initial guess as to why it crashed with an ILLEGAL_INSTRUCTION exception, is that the transcription plugin uses whisper.cpp, which has been compiled with AVX2 support. Your CPU is pretty old, and doesn't support AVX2 instructions (https://www.intel.com/content/www/us/en/products/sku/65693/intel-core-i33220-processor-3m-cache-3-30-ghz/specifications.html -- look under **Instruction Set Extensions**).

I *think* this issue would be specific to *Whisper Transcription* -- Do the other effects (such as noise suppression, music separation) work?

Ryan

**Comment by komutesu** [comment]
@RyanMetcalfeInt8, thank you very much for your kind attention!

My CPU is Intel Core i7-3770K @ 3.50GHz and was not AVX2 compliant! solved! Thank you very much.
I also stopped noise suppression. It is refreshing to know the cause. I think I will buy a new computer lol.
