### ISSUE TITLE
Question: How to Add Whisper Models

### ISSUE THREAD

**Issue by AndrewJacksonZA** [intel/openvino-plugins-ai-audacity#58]
Hello

Firstly, thank you for your and Intel's FANTASTIC work giving back to the community, through things like your work and other initiatives like the GIMP plugins. Thank you!!

How can I add models from https://ggml.ggerganov.com/ or https://huggingface.co/ggerganov/whisper.cpp/tree/main please? I see that you have an XML file and what appears to be a special "ggml-xxx-encoder-openvino.bin" file.

Alternatively, could you add a download button to the dialog box/a new dialog box, please? It would be much easier for the end users like me!

Edit: Apologies if I'm missing something obvious in the documentation.

Thank you
Andrew Jackson

**Comment by RyanMetcalfeInt8** [comment]
Hi @AndrewJacksonZA,

Thanks for the kind words!

> How can I add models from https://ggml.ggerganov.com/ or https://huggingface.co/ggerganov/whisper.cpp/tree/main please? I see that you have an XML file and what appears to be a special "ggml-xxx-encoder-openvino.bin" file.

Unfortunately, [right now] it's not as easy as downloading other whisper ggml models and dropping them into the models directory. And before I go into the details, I will say that we are working on an updated release that will be much more configurable, including the ability to select different whisper models (like small, medium, etc.).

In the meantime, I'll give some hints as to how to add models in the meantime.. but it will require folks to re-built the plugin... (sorry!)

1. The ggml-xxx-encoder-openvino.xml/bin files that you see are the result of following these steps in whisper.cpp (basically, converting the pytorch whisper encoder model to OpenVINO IR format): https://github.com/ggerganov/whisper.cpp?tab=readme-ov-file#openvino-support  

2. So, one would need to follow those steps for another version of whisper ("small", "small.en", etc.) to generate, for example, ```ggml-small-encoder-openvino.xml/.bin```. These generated files would get dropped into the openvino-models folder, along with the actual ggml file (e.g.  ```ggml-model-whisper-small.bin```)

3. You'll need to append the model version (e.g. "small", "small.en", etc.) to this sting vector: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/mod-openvino/OVWhisperTranscription.cpp#L193 and then build the plugin.

Anyway -- I know it's not as easy as it should be.. but bear with us as we improve this thing :)

> Alternatively, could you add a download button to the dialog box/a new dialog box, please? It would be much easier for the end users like me!

This may not be something that shows up as an option *inside* Audacity itself, but we are working on creating installers that would let you configure additional features / models from there (so still GUI-based).

Cheers!

**Comment by AndrewJacksonZA** [comment]
Thanks man! I'll wait for your update, me setting up my machine to rebuild the extension just isn't an option right now.

P.S. I don't know if you have to abide by a corporate policy for GUI installers, but [NSIS](https://github.com/kichik/nsis) is super flexible and super powerful (and also OSS, in case it matters.) I built a lot of installers back in the day when I was still shipping client-facing software.

**Comment by Tobe2d** [comment]
+1 Cant wait for the update ;-)

**Comment by milenamilka755** [comment]
We need access to (Whisper) ggml-medium.bin  and large. Base model is too weak for good transcription.

**Comment by Ceratopsia** [comment]
Thank you very much for your share, I'm very looking forward to the update, I really need more support with larger models!
Also I would like to ask in this thread, when I use the intel ARC a750 GPU to help run the models, I don't know why Audacity always crashes, but it still works fine when I use the CPU or run the models with intel UHD 730 without the same problem?

**Comment by RyanMetcalfeInt8** [comment]
> Also I would like to ask in this thread, when I use the intel ARC a750 GPU to help run the models, I don't know why Audacity always crashes, but it still works fine when I use the CPU or run the models with intel UHD 730 without the same problem?

Oh wow, really? Is this true only for transcription, or other effects as well?

**Comment by Ceratopsia** [comment]
Also with the same problem in other openvino effect plugins.

**Comment by RyanMetcalfeInt8** [comment]
> Also with the same problem in other openvino effect plugins.

That is strange. I've tried these plugins on A770, and they seemed to work okay. I can see if i can dig up an A750. Are your GPU drivers up to date?

**Comment by RyanMetcalfeInt8** [comment]
Also, @Ceratopsia, can you submit a dedicated issue for this GPU issue? I'd like to track this one separately.

**Comment by Ceratopsia** [comment]
> > Also with the same problem in other openvino effect plugins.
> 
> That is strange. I've tried these plugins on A770, and they seemed to work okay. I can see if i can dig up an A750. Are your GPU drivers up to date?

Yeah, it seems like my driver not the latest because I can't update the latest GPU driver. 
I have tried to update twice and my computer crashed twice and it caused me to reset my system.
![螢幕擷取畫面 2024-03-30 203842](https://github.com/intel/openvino-plugins-ai-audacity/assets/113691030/d8f485be-800e-4909-820b-85c2d87bf899)
![螢幕擷取畫面 2024-03-30 203908](https://github.com/intel/openvino-plugins-ai-audacity/assets/113691030/3985b1aa-690b-478d-be12-580d4aa9f5f3)
![螢幕擷取畫面 2024-03-30 203923](https://github.com/intel/openvino-plugins-ai-audacity/assets/113691030/554dd5f2-b8f1-4c2b-822b-58e1d87f2bc4)

Is driver version 31.0.101.5081 not compatible with this plugins?

**Comment by umitatabek** [comment]
Thanks for the info, we all wait for un apdate for the large model (which is obviously much better for languages other than English). Kdenlive (kdenlive.org) has a support for all different models, may be you can check for their solution. By the way, do you have any plans for stem seperation models update? We also need models for piano and strings seperations... Best regards...

**Comment by mark-wd** [comment]
I find this to be an awesome project, but I was a little sad to see that the larger models are not supported. Running Whisper within a familiar interface and being able to directly edit the outcome is a pretty awesome concept,  but the larger models are necessary for other languages to work properly.

**Comment by umitatabek** [comment]
Thank you for all your efforts. Best regards.

**Comment by RyanMetcalfeInt8** [comment]
Hi @mark-wd, @umitatabek,

The new release is out! 

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

You will be able to select small, medium, and large models to download / install from installer. When you get a chance, give it a try and let me know what you think!

Thanks!
Ryan

**Comment by Ceratopsia** [comment]
I have tried the new release with Openvino Whisper and AI Effect.
It's finally working well on my a750 GPU! 
Thank you so much for solving this problem👍
Do I need to close this issue thread or just keep it on?

**Comment by umitatabek** [comment]
Thank you!

**Comment by mark-wd** [comment]
> Hi @AndrewJacksonZA, @mark-wd, @umitatabek, all,
> 
> The new release is out!
> 
> https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
> 
> You will be able to select small, medium, and large models to download / install from installer. When you get a chance, give it a try and let me know what you think!
> 
> Thanks! Ryan

Wow. The work performed on this version was massive, congratulations. I am testing the features and so far it all looks amazing!

**Comment by mark-wd** [comment]
And wow... Whisper Medium is actually surpringly fast from the GUI, I am getting very similar speeds to just using command line, only with a much more comfortable workflow. Amazing!

**Comment by RyanMetcalfeInt8** [comment]
Thrilled that ya'll are enjoying it!

**Comment by mark-wd** [comment]
> . When you get a chance, give it a try and let me know what you think!
> 
> > 
> 
> I try base and large model and both crash Audacity (CPU and GPU mode)

What does your RAM (not VRAM) look like? These models require a certain amount of free RAM, like a few GB.

**Comment by milenamilka755** [comment]
> > . When you get a chance, give it a try and let me know what you think!
> > > 
> > 
> > 
> > I try base and large model and both crash Audacity (CPU and GPU mode)
> 
> What does your RAM (not VRAM) look like? These models require a certain amount of free RAM, like a few GB.

My computer -32GB RAM so this is not a problem. (old GPU GTX660 2GB)

**Comment by AndrewJacksonZA** [comment]
Brilliant! Thank you @RyanMetcalfeInt8  !! :-)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/47087126/a1ffcd9b-388d-4004-bb91-789126a8ffde)
