### ISSUE TITLE
AI Not supported by Linux?

### ISSUE THREAD

**Issue by genotics** [intel/openvino-plugins-ai-audacity#66]
I copied the contents of the two folders to the snap folder containing Audacity and started Audacity, but I do not see the AI module so cannot enable it. Am I wasting my time?

**Comment by RyanMetcalfeInt8** [comment]
Linux is supported, but you need to build Audacity + the module from source. The instructions are here: https://github.com/intel/openvino-plugins-ai-audacity/blob/v3.4.2-R1/doc/build_doc/linux/README.md

It sounds like you are trying to copy the Windows DLL's into the Linux snap folder. That certainly is not going to work.

**Comment by genotics** [comment]
Thanks Ryan, Actually I have Audacity as an AppImage, since I thought that
this was the most recent version, I presume that the same limitation
applies to AppImage. Much obliged. - Roy

**Comment by genotics** [comment]
Actually I am running Ubuntu v 23 so I guess the plugins won't install. Too bad

**Comment by RyanMetcalfeInt8** [comment]
I mean you can try the build instructions on Ubuntu 23 -- I haven't tried yet on that OS. It may work as is.

**Comment by genotics** [comment]
It definitely won't install on version 24

**Comment by genotics** [comment]
Sorry, I meant 23.10
