### ISSUE TITLE
OpenVINO AI Effects not appearing

### ISSUE THREAD

**Issue by joedale100** [intel/openvino-plugins-ai-audacity#7]
Hi there,

So I followed the different steps. I downloaded and unzipped the two zip files, then copied and pasted them into the Audacity folder. I then enabled the mod-openvino in Preferences/Modules, but when I went to the Effects menu, the OpenVINO AI Effects don't appear. Any advice? I'm running WIndows 10 64 bit with Audacity 3.4.2.

Best wishes

Joe

**Comment by RyanMetcalfeInt8** [comment]
Hi @joedale100,

After changing mod-openvino from *New* to *Enabled* in Preferences/Modules, did you close & re-open Audacity? That step is required to actually get the effects to load.

Thanks,
Ryan

**Comment by joedale100** [comment]
Yes, I did and the new option didn't appear. Thanks for your prompt reply.

**Comment by joedale100** [comment]
It's enabled.

**Comment by joedale100** [comment]
I put the files in Program Files/Audacity/Audacity 3.4.2/Audacity. Would that make a difference? I have Audacity 3.3.3 and 3.4.2 both running on my machine.

**Comment by joedale100** [comment]
As you can see, I have copied and pasted the files across. 
![Screenshot 2023-12-19 200916](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/176bfc8f-6d1c-491c-98de-0a87cf7ee82e)

**Comment by RyanMetcalfeInt8** [comment]
Weird. If 'mod-openvino' shows up under Preferences/Modules, it means that the files were put in the right spot. Also I don't think that having Audacity 3.3.3 installed shouldn't matter. 

So you don't see any OpenVINO features show up in Generate, Effect, or Analyze tabs? Usually if OpenVINO effects don't show up there, there is some error dialog that pops up that gives some notice that the module failed to load.

Is there anything suspicious looking in Help->Diagnostics->Show Log?

**Comment by joedale100** [comment]
Nothing in those menus. Here is a screenshot of the Audacity Log. 
![Screenshot 2023-12-19 201850](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/f035d612-3d29-42a4-9c1a-a1863e6b3058)

**Comment by joedale100** [comment]
As you can see, it is definitely enabled. 
![Screenshot 2023-12-19 202556](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/13124d09-4557-4ece-9a76-119ef9677fb5)

**Comment by RyanMetcalfeInt8** [comment]
Thanks -- very strange. Yeah nothing looks wrong from the log or modules screenshot. Let me find a Windows 10 machine to try this on...

**Comment by joedale100** [comment]
Thanks!

**Comment by RyanMetcalfeInt8** [comment]
Hi @joedale100,

I tried on a Windows 10 machine.. unfortunately, I wasn't able to reproduce the issue still...

Could you share more details about your system setup? CPU version, etc.?

And one thing to check quick:
In ```%appdata%\audacity\audacity.cfg```, do you see 'mod-openvino' entries? For example, mine looks like this:
```
audacity.cfg:mod-openvino=1
audacity.cfg:mod-openvino=C:\\Program Files\\Audacity\\modules\\mod-openvino.dll
audacity.cfg:mod-openvino=2023-12-07T07:57:42
```

Thanks,
Ryan

**Comment by joedale100** [comment]
Hi Ryan,

Here are more details:

Processor	Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

This is what I see 
![Screenshot 2023-12-20 104510](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/18ceaf1a-ce8f-4666-aed6-2b7797817966)

Best wishes

Joe

**Comment by RyanMetcalfeInt8** [comment]
Hi Joe,

Looks like you gave the output of 'lastlog', but I was hoping you could confirm that there are 'mod-openvino' entries in audacity.cfg. 

Thanks,
Ryan

**Comment by joedale100** [comment]
Hi Ryan,

How do I do that?

Best wishes

Joe

**Comment by RyanMetcalfeInt8** [comment]
Hi Joe,

Sorry, you can just open up audacity.cfg with notepad (it's just a plain text file), and then search for 'mod-openvino'. 

Thanks,
Ryan

**Comment by joedale100** [comment]
Does this help? 
![Uploading Screenshot 2023-12-20 133419.jpg…]()

**Comment by joedale100** [comment]
Does this help?
![Screenshot 2023-12-20 133419](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/784b1d86-ab75-446b-8402-6b506cf1e801)

**Comment by RyanMetcalfeInt8** [comment]
Yes, thank you!

So one thing that looks odd to me is that it is showing 'mod-openvino' installed at "C:\Program Files (x86)\Audacity\modules", whereas the rest of the module DLL's are installed at "C:\Program Files\Audacity\modules".

Any idea why that would be? You did mention that you had a couple versions of Audacity loaded.

**Comment by joedale100** [comment]
I first copied and pasted the files into an older version and then clicked on Date Modified to get all the files labelled 19/12/23 and cut and pasted them into the correct folder. Should I delete all those files and try again from scratch?

**Comment by RyanMetcalfeInt8** [comment]
> Should I delete all those files and try again from scratch?

Yes, it might be worth it to start from scratch. When you cut and pasted the files, did you remember to also cut & paste modules/mod-openvino.dll, or is this still sitting in the 'old' Audacity installed location?

**Comment by joedale100** [comment]
I'm not sure. How can I ensure I have?

**Comment by joedale100** [comment]
Here is a screenshot showing the file is in the right place now, but it's still not working. 
![Screenshot 2023-12-20 140028](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/fd0d1cd7-ecc1-41a8-9075-71ad56839ab2)

**Comment by joedale100** [comment]
Hi Ryan,

I've worked out the following prompt for ChatGPT which delineates each speaker nicely. Please transform the provided interview transcript by making the following adjustments:

Remove All Timestamps: Eliminate all timestamps from the transcript to enhance readability.

Consolidate Continuous Speech: Identify each unique speaker and consolidate their continuous speech. Label each section of uninterrupted dialogue with 'Speaker 1', 'Speaker 2', 'Speaker 3', etc., corresponding to each different speaker. Ensure that when the same speaker talks consecutively, their dialogue is grouped under a single label, avoiding repetition of speaker labels for continuous speech.

The goal is to create a clean and coherent transcript that clearly delineates who is speaking and presents their dialogue in an unbroken sequence, making it easier to follow the conversation flow. 

I also found this thread which asks how to export labels to a txt file: https://forum.audacityteam.org/t/export-labels-into-a-custom-text-file/63330

I will ask Steve on the forum if he can help. Thank you so much for your help.

**Comment by RyanMetcalfeInt8** [comment]
Cool, thank you @joedale100 -- please let me know if you need any additional help. Cheers, Ryan

**Comment by joedale100** [comment]
Hi Ryan,

I've now tried to use the OpenVINO Music Generation tool and I just get an error message. Any advice? See attached screenshots including the activity log.
![Screenshot 2023-12-21 151454](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/26cfdf55-7312-400c-9a4d-e32d37f1fd61)
![Screenshot 2023-12-21 151342](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/a7621489-9122-42c9-8446-babab9989a93)

**Comment by RyanMetcalfeInt8** [comment]
Hi @joedale100,

Looks like there was some error prepping the model to run on your GPU (Specifically, the OpenCL compilation for some kernel failed). This typically happens if you are using old / out of date GPU drivers. You can check to see if there are updated drivers available for your system.

The other option is to switch 'GPU' to 'CPU' for the device entries. My recommendation would be to try generating only a few seconds to start with, as I think generation might take some time on your 7th Gen Core i7.

Thanks,
Ryan

**Comment by joedale100** [comment]
Hi Ryan, 

Even 1 second gets an error message. How do I update my GPU drivers? My PC is only about 3 years old.
![Screenshot 2023-12-21 194613](https://github.com/intel/openvino-plugins-ai-audacity/assets/154364706/a14059e6-f088-4e40-9fce-b7402fbc1ee2)

**Comment by RyanMetcalfeInt8** [comment]
Hi @joedale100,

Right, the error is going to happen regardless of duration length as it happens while prepping the device (before it starts generating anything).

For the 'device' options, you can try to change the things set to "GPU" (like Unet+ Device, etc.) to "CPU" to try and work around the issue. 

I think GPU driver updates usually happen as part of Windows updates. But depending on the brand of your system (Dell, Lenovo, etc.), you can probably try searching for updated drivers on the specific website (under support).

Thanks,
Ryan

**Comment by joedale100** [comment]
I changed everything to CPU and it's working now. Thanks!

**Comment by joedale100** [comment]
Hi Ryan,

I've written the following instructions to create a transcription using a macro in Audacity:

Download and enable OpenVINO modules

Download the two zip files below (Audacity-OpenVINO-Module-3.4.2-R1.zip, openvino-models.zip)
Copy the contents of these zip files to the folder where Audacity.exe has been installed. E.g. C:\Program Files\Audacity.
After all files files from both zip files have been copied, run Audacity.exe.
Inside of Audacity, go to Edit -> Preferences, select Modules, change mod-openvino from New to Enabled, and press OK.
Close Audacity.
Re-Open Audacity.
Your OpenVINO modules should now be enabled. You can check this by making sure that OpenVINO AI Effects show up in Effects menu and Analyse menu.
https://github.com/intel/openvino-plugins-ai-audacity?tab=readme-ov-file

Download and enable exportlabels plugin

Go to https://forum.audacityteam.org/t/export-labels/54745 and download exportlabels.ny file. 
Copy and paste it into C:/Program Files/Audacity/Plug-Ins folder.
Go to Tools/Nyquist Plugin Installer
Click on Browse and go to C:\Program Files\Audacity\Plug-Ins\exportlabels.ny
Click Open
Click Apply

Create Transcribe Macro

Go to Tools/Macro Manager
Click New
Enter name of new macro e.g Transcribe
C.ick OK
Click Insert and select Select All
Click OK. 
Click Insert and OpenvinoWhisperTranscription
Click OK. 
Click Move Focus to Next and Select
Click OK
Click Select All
Click OK
Click Export Labels.
Click Select a file and choose where you would like to export the file and what name you would like the txt file to have.
For Track names select No.
Click Close

Assign hot key

Go to Edit/Preferences/Shortcuts
Search for Transcribe and select it.
Put your keyboard shortcut into the box to the left of Set and click Set and OK
To run the macro, click on the keyboard shortcut once you have some audio in your Audacity project.

Copy the text in the Transcription.txt file and use the following prompt in ChatGPT to add different speakers.
Edit as required.

Please transform the provided interview transcript by making the following adjustments:

Identify each unique speaker and consolidate their continuous speech. Label each section of uninterrupted dialogue with 'Speaker 1', 'Speaker 2', 'Speaker 3', etc., corresponding to each different speaker. Ensure that when the same speaker talks consecutively, their dialogue is grouped under a single label, avoiding repetition of speaker labels for continuous speech.

The goal is to create a clean and coherent transcript that clearly delineates who is speaking and presents their dialogue in an unbroken sequence, making it easier to follow the conversation flow.

**Comment by RyanMetcalfeInt8** [comment]
Thank you @joedale100! I will probably look into supporting whisper diarization using local models instead of ChatGPT (as that is a cloud-based service).

**Comment by joedale100** [comment]
Thank you Ryan! That would be awesome.

I would love to recommend that schools use this plug-in in order to transcribe different types of audio. Local speaker, die reservation would be amazing.

Here is an updated prompts to do the same thing with chat GPT:

Please apply speaker diarization to the provided interview transcript. Identify each unique speaker and consolidate their continuous speech. Label each section of uninterrupted dialogue with ‘Speaker 1’, ‘Speaker 2’, ‘Speaker 3’, etc., corresponding to each different speaker. Group continuous speech by the same speaker under a single label. The goal is to create a clear transcript delineating each speaker and presenting their dialogue in sequence.
