### ISSUE TITLE
Modules not showing up

### ISSUE THREAD

**Issue by damandale** [intel/openvino-plugins-ai-audacity#70]
I'm on a windows 11 64bit. I've uninstalled/reinstalled audacity multiple times. When I download the two files I unzip and unblock both before copying to audacity, but the modules still don't show up for me. Any ideas?

**Comment by RyanMetcalfeInt8** [comment]
Hmm, does the ```mod-openvino``` entry show up in Preference->modules?

**Comment by temran** [comment]
Same here. Win 11 Home 64 bit. Modules don't show up.

**Comment by RyanMetcalfeInt8** [comment]
@temran, does ```mod-openvino``` show up in Preference->modules??

**Comment by temran** [comment]
No. I tried other folders. Got the message: Module unsuitable X
The "openvino" module could not be loaded. 
Error: %1 is not a valid Win32 application.

**Comment by RyanMetcalfeInt8** [comment]
Are you using the 64-bit version of Audacity?

**Comment by temran** [comment]
Good hint! I have installed the 32 bit version 3.4.2. I found the 64 bit version and will give it a try.

**Comment by temran** [comment]
Even in the 64bit version the modules don't show up.

**Comment by RyanMetcalfeInt8** [comment]
Hi @temran,

I need a little more detail about the issue you're now seeing with 64-bit. Are you getting a new error message that pops up? 

Thanks,
Ryan

**Comment by temran** [comment]
No, I Place the unzipped  folders in the audacity folder.

Ryan Metcalfe ***@***.***> schrieb am Di. 26. März 2024 um
00:50:

**Comment by RandyTheK** [comment]
With mine the files are in the Program Files but do not show in Preferences:Modules nor in Effect. When I copied the downloaded files to Program Files I did get a warning that I didn't have admin privileges but allowed me to copy the files.

**Comment by RyanMetcalfeInt8** [comment]
Hi @RandyTheK, in Audacity folder there should be a folder called ```modules```. Inside of that, is there a file called ```mod-openvino.dll```?

**Comment by temran** [comment]
No

**Comment by RyanMetcalfeInt8** [comment]
Did you follow along, step-by-step with the installation video here? https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.4.2-R1

The contents of [Audacity-OpenVINO-Module-3.4.2-R1.zip](https://github.com/intel/openvino-plugins-ai-audacity/releases/download/v3.4.2-R1/Audacity-OpenVINO-Module-3.4.2-R1.zip) should be copied to ```Audacity``` folder, and this is the step that copies ```mod-openvino.dll``` to the right spot.

**Comment by RandyTheK** [comment]
It's inside the folder Audacity-OpenVINO-Module-3.4.2-R1. I should move it to modules?

**Comment by RyanMetcalfeInt8** [comment]
> It's inside the folder Audacity-OpenVINO-Module-3.4.2-R1. I should move it to modules?

Yes, but it seems like the installation video wasn't followed correctly, if that file is there. Can you start over, but perform exact same actions as is shown in the installation video here:  https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.4.2-R1

**Comment by RandyTheK** [comment]
The install video wouldn't play

**Comment by temran** [comment]
When I copy the module open-vino.dll into the "modules" folder, the module appears in the module settings, but it is not displayed in the effects.

Instead, the following message appears:


Module unsuitable 
The "mod-openvino" module could not be
be loaded.
Error: The specified module was not found.

**Comment by RyanMetcalfeInt8** [comment]
> Quality is built in, not added on. Why aren't these in the install?

Hmm, I'm not sure what you mean by this?

**Comment by RyanMetcalfeInt8** [comment]
> When I copy the module open-vino.dll into the "modules" folder, the module appears in the module settings, but it is not displayed in the effects.
> 
> Instead, the following message appears:
> 
> Module unsuitable The "mod-openvino" module could not be be loaded. Error: The specified module was not found.

If the only file that you copied there is mod-openvino.dll, then it will be missing the other required files in the zip file. As the installation video shows, please copy all files in the zip file.

**Comment by temran** [comment]
Thank you, I followed your video. Now it's working! :-)

**Comment by temran** [comment]
I followed the steps of your video. Thank you! It's working now.

Am Di., 26. März 2024 um 18:57 Uhr schrieb Ryan Metcalfe <
***@***.***>:

**Comment by RyanMetcalfeInt8** [comment]
Great. I'll close this issue -- @RandyTheK, I'm pretty confident that if you run full installation steps again, it will work, but feel free to keep commenting on this issue, and I can help.

**Comment by RandyTheK** [comment]
FYI- deleted and reinstalled as in the vid and presto

Thanks
________________________________

**Comment by iAnish** [comment]
> @temran, does `mod-openvino` show up in Preference->modules??

For me  'mod-openvino' was set to "no choice made". After setting it to enabled and restarting Audacity, it worked.

Thanks

![openvinomodule](https://github.com/user-attachments/assets/9adab1f7-eec8-48d5-a2f1-8b4eb98c1e3a)
