### ISSUE TITLE
Music Separation Error on Ubuntu 22.04

### ISSUE THREAD

**Issue by rkjk** [intel/openvino-plugins-ai-audacity#71]
I run an Ubuntu 22.04 system. Followed the steps outlined [here](https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/linux/README.md) and was able to get the module installed without any issues. 

I booted up Audacity and was able to successfully generate the Whisper transcription for a 5min file.

But Music Separation Errors out with this message:
`
18:45:19: Error: In Music Separation, exception: Exception from src/inference/src/core.cpp:116:
Exception from src/inference/src/model_reader.cpp:137:
Unable to read the model: /usr/local/lib/openvino-models/htdemucs_v4.onnx Please check that model format: onnx is supported and the model is correct. Available frontends: onnx paddle tf ir pytorch tflite 
`

The model seems to be in IR whereas the libopenvino expects the onnx file. This is weird
1. The documentation explicitly says to copy the .bin and .xml files, so I take it the IR model representation is expected
2. The error message includes IR as one of the supported formats, yet complains that the onnx file is missing. 

Let me know if I am missing something here. Thanks.

**Comment by RyanMetcalfeInt8** [comment]
Hi @rkjk,

Ah, I think I know what's going on. I've been updating the build README's on main branch with instructions to grab the models and populate the ```openvino-models``` folder in the way that the current plugins (from latest main) expect. But, in those instructions, I forgot to update the part that has you check out older tag:
```

```
cd openvino-plugins-ai-audacity
git checkout v3.4.2-R1
cd ..
```

So what's happening is, you're building the plugins from that tag (which, music separation was still expecting model in onnx format), but populating ```openvino-models``` in a way that the latest plugin expect (which is OpenVINO IR .xml/.bin).

My recommendation is to check out latest main (```git checkout main```) in your ```openvino-plugins-ai-audacity``` folder, and re-run the build command from your build folder. 

Let me know if you have any questions.
Thanks,
Ryan
