### ISSUE TITLE
Problem with generation of music

### ISSUE THREAD

**Issue by Giovani93** [intel/openvino-plugins-ai-audacity#81]
Hi.
I've found issue. Openvino music generation failed and here is the result showed in log of Audacity:
23:09:33: Error: In Music Generation, exception: Exception from src\inference\src\core.cpp:134:
[ GENERAL_ERROR ] Check 'false' failed at src\plugins\intel_gpu\src\plugin\program.cpp:401:
GPU program build failed!
Program build failed(0_part_46): You may enable OCL source dump to see the error log.

What can be problem?
I've entered something in the simple mode, as:
Harp, flute, sad, love

**Comment by RyanMetcalfeInt8** [comment]
Hi @Giovani93,

From your log, it seems like the OpenVINO framework had a problem prepping the model to run on your GPU. What kind of GPU do you have?

In the Music Generation settings window, on the right-side there are a list of devices. You can try changing them all to CPU to see if that works, as a workaround.

Thanks,
Ryan

**Comment by Giovani93** [comment]
It littlebid helped, but result is still 5 seconds, althought I set duration to 5 minutes. Can It be mistake of CPU?

**Comment by RyanMetcalfeInt8** [comment]
Hmm... can you try something longer than 5 seconds but shorter than 5 minutes (that would take a very long time to generate, btw). Can you try 15 secs?

**Comment by Giovani93** [comment]
I've made It, but It doesn't sounds still, like music. Maybe, I use some strange preferences, for example:
Happy, Summer, Ukulele
Reggae, Drums, Brass, Hammond organ, Guitar
It is true, that I listen various kinds of music, sometimes non-traditional.

**Comment by RyanMetcalfeInt8** [comment]
It sounds like it 'worked', but you're not pleased with the generated 'music'. You may need to experiment with the prompt and other settings -- this is sort of the nature of generative ai, in that it can be an iterative / experimental process to generate something that you find useful.
