### ISSUE TITLE
Audacity mod-openvivo dll not found , win 10

### ISSUE THREAD

**Issue by Musthyd** [intel/openvino-plugins-ai-audacity#83]
Hi,

i installed [Releases · intel/openvino-plugins-ai-audacity · GitHub](https://github.com/intel/openvino-plugins-ai-audacity/releases) but when i open audacity it says

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/2c151eb0-6e54-4d5b-a2c1-5e63effc0064)

and

mod-openvivo as failed

kindly suggest

**Comment by DJ-FilFire** [comment]
Good evening,
I have the same problem.
Here are some screenshots to inform you of my hardware and software configuration, concerning my laptop.
Thanking you for your help, best regards.
![Capture d’écran (69)](https://github.com/intel/openvino-plugins-ai-audacity/assets/165099366/178af054-3297-4dd3-abcf-b4bc295fd145)
![Capture d’écran (66)](https://github.com/intel/openvino-plugins-ai-audacity/assets/165099366/13dbd388-9f9a-4ab4-b177-0c5eb01b07fb)
![Capture d’écran (71)](https://github.com/intel/openvino-plugins-ai-audacity/assets/165099366/7f74cf3b-4ba8-4e39-89db-4e6d11c494fc)
![Capture d’écran (72)](https://github.com/intel/openvino-plugins-ai-audacity/assets/165099366/0503b3f3-ecd5-47f2-8fd6-c3df83d36ed7)
![Capture d’écran (73)](https://github.com/intel/openvino-plugins-ai-audacity/assets/165099366/e3662d92-0646-4868-9665-2bc0cbc67322)

**Comment by nonsuchpro** [comment]
Unfortunately, I get the same error pop-up. I did everything correctly according to the installation video and I've been using Audacity for a long time. Also, I am able to use many other AI applications with no issues. Is it possible my processor is missing a specific instruction set needed that you guys are using?
Thanks in advance for any help!

Audacity -  3.4.2 x64
Processor - Intel(R) Core(TM) i7 CPU 920  @ 2.67GHz   2.67 GHz
Installed RAM - 24.0 GB
Edition - Windows 10 Pro
Version - 22H2
Installed on - 2/‎1/‎2021
OS build - 19045.4170
Experience - Windows Feature Experience Pack 1000.19054.1000.0

I've also attached a CPU-Z output txt below if it helps any. 
[CPU-Z.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/14766843/CPU-Z.txt)

**Comment by Musthyd** [comment]
> Hi @Musthyd,
> 
> Can you list your Windows version and details about the CPU that you are using?
> 
> Thanks! Ryan

Hi Ryan,

Thanks for the reply, yes sure here is the screen shot please

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/0bbec16c-4e3b-4a18-8aef-68fc0f5f13d7)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/6561cffb-c3fe-4a12-8751-325a5db99dc5)

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8 ,

Here are the screen shots , Thanks 

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/65338a4e-faea-4606-9ef7-e4b6826341fd)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/5ea71e9d-db93-4309-975d-4fdbd0e55a8e)

**Comment by Musthyd** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/11ee30ca-44d2-467d-a00b-37687adec2c6)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165008128/b317c51b-8806-4bcb-9066-52f2cc251bcb)

**Comment by RyanMetcalfeInt8** [comment]
Hi @Musthyd, @nonsuchpro,

In both of these cases, the ```initialization routine failed``` error is because your CPUs do not support AVX / AVX2 instruction set. We may have a fix coming soon in our next release. Stay tuned.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @Musthyd,

We're getting close -- hopefully within the next couple of weeks we'll be ready to post it.

Thanks!
Ryan

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8 ,

Please leave a message whenever the fix is done. Appreciate your efforts and response. Thanks

Mustafa

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8 

Hope you are doing fine, was curious about the updates and fix. Is is done or work in progress?

Thanks

Mustafa

**Comment by RyanMetcalfeInt8** [comment]
Hi @Musthyd,

We should be posting the updated release next week to coincide with the upcoming Audacity 3.5.0 release. I know it's been a bit of a wait, so I appreciate your patience!

Thanks,
Ryan

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8 ,

Thanks for the update. Its very kind of you. Appreciate your efforts.

Regards,

Mustafa

**Comment by RyanMetcalfeInt8** [comment]
Hi @Musthyd, @nonsuchpro, @DJ-FilFire,

We've posted an updated release that should resolve this issue. You can find it here:
https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

I'll close this issue for now, but please feel free to keep commenting if you have questions or if you want to share results about whether the new release works for you.

Cheers!

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8,

Thanks i was able to install. I need to separate these two voices into individual files each with only one of the duets, can you please guide me on this. as to how to do this.
 eg: https://www.youtube.com/watch?v=T99m_1HgzxM 
In the above file if i need to separate into individual voices, how do we do it please.

Thanks

**Comment by RyanMetcalfeInt8** [comment]
Hi @Musthyd,

Glad the updated release is working for you! 

> I need to separate these two voices into individual files each with only one of the duets

This is a little bit more tricky, as we don't (yet) have a feature that separates individual voices into separate tracks. There is high demand for this feature though, so I've been on the lookout for other open source projects / AI models that support something like this.

Thanks,
Ryan

**Comment by Musthyd** [comment]
Hi @RyanMetcalfeInt8,

Thanks Ryan, if you get to know/develop one. Please let me know.

Thanks again. You are a gem

Mustafa
