### ISSUE TITLE
Open vino error on launch

### ISSUE THREAD

**Issue by Dipenmehta** [intel/openvino-plugins-ai-audacity#84]
Hi 
I downloaded the latest version of audacity (3.4.2). Then as shown in the video, downloaded the two zip files and then extracted them into the audacity folder - once extracted, the show up in the directory exactly as specified in the video (screenshot attached)

On launching the program it gives an error as shown in the screenshot. (attached) 
![audacity directory structure](https://github.com/intel/openvino-plugins-ai-audacity/assets/165041366/117d6094-05fe-43af-8f97-ca57bc3488d0)
![Openvino module error](https://github.com/intel/openvino-plugins-ai-audacity/assets/165041366/445274cb-c81c-4d1c-9866-dca8f346be27)

I have downloaded the exe file twice, reinstalled audacity twice, downloaded the zip files twice - but on launching audacity, I get the same error again. 

Can you please help?

Thanks

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dipenmehta,

Hmm, strange. I have a wiki dedicated to help debug this issue: https://github.com/intel/openvino-plugins-ai-audacity/wiki/Debugging-DLL-dependency-issues-on-Windows

Can you see if you can follow that and spot which DLL is missing?

Thanks,
Ryan

**Comment by Dipenmehta** [comment]
Hi Ryan

Thanks for the quick response – I ran the steps as you recommended in the wiki and here is the screenshot of the results

Please help with the next steps

Thanks

Dipen

***@***.***

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dipenmehta,

It looks like your screenshot didn't get pasted / uploaded properly. Can you try to add it by commenting directly on GitHub (instead of replying via email). Thanks!

Ryan

**Comment by Dipenmehta** [comment]
Sorry – here is the ***@***.***

**Comment by RyanMetcalfeInt8** [comment]
@Dipenmehta -- hmm, I don't think it worked that time either 😄 

It looks like you are trying to update this issue by replying via email, which could be why the image upload isn't working. I would recommend just adding a comment directly to this issue (https://github.com/intel/openvino-plugins-ai-audacity/issues/84).

**Comment by Dipenmehta** [comment]
![dependencies error](https://github.com/intel/openvino-plugins-ai-audacity/assets/165041366/db9acebb-4dd4-4a58-a3ea-f6acde481570)
Here you go !!!!

**Comment by Dipenmehta** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165041366/e823fe53-808d-4671-b37f-e712584b5e06)
This is the list of DLLs installed in audacity

**Comment by RyanMetcalfeInt8** [comment]
Hi @Dipenmehta,

Hmm, strange. I don't understand why that 'Dependencies' tools is listing those DLL's as not found, when I can see them sitting in your 'Audacity' folder...

Perhaps these DLL's are getting 'blocked'.

For one of the DLL's that it claims that it cannot find (openvino.dll, for example), in Windows explorer can you right-click and go to 'properties'. In the 'general' tab, look at the bottom for a 'security' section to see if there is an 'Unblock' option. Let me know if you see something like that.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
I remember now that someone else reported that they needed to 'unblock' the zip files before copying the content. See here: https://github.com/intel/openvino-plugins-ai-audacity/issues/41#issuecomment-1932621110

Maybe you need to do the same?

**Comment by Dipenmehta** [comment]
OK - the unblock option appears in open vino, whisper and both stable diffusion dlls and i have unblocked them

**Comment by Dipenmehta** [comment]
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/165041366/8156a6e7-2bf9-453b-8727-784d886b6c9a)

This is what the dependencies check shows now

**Comment by Dipenmehta** [comment]
still getting same error - went to edit - preferences - open vino - and changed from failed to enabled but same issue

**Comment by RyanMetcalfeInt8** [comment]
You may want to perform 'unblock' operation on the downloaded zip files, and then re-copy extract everything.

**Comment by Dipenmehta** [comment]
ok - on it now

**Comment by Dipenmehta** [comment]
Brilliant - that worked - lifesaver!!!

Thanks a lot for all your effort

Cheers

**Comment by RyanMetcalfeInt8** [comment]
Cool, nice! I'll close this as completed then.

And just to note, upcoming releases will use installers which should be way less problematic than these zip files.

**Comment by Dipenmehta** [comment]
next issue - i launched it and can see the open vino plugin - but the software does not import mp3 - says download ffmpeg?

**Comment by RyanMetcalfeInt8** [comment]
Ah, that one doesn't have anything to do with these plugins, but here's how to fix it: https://support.audacityteam.org/basics/installing-ffmpeg

Basically:
1. download & install this: https://lame.buanzo.org/FFmpeg_5.0.0_for_Audacity_on_Windows_x86_64.exe
2. And then launch Audacity again.

**Comment by Dipenmehta** [comment]
Thanks. All sorted

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
