### ISSUE TITLE
Module unsuitable

### ISSUE THREAD

**Issue by SadPuppyX** [intel/openvino-plugins-ai-audacity#85]
I get the following error when trying to launch Audacity after copying the files:

![Skärmbild 2024-03-26 154651](https://github.com/intel/openvino-plugins-ai-audacity/assets/165051112/5de07775-79bb-46c7-999d-85c99deaeaf9)

**Comment by RyanMetcalfeInt8** [comment]
Hi @SadPuppyX, are you using 64-bit version of Audacity 3.4.2?

**Comment by RyanMetcalfeInt8** [comment]
Hi @SadPuppyX,

Inside of Audacity, if you go to Help->About Audacity, and then select 'Build Information' tab, you can see this kind of information next to 'Build type'. For example, the following shows a 64-bit build:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/e6190b22-6fed-435b-abad-bdb1ffb95428)

**Comment by SadPuppyX** [comment]
@RyanMetcalfeInt8 

Yes, for some reason it was 32 bit. I can't fathom why I would have the 32 bit version, but I downloaded the 64 bit now and
installed it and everything seems fine. At least I don't get an error at start up, will test more later.

Thanks a lot for the help! Appreciated! Cheers!

**Comment by RyanMetcalfeInt8** [comment]
Cool, glad you were able to get it working. I'll close this one as completed for now. Cheers!
