### ISSUE TITLE
does openvino support Intel(R) Pentium(R) CPU G4560?

### ISSUE THREAD

**Issue by SplendidPiePizza** [intel/openvino-plugins-ai-audacity#89]
when i installed openvino it said mod-openvino.dll cannot link. i use dependencies and it all check but it's still error, why is this always happening to me??? does anyone know why? also does it support Intel(R) Pentium(R) CPU G4560?
i am using windows 10 x64 and also audacity x64 if not work does it also work with AMD A4-6210 APU with AMD Radeon R3 Graphics?

**Comment by SplendidPiePizza** [comment]
> Hi @SplendidPiePizza,
> 
> There is an issue with the current release where, CPUs that do not support AVX / AVX2 instructions will have this problem. Your Pentium G4560 only supports up to SSE4.2.
> 
> We have another release coming soon that will address this problem.
> 
> Thanks, Ryan

what about AMD A4-6210 APU with AMD Radeon R3 Graphics??

**Comment by RyanMetcalfeInt8** [comment]
I'm not sure. If AMD A4-6210 supports AVX / AVX2, then it might work just fine... you'll have to give it a try.

**Comment by SplendidPiePizza** [comment]
> I'm not sure. If AMD A4-6210 supports AVX / AVX2, then it might work just fine... you'll have to give it a try.

how to know if it supports avx/ avx2?

**Comment by RyanMetcalfeInt8** [comment]
First link when I googled "AMD A4-6210".
https://www.cpu-world.com/CPUs/Puma/AMD-A4-Series%20A4-6210.html

Look under 'Extensions & Technologies'. Looks like it supports AVX, but not AVX2. I'm not sure what would happen in this case if you tried it.

**Comment by SplendidPiePizza** [comment]
> First link when I googled "AMD A4-6210". https://www.cpu-world.com/CPUs/Puma/AMD-A4-Series%20A4-6210.html
> 
> Look under 'Extensions & Technologies'. Looks like it supports AVX, but not AVX2. I'm not sure what would happen in this case if you tried it.

this is a really long issue but when a new release was introduced. Will it support sse4.2? the amd cpu i am using supports it.

**Comment by RyanMetcalfeInt8** [comment]
Next release should support SSE4.2.

**Comment by RyanMetcalfeInt8** [comment]
Hi @SplendidPiePizza,

We have posted the updated release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

This release should support SSE4.2 CPUs. I'll close this issue for now, but feel free to keep commenting if you have questions.

Thanks,
Ryan
