### ISSUE TITLE
Runtime Unicode path error

### ISSUE THREAD

**Issue by bluemoehre** [intel/openvino-plugins-ai-audacity#91]
Every time I try to use a Vino effect, Audacity tries to create a new folder in my file system and fails because of the permissions:

<img width="353" alt="image" src="https://github.com/intel/openvino-plugins-ai-audacity/assets/1735386/5c36ed7d-e111-402e-b7cc-4dba75e27c49">

**Log:**
> 02:34:07: Audacity 3.4.2
> 02:34:14: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
> 02:34:14: Error: In Music Separation, exception: Exception from src\inference\src\core.cpp:237:
> **Couldn't create directory [C:\Users\BlueMÃ¶hre], err=Permission denied)**
> 02:34:15: Operation 'OpenVINO Music Separation' took 0.021000 seconds. Poll was called 2 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.

Seems to be a charset / Unicode problem. The correct (existing) folder would be `C:\Users\BlueMöhre`.

**Comment by RyanMetcalfeInt8** [comment]
Hi @bluemoehre,

Yes, sorry about that. This is a known bug with the initial release, where as you said, OpenVINO incorrectly handles the unicode path. This should be fixed in the upcoming release (Next 2 or 3 weeks)

Thanks,
Ryan

**Comment by bluemoehre** [comment]
Thanks a lot!
