### ISSUE TITLE
How do this work with the portableapp of Audacity?  

### ISSUE THREAD

**Issue by zbart97** [intel/openvino-plugins-ai-audacity#92]
I am attempting to add this to portable Audacity.  When downloading to the program folder as shown the new modules do not show up.

Any thoughts on how to fix this?

**Comment by RyanMetcalfeInt8** [comment]
Hmm, it should be the same install procedure. Does 'mod-openvino' show up in Preferences->Modules?

**Comment by SMESH109** [comment]
After an update via PortableApps platform, the whole installed OpenVino stuff is even gone.
