### ISSUE TITLE
Message Unable to open the "mod-openvino module" when opening Audacity - Module unsuitable

### ISSUE THREAD

**Issue by Paul-Smith1** [intel/openvino-plugins-ai-audacity#93]
Hi, I've tried the solutions posted elsewhere but still get this error.
Running Win 7 64 Bit with Audacity 3.4.2
Have installed exactly as described several times and after enabling openvino in preferences, closing and re opening Audaccity the above message is displayed. I can close the message and Audacity will continue opening but in preferences it says that Openvino has failed.

I have tried this in several fresh Audacity installs and get the same result. I am copying the files as described into the folder containing Audacity .exe.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Paul-Smith1,

What kind of CPU are you using? Can you post the full model name?

Thanks,
Ryan

**Comment by Paul-Smith1** [comment]
Thanks for your quick reply Ryan, I'm using a Dell Lattitude E6410 laptop. The CPU is an Intel Core i5  M520@2.4Ghz I have 6Gb of RAM installed

**Comment by Paul-Smith1** [comment]
Hi Ryan, I'm guessing that an i5 won't cut it so I've tried again on another laptop runiing an i7 and it works perfectly. Many thanks for your help. Paul

**Comment by RyanMetcalfeInt8** [comment]
Hi @Paul-Smith1,

Sorry for my delay in getting back to you. Our initial release only supports processors with AVX/AVX2 support, which is why your M520 didn’t work. Our next release should address that so stay tuned. Glad you were able to get it running on that i7 in the meantime!
