### ISSUE TITLE
openvino-models' couldn't be created error 5

### ISSUE THREAD

**Issue by dmazilu** [intel/openvino-plugins-ai-audacity#95]
When trying to use Openvino ai effect music separation this error comes up

19:44:44: Audacity 3.4.2
Log Cleared.
19:45:03: Error: Directory 'C:\Program Files\Audacity\openvino-models' couldn't be created (error 5: Access is denied.)
19:45:03: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
19:45:03: Error: In Music Separation, exception: Exception from src\inference\src\core.cpp:134:
[ GENERAL_ERROR ] Model file C:\Program Files\Audacity\openvino-models\htdemucs_v4.onnx cannot be opened!

19:45:04: Operation 'OpenVINO Music Separation' took 0.025000 seconds. Poll was called 2 times and took 0.000001 seconds. Yield was called 0 times and took 0.000000 seconds.

**Comment by RyanMetcalfeInt8** [comment]
Hi @dmazilu,

it looks like perhaps the ‘openvino-models’ directory wasn’t copied correctly into the Audacity\ folder. Can you double check it?
