### ISSUE TITLE
Problem with generation of music

### ISSUE THREAD

**Issue by yeyi913** [intel/openvino-plugins-ai-audacity#96]
9:25:35: Audacity 3.4.2
9:25:35: FFmpeg libraries loaded successfully from: C:\Program Files\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
9:25:41: sqlite3 message: (1) no such table: project in "SELECT 1 FROM project LIMIT 1;"
9:25:41: FFmpeg libraries loaded successfully from: C:\Program Files\ffmpeg-6.1.1-full_build-shared\bin\avformat-60.dll
9:29:39: Error: In Music Generation, exception: If num_output_segments is set, it must be <= num_interpolation_steps
9:29:41: Operation 'OpenVINO Music Generation' took 5.003000 seconds. Poll was called 10 times and took 0.018326 seconds. Yield was called 10 times and took 0.009556 seconds.

What can be problem?
Start Prompt (in Advanced Mode using Chinese input):
In the depths of the night, neon lights flash, and the bustling streets are filled with a dense atmosphere of electronic music. A unique melody, a blend of traditional Chinese melodies and futuristic electronic bass, rises quietly. The notes dance, like fireworks exploding, dazzling and captivating.
The strings are gently plucked, and the melodious sound of the guzheng intertwines with the modern feel of the electronic synthesizer, creating a unique sense of time and space. The melody gradually rises, as if traversing a millennium-old temporal tunnel, perfectly fusing the ancient oriental charm with modern electronic music.
The drum beats grow stronger, and the bass thumps deeply and powerfully, like the heartbeat of the city, pulsating in every corner. The electronic effects soar like meteors across the night sky, leaving behind a brilliant glow.

End Prompt:
The music gradually builds to a climax, the melody more intense and passionate, like a raging river, unstoppable. Each note is filled with strength and emotion, making one feel as if they are immersed in a vibrant future world.
Finally, the music fades away in a long, lingering coda, like the serene night sky after a fireworks display. That unique melody, that music that blends Chinese charm with futuristic electronic bass, is like a beautiful dream, leaving a lasting impression that is difficult to forget.

（Below is the Chinese translation）
Start Prompt：
深夜的都市，霓虹灯闪烁，繁华的街头弥漫着浓厚的电子音乐氛围。一曲独特的旋律，融合了中式旋律与未来电子Bass，悄然响起。音符跳跃，如同烟花绽放，绚烂夺目。
琴弦轻拨，古筝的悠扬与电子合成器的现代感交织在一起，创造出一种独特的时空感。旋律逐渐升高，仿佛穿越千年的时空隧道，将古老的东方韵味与现代电子乐完美融合。
鼓点渐强，Bass音深沉而有力，如同都市的心跳，跳动在每一个角落。电子音效如同流星划过夜空，留下璀璨的光芒。
End Prompt：
乐曲渐入高潮，旋律更加激昂，如同江河奔腾，势不可挡。每一个音符都充满了力量与激情，让人仿佛置身于一个充满活力的未来世界。
最终，乐曲在一段悠长的尾声中缓缓落下，如同烟花绽放后的宁静夜空。那独特的旋律，那融合了中式韵味与未来电子Bass的音乐，如同一个美丽的梦，让人久久难以忘怀。

**Comment by RyanMetcalfeInt8** [comment]
Hi @yeyi913,

Sorry for my delay in responding to this. We have just released a new version of the plugins that replace Riffusion-based Music Generation with MusicGen LLM. You can download it here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Note your prompts seem very lengthy -- I would try something shorter, such as 50 words or less for now.
