### ISSUE TITLE
Audacity crashed with openvino GPU support.

### ISSUE THREAD

**Issue by Ceratopsia** [intel/openvino-plugins-ai-audacity#97]
Hi, I tried to run this plugin with my a750 GPU and it shows some problems.
My intel ARC a750 GPU driver version is 31.0.101.5379, and there is information about the error:

> Failed application name: Audacity.exe, version: 3.4.2.0, timestamp: 0x6606d3d8
> Error module name: OpenCLOn12.dll, version: 0.0.0.0, timestamp: 0x66059684
> Exception Code: 0xc0000005
> Error Displacement: 0x000000000002a919
> Error Handling Constant Identifier: 0xE58
> Failed application start time: 0x1DA84B828411BDA
> Faulting application path: S:\Whisper\audacity-build\Release\Audacity.exe
> Faulting Module Path: C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2403.9.0_x64__8wekyb3d8bbwe\x64\OpenCLOn12.dll
> Report Identifier: f68eecfc-a5ec-4949-a307-580e3caae0b5
> Full name of the Faulting package: 
> Faulting Suite Relative Application Identifier: 

But I worked with my CPU and another GPU without this problem.
I don't know how to solve it.
Thank you.

**Comment by hitesh-geek** [comment]
Hi , i have same problem.
My Laptop has a dedicated gpu  i.e nvidia 4050 it works fine when i use music separation with UHD graphics but when i switch it nvidia graphics its show error. 
Can someone help me with this problem.
Thank you.
Here is the log file
[Log.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/14967741/Log.txt)

**Comment by RyanMetcalfeInt8** [comment]
> Hi, I tried to run this plugin with my a750 GPU and it shows some problems. My intel ARC a750 GPU driver version is 31.0.101.5379, and there is information about the error:
> 
> > Failed application name: Audacity.exe, version: 3.4.2.0, timestamp: 0x6606d3d8
> > Error module name: OpenCLOn12.dll, version: 0.0.0.0, timestamp: 0x66059684
> > Exception Code: 0xc0000005
> > Error Displacement: 0x000000000002a919
> > Error Handling Constant Identifier: 0xE58
> > Failed application start time: 0x1DA84B828411BDA
> > Faulting application path: S:\Whisper\audacity-build\Release\Audacity.exe
> > Faulting Module Path: C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2403.9.0_x64__8wekyb3d8bbwe\x64\OpenCLOn12.dll
> > Report Identifier: f68eecfc-a5ec-4949-a307-580e3caae0b5
> > Full name of the Faulting package:
> > Faulting Suite Relative Application Identifier:
> 
> But I worked with my CPU and another GPU without this problem. I don't know how to solve it. Thank you.

Hi @Ceratopsia,

Sorry for the delay, I'll try on an A770 that I have access to within the next few days to see if I can reproduce. We also have a new version of these plugins coming out soon that uses OpenVINO 2024.0 (latest version), so that might solve the issue as well.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
> Hi , i have same problem. My Laptop has a dedicated gpu i.e nvidia 4050 it works fine when i use music separation with UHD graphics but when i switch it to nvidia graphics it shows error. Can someone help me with this problem. Thank you. Here is the log file [Log.txt](https://github.com/intel/openvino-plugins-ai-audacity/files/14967741/Log.txt)

Unfortunately, I don't have any nvidia discrete cards to test with. As far as I understand, NVidia cards don't support OpenVINO very well -- they might be functional for certain models, but I've heard that performance isn't very good. At any rate, this would be an OpenVINO-level issue and not necessarily an issue that I would be able to resolve at the plugin-level. Sorry!

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment]
Hi @Ceratopsia,

Can you try with the latest version of these plugins? 

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

These use OpenVINO 2024.0, so hopefully you will find this issue resolved. Please let me know whether this solved your issue. Thanks!

**Comment by Ceratopsia** [comment]
I have tried the new release with Openvino Whisper and AI Effect.
It's finally working well on my a750 GPU!
Thank you so much for solving this problem👍
Do I need to close this issue thread or just keep it on?

**Comment by hariji814** [comment]
AMD R7 5800U has this problem
问题签名
问题事件名称:	BEX64
应用程序名:	TecnoAI_Server.exe
应用程序版本:	[0.1.0.0](http://0.1.0.0/)
应用程序时间戳:	694cc59c
故障模块名称:	OpenCLOn12.dll
故障模块版本:	[0.0.0.0](http://0.0.0.0/)
故障模块时间戳:	68c489a5
异常偏移:	00000000000eb305
异常代码:	c0000409
异常数据:	0000000000000007
OS 版本:	10.0.26200.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	fa15
其他信息 2:	fa150787a59424ef62e5c128fdc8f240
其他信息 3:	fa44
其他信息 4:	fa44dcf399e55fb61271a1fbcb4f494f

关于该问题的额外信息
存储段 ID:	d0f071f1821cd7cd23590ba681f34811 (1394158369420560401)

**Comment by RyanMetcalfeInt8** [comment]
> AMD R7 5800U has this problem

Hmm, I'm not quite sure what this is. I have no idea what `TecnoAI_Server.exe` is.
