### ISSUE TITLE
"initialisingroutine of dynamic link library failed"

### ISSUE THREAD

**Issue by rensjoost** [intel/openvino-plugins-ai-audacity#98]
computer says : "initialisingroutine of dynamic link library failed".....

anyone?

thank you

**Comment by RyanMetcalfeInt8** [comment]
Hi @rensjoost, what is the model of CPU that you are using?

**Comment by rensjoost** [comment]
intel cerion (r) n5100 @1.10ghz  1.11 ghz

thank you in advance.

Op di 2 apr 2024 om 14:15 schreef Ryan Metcalfe ***@***.***>:

**Comment by Newjohnm** [comment]
I to had got the same dll initialization error. I am running a windows 10 pro desktop with an intel i5 4 cores. Plenty of memory and hd space. I followed the install instructions to the tee as well. Thanks you all in advance for all that you do here!

**Comment by Casper1544** [comment]
Hello all , have the same issue (( a routine of actualization of library dynamix of dll failed - excuse my english )) after installing both files unzipped in audacity folder and activate it in preference . i am using w10 I7 - 870 16gb memory

**Comment by Tony1965** [comment]
It won't work on my Intel Pentium Quad Core N4200 Laptop, but will work on my Intel I5 Laptop. so it looks like a CPU issue.

Not sure if you already know, but if you go to the Audacity home page there are two options for downloading Audacity.
1. Audacity on it's own.
2. Audacity + samples and effects. (MUSE Hub)

Using option 2 will download Muse Hub which has some good free plug-ins. I'd advice that you uninstall Audacity first, install the MUSE Hub and then install Audacity from there.

Hope this helps?

**Comment by rensjoost** [comment]
Thanks, I'll check it out!

Op zo 7 apr. 2024 12:38 schreef Tony1965 ***@***.***>:

**Comment by RyanMetcalfeInt8** [comment]
Hi all,

We've released a new version of these plugins that should solve the 'initialization' error in some cases. Can you give it a try? You can download the release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

I'll close this for now, but feel free to keep commenting if you have questions, issues, or other feedback.

Thanks!

**Comment by Newjohnm** [comment]
Thanks Ryan, I'll download and give it a go.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ryan Metcalfe ***@***.***> Date: 4/22/24  8:56 PM  (GMT-05:00) To: intel/openvino-plugins-ai-audacity ***@***.***> Cc: Newjohnm ***@***.***>, Comment ***@***.***> Subject: Re: [intel/openvino-plugins-ai-audacity] "initialisingroutine of
  dynamic link library failed" (Issue #98) 
Hi all,
We've released a new version of these plugins that should solve the 'initialization' error in some cases. Can you give it a try? You can download the release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
I'll close this for now, but feel free to keep commenting if you have questions, issues, or other feedback.
Thanks!
