### ISSUE TITLE
issue while transcribing 

### ISSUE THREAD

**Issue by ntikoo** [intel/openvino-plugins-ai-audacity#99]
17:05:53: Error: whisper_init_from_file_with_params(C:\Program Files\Audacity\openvino-models\ggml-base.bin, ...) failed

**Comment by gblong1** [comment]
Hi @ntikoo - Is your issue only with Whisper? Can you provide some more details about your system (processor, memory, etc)? 

Thanks!

**Comment by RyanMetcalfeInt8** [comment]
Hi @ntikoo,

Can you try with the new release? https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Thanks!
